// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (name, username, password_hash, enabled, role) VALUES ($1, $2, $3, $4, $5) RETURNING id, name, username, password_hash, enabled, role, created_at, totp_secret
`

type CreateAdminParams struct {
	Name         string `json:"name"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Enabled      bool   `json:"enabled"`
	Role         string `json:"role"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Name,
		arg.Username,
		arg.PasswordHash,
		arg.Enabled,
		arg.Role,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.Enabled,
		&i.Role,
		&i.CreatedAt,
		&i.TotpSecret,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, name, username, password_hash, enabled, role, created_at, totp_secret FROM admins WHERE id = $1
`

func (q *Queries) GetAdmin(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdmin, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.Enabled,
		&i.Role,
		&i.CreatedAt,
		&i.TotpSecret,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, name, username, password_hash, enabled, role, created_at, totp_secret FROM admins WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.Enabled,
		&i.Role,
		&i.CreatedAt,
		&i.TotpSecret,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (admin_id, action, target_type, target_id, details, ip) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	AdminID    *int64          `json:"admin_id"`
	Action     string          `json:"action"`
	TargetType string          `json:"target_type"`
	TargetID   *int64          `json:"target_id"`
	Details    json.RawMessage `json:"details"`
	Ip         string          `json:"ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.Ip,
	)
	return err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, name, username, password_hash, enabled, role, created_at, totp_secret FROM admins ORDER BY username
`

func (q *Queries) ListAdmins(ctx context.Context) ([]Admin, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Admin{}
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.PasswordHash,
			&i.Enabled,
			&i.Role,
			&i.CreatedAt,
			&i.TotpSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditActions = `-- name: ListAuditActions :many
SELECT DISTINCT action FROM audit_log ORDER BY action
`

// The actions recorded, for the filter's suggestions.
func (q *Queries) ListAuditActions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAuditActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT a.id, a.admin_id, a.created_at, a.action, a.target_type, a.target_id, a.details, a.ip, ad.username AS admin_username
FROM audit_log a LEFT JOIN admins ad ON ad.id = a.admin_id
WHERE ($2::bigint IS NULL OR a.admin_id = $2)
  AND ($3::text IS NULL OR a.action LIKE $3::text || '%')
  AND ($4::timestamptz IS NULL OR a.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR a.created_at < $5::timestamptz)
  AND ($6::bigint IS NULL OR a.id < $6)
ORDER BY a.id DESC
LIMIT $1
`

type ListAuditLogParams struct {
	Limit    int32      `json:"limit"`
	AdminID  *int64     `json:"admin_id"`
	Action   *string    `json:"action"`
	FromTime *time.Time `json:"from_time"`
	ToTime   *time.Time `json:"to_time"`
	BeforeID *int64     `json:"before_id"`
}

type ListAuditLogRow struct {
	ID            int64           `json:"id"`
	AdminID       *int64          `json:"admin_id"`
	CreatedAt     time.Time       `json:"created_at"`
	Action        string          `json:"action"`
	TargetType    string          `json:"target_type"`
	TargetID      *int64          `json:"target_id"`
	Details       json.RawMessage `json:"details"`
	Ip            string          `json:"ip"`
	AdminUsername *string         `json:"admin_username"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.Limit,
		arg.AdminID,
		arg.Action,
		arg.FromTime,
		arg.ToTime,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.CreatedAt,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.Ip,
			&i.AdminUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdminPassword = `-- name: SetAdminPassword :exec
UPDATE admins SET password_hash = $2 WHERE id = $1
`

type SetAdminPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) SetAdminPassword(ctx context.Context, arg SetAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, setAdminPassword, arg.ID, arg.PasswordHash)
	return err
}

const setAdminTOTP = `-- name: SetAdminTOTP :exec
UPDATE admins SET totp_secret = $2 WHERE id = $1
`

type SetAdminTOTPParams struct {
	ID         int64   `json:"id"`
	TotpSecret *string `json:"totp_secret"`
}

func (q *Queries) SetAdminTOTP(ctx context.Context, arg SetAdminTOTPParams) error {
	_, err := q.db.Exec(ctx, setAdminTOTP, arg.ID, arg.TotpSecret)
	return err
}

const updateAdmin = `-- name: UpdateAdmin :one
UPDATE admins SET name = $2, username = $3, enabled = $4, role = $5 WHERE id = $1 RETURNING id, name, username, password_hash, enabled, role, created_at, totp_secret
`

type UpdateAdminParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Enabled  bool   `json:"enabled"`
	Role     string `json:"role"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, updateAdmin,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Enabled,
		arg.Role,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.Enabled,
		&i.Role,
		&i.CreatedAt,
		&i.TotpSecret,
	)
	return i, err
}
