// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appeals.sql

package sqlc

import (
	"context"
	"time"
)

const adminListAppeals = `-- name: AdminListAppeals :many
SELECT a.id, a.participation_id, a.task_id, a.submission_id, a.created_at, a.text, a.status, a.response, a.handled_by, a.handled_at, u.username, t.name AS task_name, ad.username AS handler
FROM participations p
JOIN appeals a ON a.participation_id = p.id
JOIN users u ON u.id = p.user_id
LEFT JOIN tasks t ON t.id = a.task_id
LEFT JOIN admins ad ON ad.id = a.handled_by
WHERE p.contest_id = $1::bigint
  AND ($2::text IS NULL OR a.status = $2::text)
ORDER BY (a.status = 'open') DESC, a.created_at
`

type AdminListAppealsParams struct {
	ContestID int64   `json:"contest_id"`
	Status    *string `json:"status"`
}

type AdminListAppealsRow struct {
	ID              int64      `json:"id"`
	ParticipationID int64      `json:"participation_id"`
	TaskID          *int64     `json:"task_id"`
	SubmissionID    *int64     `json:"submission_id"`
	CreatedAt       time.Time  `json:"created_at"`
	Text            string     `json:"text"`
	Status          string     `json:"status"`
	Response        string     `json:"response"`
	HandledBy       *int64     `json:"handled_by"`
	HandledAt       *time.Time `json:"handled_at"`
	Username        string     `json:"username"`
	TaskName        *string    `json:"task_name"`
	Handler         *string    `json:"handler"`
}

// A contest's appeals, open ones first (the participations of the contest,
// then appeals_participation_idx); optionally one status.
func (q *Queries) AdminListAppeals(ctx context.Context, arg AdminListAppealsParams) ([]AdminListAppealsRow, error) {
	rows, err := q.db.Query(ctx, adminListAppeals, arg.ContestID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAppealsRow{}
	for rows.Next() {
		var i AdminListAppealsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.TaskID,
			&i.SubmissionID,
			&i.CreatedAt,
			&i.Text,
			&i.Status,
			&i.Response,
			&i.HandledBy,
			&i.HandledAt,
			&i.Username,
			&i.TaskName,
			&i.Handler,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const answerAppeal = `-- name: AnswerAppeal :exec
UPDATE appeals SET status = $1::text, response = $2::text, handled_by = $3, handled_at = now()
WHERE id = $4::bigint
`

type AnswerAppealParams struct {
	Status    string `json:"status"`
	Response  string `json:"response"`
	HandledBy *int64 `json:"handled_by"`
	ID        int64  `json:"id"`
}

func (q *Queries) AnswerAppeal(ctx context.Context, arg AnswerAppealParams) error {
	_, err := q.db.Exec(ctx, answerAppeal,
		arg.Status,
		arg.Response,
		arg.HandledBy,
		arg.ID,
	)
	return err
}

const countAppealsByParticipation = `-- name: CountAppealsByParticipation :one
SELECT count(*)::bigint FROM appeals WHERE participation_id = $1::bigint
`

func (q *Queries) CountAppealsByParticipation(ctx context.Context, participationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAppealsByParticipation, participationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOpenAppeals = `-- name: CountOpenAppeals :one
SELECT count(*)::bigint FROM participations p JOIN appeals a ON a.participation_id = p.id
WHERE p.contest_id = $1::bigint AND a.status = 'open'
`

func (q *Queries) CountOpenAppeals(ctx context.Context, contestID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenAppeals, contestID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAppeal = `-- name: CreateAppeal :one
INSERT INTO appeals (participation_id, task_id, submission_id, text)
VALUES ($1::bigint, $2, $3, $4::text)
RETURNING id, participation_id, task_id, submission_id, created_at, text, status, response, handled_by, handled_at
`

type CreateAppealParams struct {
	ParticipationID int64  `json:"participation_id"`
	TaskID          *int64 `json:"task_id"`
	SubmissionID    *int64 `json:"submission_id"`
	Text            string `json:"text"`
}

func (q *Queries) CreateAppeal(ctx context.Context, arg CreateAppealParams) (Appeal, error) {
	row := q.db.QueryRow(ctx, createAppeal,
		arg.ParticipationID,
		arg.TaskID,
		arg.SubmissionID,
		arg.Text,
	)
	var i Appeal
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.SubmissionID,
		&i.CreatedAt,
		&i.Text,
		&i.Status,
		&i.Response,
		&i.HandledBy,
		&i.HandledAt,
	)
	return i, err
}

const getAppealContest = `-- name: GetAppealContest :one
SELECT p.contest_id FROM appeals a JOIN participations p ON p.id = a.participation_id WHERE a.id = $1::bigint
`

// The contest of an appeal (to go back to its list).
func (q *Queries) GetAppealContest(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getAppealContest, id)
	var contest_id int64
	err := row.Scan(&contest_id)
	return contest_id, err
}

const getOwnSubmissionTask = `-- name: GetOwnSubmissionTask :one
SELECT task_id FROM submissions WHERE id = $1::bigint AND participation_id = ANY($2::bigint[])
`

type GetOwnSubmissionTaskParams struct {
	ID               int64   `json:"id"`
	ParticipationIds []int64 `json:"participation_ids"`
}

// The task of a submission, if it belongs to one of the participations.
func (q *Queries) GetOwnSubmissionTask(ctx context.Context, arg GetOwnSubmissionTaskParams) (int64, error) {
	row := q.db.QueryRow(ctx, getOwnSubmissionTask, arg.ID, arg.ParticipationIds)
	var task_id int64
	err := row.Scan(&task_id)
	return task_id, err
}

const listAppealsByParticipation = `-- name: ListAppealsByParticipation :many
SELECT a.id, a.participation_id, a.task_id, a.submission_id, a.created_at, a.text, a.status, a.response, a.handled_by, a.handled_at, t.name AS task_name
FROM appeals a LEFT JOIN tasks t ON t.id = a.task_id
WHERE a.participation_id = $1::bigint
ORDER BY a.created_at DESC
`

type ListAppealsByParticipationRow struct {
	ID              int64      `json:"id"`
	ParticipationID int64      `json:"participation_id"`
	TaskID          *int64     `json:"task_id"`
	SubmissionID    *int64     `json:"submission_id"`
	CreatedAt       time.Time  `json:"created_at"`
	Text            string     `json:"text"`
	Status          string     `json:"status"`
	Response        string     `json:"response"`
	HandledBy       *int64     `json:"handled_by"`
	HandledAt       *time.Time `json:"handled_at"`
	TaskName        *string    `json:"task_name"`
}

// A contestant's appeals, newest first (appeals_participation_idx).
func (q *Queries) ListAppealsByParticipation(ctx context.Context, participationID int64) ([]ListAppealsByParticipationRow, error) {
	rows, err := q.db.Query(ctx, listAppealsByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppealsByParticipationRow{}
	for rows.Next() {
		var i ListAppealsByParticipationRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.TaskID,
			&i.SubmissionID,
			&i.CreatedAt,
			&i.Text,
			&i.Status,
			&i.Response,
			&i.HandledBy,
			&i.HandledAt,
			&i.TaskName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
