// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aws.sql

package sqlc

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"
)

const adminContestCounts = `-- name: AdminContestCounts :many
SELECT c.id,
       (SELECT count(*) FROM participations p WHERE p.contest_id = c.id) AS participations,
       (SELECT count(*) FROM tasks t WHERE t.contest_id = c.id) AS tasks,
       (SELECT count(*) FROM submissions s JOIN participations p ON p.id = s.participation_id
         WHERE p.contest_id = c.id) AS submissions
FROM contests c
`

type AdminContestCountsRow struct {
	ID             int64 `json:"id"`
	Participations int64 `json:"participations"`
	Tasks          int64 `json:"tasks"`
	Submissions    int64 `json:"submissions"`
}

// Dashboard counters per contest.
func (q *Queries) AdminContestCounts(ctx context.Context) ([]AdminContestCountsRow, error) {
	rows, err := q.db.Query(ctx, adminContestCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminContestCountsRow{}
	for rows.Next() {
		var i AdminContestCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Participations,
			&i.Tasks,
			&i.Submissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) AdminCountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetParticipation = `-- name: AdminGetParticipation :one
SELECT p.id, p.contest_id, p.user_id, p.team_id, p.password_hash, p.ip, p.starting_time, p.delay_time_s, p.extra_time_s, p.hidden, p.unrestricted, p.login_nonce, u.username, u.first_name, u.last_name, c.name AS contest_name
FROM participations p
JOIN users u ON u.id = p.user_id
JOIN contests c ON c.id = p.contest_id
WHERE p.id = $1
`

type AdminGetParticipationRow struct {
	ID           int64          `json:"id"`
	ContestID    int64          `json:"contest_id"`
	UserID       int64          `json:"user_id"`
	TeamID       *int64         `json:"team_id"`
	PasswordHash *string        `json:"password_hash"`
	Ip           []netip.Prefix `json:"ip"`
	StartingTime *time.Time     `json:"starting_time"`
	DelayTimeS   int64          `json:"delay_time_s"`
	ExtraTimeS   int64          `json:"extra_time_s"`
	Hidden       bool           `json:"hidden"`
	Unrestricted bool           `json:"unrestricted"`
	LoginNonce   int64          `json:"login_nonce"`
	Username     string         `json:"username"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	ContestName  string         `json:"contest_name"`
}

func (q *Queries) AdminGetParticipation(ctx context.Context, id int64) (AdminGetParticipationRow, error) {
	row := q.db.QueryRow(ctx, adminGetParticipation, id)
	var i AdminGetParticipationRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.TeamID,
		&i.PasswordHash,
		&i.Ip,
		&i.StartingTime,
		&i.DelayTimeS,
		&i.ExtraTimeS,
		&i.Hidden,
		&i.Unrestricted,
		&i.LoginNonce,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.ContestName,
	)
	return i, err
}

const adminGetSubmission = `-- name: AdminGetSubmission :one
SELECT s.id, s.participation_id, s.task_id, s.submitted_at, s.language, s.comment, s.official, u.id AS user_id, u.username, t.name AS task_name, t.title AS task_title,
       t.active_dataset_id, p.contest_id, (tk.submission_id IS NOT NULL)::boolean AS tokened
FROM submissions s
JOIN participations p ON p.id = s.participation_id
JOIN users u ON u.id = p.user_id
JOIN tasks t ON t.id = s.task_id
LEFT JOIN tokens tk ON tk.submission_id = s.id
WHERE s.id = $1
`

type AdminGetSubmissionRow struct {
	ID              int64     `json:"id"`
	ParticipationID int64     `json:"participation_id"`
	TaskID          int64     `json:"task_id"`
	SubmittedAt     time.Time `json:"submitted_at"`
	Language        *string   `json:"language"`
	Comment         string    `json:"comment"`
	Official        bool      `json:"official"`
	UserID          int64     `json:"user_id"`
	Username        string    `json:"username"`
	TaskName        string    `json:"task_name"`
	TaskTitle       string    `json:"task_title"`
	ActiveDatasetID *int64    `json:"active_dataset_id"`
	ContestID       int64     `json:"contest_id"`
	Tokened         bool      `json:"tokened"`
}

func (q *Queries) AdminGetSubmission(ctx context.Context, id int64) (AdminGetSubmissionRow, error) {
	row := q.db.QueryRow(ctx, adminGetSubmission, id)
	var i AdminGetSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.SubmittedAt,
		&i.Language,
		&i.Comment,
		&i.Official,
		&i.UserID,
		&i.Username,
		&i.TaskName,
		&i.TaskTitle,
		&i.ActiveDatasetID,
		&i.ContestID,
		&i.Tokened,
	)
	return i, err
}

const adminListSubmissionResults = `-- name: AdminListSubmissionResults :many
SELECT sr.submission_id, sr.dataset_id, sr.generation, sr.compilation_outcome, sr.compilation_text, sr.compilation_stdout, sr.compilation_stderr, sr.compilation_tries, sr.compilation_time, sr.compilation_wall_time, sr.compilation_memory, sr.compilation_worker, sr.evaluation_outcome, sr.evaluation_tries, sr.testcases_total, sr.testcases_done, sr.score, sr.score_details, sr.public_score, sr.public_score_details, sr.ranking_score_details, sr.scored_at, sr.system_error, sr.created_at, sr.jobs_enqueued_at, d.description AS dataset_description, (d.id = t.active_dataset_id)::boolean AS live
FROM submission_results sr
JOIN datasets d ON d.id = sr.dataset_id
JOIN tasks t ON t.id = d.task_id
WHERE sr.submission_id = $1
ORDER BY (d.id = t.active_dataset_id) DESC, d.id
`

type AdminListSubmissionResultsRow struct {
	SubmissionID        int64           `json:"submission_id"`
	DatasetID           int64           `json:"dataset_id"`
	Generation          int32           `json:"generation"`
	CompilationOutcome  *string         `json:"compilation_outcome"`
	CompilationText     string          `json:"compilation_text"`
	CompilationStdout   string          `json:"compilation_stdout"`
	CompilationStderr   string          `json:"compilation_stderr"`
	CompilationTries    int32           `json:"compilation_tries"`
	CompilationTime     *float64        `json:"compilation_time"`
	CompilationWallTime *float64        `json:"compilation_wall_time"`
	CompilationMemory   *int64          `json:"compilation_memory"`
	CompilationWorker   *string         `json:"compilation_worker"`
	EvaluationOutcome   *string         `json:"evaluation_outcome"`
	EvaluationTries     int32           `json:"evaluation_tries"`
	TestcasesTotal      int32           `json:"testcases_total"`
	TestcasesDone       int32           `json:"testcases_done"`
	Score               *float64        `json:"score"`
	ScoreDetails        json.RawMessage `json:"score_details"`
	PublicScore         *float64        `json:"public_score"`
	PublicScoreDetails  json.RawMessage `json:"public_score_details"`
	RankingScoreDetails json.RawMessage `json:"ranking_score_details"`
	ScoredAt            *time.Time      `json:"scored_at"`
	SystemError         *string         `json:"system_error"`
	CreatedAt           time.Time       `json:"created_at"`
	JobsEnqueuedAt      *time.Time      `json:"jobs_enqueued_at"`
	DatasetDescription  string          `json:"dataset_description"`
	Live                bool            `json:"live"`
}

// Results of a submission on every dataset it was judged on.
func (q *Queries) AdminListSubmissionResults(ctx context.Context, submissionID int64) ([]AdminListSubmissionResultsRow, error) {
	rows, err := q.db.Query(ctx, adminListSubmissionResults, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListSubmissionResultsRow{}
	for rows.Next() {
		var i AdminListSubmissionResultsRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.DatasetID,
			&i.Generation,
			&i.CompilationOutcome,
			&i.CompilationText,
			&i.CompilationStdout,
			&i.CompilationStderr,
			&i.CompilationTries,
			&i.CompilationTime,
			&i.CompilationWallTime,
			&i.CompilationMemory,
			&i.CompilationWorker,
			&i.EvaluationOutcome,
			&i.EvaluationTries,
			&i.TestcasesTotal,
			&i.TestcasesDone,
			&i.Score,
			&i.ScoreDetails,
			&i.PublicScore,
			&i.PublicScoreDetails,
			&i.RankingScoreDetails,
			&i.ScoredAt,
			&i.SystemError,
			&i.CreatedAt,
			&i.JobsEnqueuedAt,
			&i.DatasetDescription,
			&i.Live,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSubmissions = `-- name: AdminListSubmissions :many

SELECT s.id, s.submitted_at, s.language, s.official, s.participation_id, s.task_id,
       u.username, t.name AS task_name, t.score_precision,
       sr.compilation_outcome, sr.testcases_done, sr.testcases_total, sr.score, sr.scored_at,
       sr.system_error, (tk.submission_id IS NOT NULL)::boolean AS tokened
FROM submissions s
JOIN participations p ON p.id = s.participation_id
JOIN users u ON u.id = p.user_id
JOIN tasks t ON t.id = s.task_id
LEFT JOIN submission_results sr ON sr.submission_id = s.id AND sr.dataset_id = t.active_dataset_id
LEFT JOIN tokens tk ON tk.submission_id = s.id
WHERE p.contest_id = $1::bigint
  AND ($2::bigint IS NULL OR s.task_id = $2::bigint)
  AND ($3::bigint IS NULL OR s.participation_id = $3::bigint)
  AND ($4::text IS NULL OR u.username ILIKE '%' || $4::text || '%')
  AND ($5::text IS NULL OR s.language = $5::text)
  AND ($6::float8 IS NULL OR sr.score >= $6::float8)
  AND ($7::float8 IS NULL OR sr.score <= $7::float8)
  AND ($8::text IS NULL OR CASE $8::text
        WHEN 'pending' THEN sr.scored_at IS NULL AND sr.system_error IS NULL
        WHEN 'compile_failed' THEN sr.compilation_outcome = 'fail'
        WHEN 'scored' THEN sr.scored_at IS NOT NULL AND sr.compilation_outcome = 'ok'
        WHEN 'error' THEN sr.system_error IS NOT NULL
        ELSE true END)
  AND ($9::bigint IS NULL OR s.id < $9::bigint)
ORDER BY s.id DESC
LIMIT $10::int
`

type AdminListSubmissionsParams struct {
	ContestID       int64    `json:"contest_id"`
	TaskID          *int64   `json:"task_id"`
	ParticipationID *int64   `json:"participation_id"`
	Username        *string  `json:"username"`
	Language        *string  `json:"language"`
	MinScore        *float64 `json:"min_score"`
	MaxScore        *float64 `json:"max_score"`
	Status          *string  `json:"status"`
	BeforeID        *int64   `json:"before_id"`
	Lim             int32    `json:"lim"`
}

type AdminListSubmissionsRow struct {
	ID                 int64      `json:"id"`
	SubmittedAt        time.Time  `json:"submitted_at"`
	Language           *string    `json:"language"`
	Official           bool       `json:"official"`
	ParticipationID    int64      `json:"participation_id"`
	TaskID             int64      `json:"task_id"`
	Username           string     `json:"username"`
	TaskName           string     `json:"task_name"`
	ScorePrecision     int32      `json:"score_precision"`
	CompilationOutcome *string    `json:"compilation_outcome"`
	TestcasesDone      *int32     `json:"testcases_done"`
	TestcasesTotal     *int32     `json:"testcases_total"`
	Score              *float64   `json:"score"`
	ScoredAt           *time.Time `json:"scored_at"`
	SystemError        *string    `json:"system_error"`
	Tokened            bool       `json:"tokened"`
}

// Queries of the admin web server (AWS).
// Submissions of a contest, newest first, with their live-dataset result.
// Keyset pagination on the id (before_id); every filter is optional.
func (q *Queries) AdminListSubmissions(ctx context.Context, arg AdminListSubmissionsParams) ([]AdminListSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, adminListSubmissions,
		arg.ContestID,
		arg.TaskID,
		arg.ParticipationID,
		arg.Username,
		arg.Language,
		arg.MinScore,
		arg.MaxScore,
		arg.Status,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListSubmissionsRow{}
	for rows.Next() {
		var i AdminListSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedAt,
			&i.Language,
			&i.Official,
			&i.ParticipationID,
			&i.TaskID,
			&i.Username,
			&i.TaskName,
			&i.ScorePrecision,
			&i.CompilationOutcome,
			&i.TestcasesDone,
			&i.TestcasesTotal,
			&i.Score,
			&i.ScoredAt,
			&i.SystemError,
			&i.Tokened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSystemErrors = `-- name: AdminListSystemErrors :many
SELECT sr.submission_id, sr.dataset_id, sr.system_error, sr.created_at, s.task_id, t.name AS task_name,
       u.username, p.contest_id
FROM submission_results sr
JOIN submissions s ON s.id = sr.submission_id
JOIN tasks t ON t.id = s.task_id
JOIN participations p ON p.id = s.participation_id
JOIN users u ON u.id = p.user_id
WHERE sr.system_error IS NOT NULL
ORDER BY sr.submission_id DESC
LIMIT 50
`

type AdminListSystemErrorsRow struct {
	SubmissionID int64     `json:"submission_id"`
	DatasetID    int64     `json:"dataset_id"`
	SystemError  *string   `json:"system_error"`
	CreatedAt    time.Time `json:"created_at"`
	TaskID       int64     `json:"task_id"`
	TaskName     string    `json:"task_name"`
	Username     string    `json:"username"`
	ContestID    int64     `json:"contest_id"`
}

// Submissions that could not be judged (most recent first).
func (q *Queries) AdminListSystemErrors(ctx context.Context) ([]AdminListSystemErrorsRow, error) {
	rows, err := q.db.Query(ctx, adminListSystemErrors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListSystemErrorsRow{}
	for rows.Next() {
		var i AdminListSystemErrorsRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.DatasetID,
			&i.SystemError,
			&i.CreatedAt,
			&i.TaskID,
			&i.TaskName,
			&i.Username,
			&i.ContestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUserParticipations = `-- name: AdminListUserParticipations :many
SELECT p.id, p.contest_id, p.user_id, p.team_id, p.password_hash, p.ip, p.starting_time, p.delay_time_s, p.extra_time_s, p.hidden, p.unrestricted, p.login_nonce, c.name AS contest_name, t.code AS team_code
FROM participations p
JOIN contests c ON c.id = p.contest_id
LEFT JOIN teams t ON t.id = p.team_id
WHERE p.user_id = $1
ORDER BY c.start_time DESC
`

type AdminListUserParticipationsRow struct {
	ID           int64          `json:"id"`
	ContestID    int64          `json:"contest_id"`
	UserID       int64          `json:"user_id"`
	TeamID       *int64         `json:"team_id"`
	PasswordHash *string        `json:"password_hash"`
	Ip           []netip.Prefix `json:"ip"`
	StartingTime *time.Time     `json:"starting_time"`
	DelayTimeS   int64          `json:"delay_time_s"`
	ExtraTimeS   int64          `json:"extra_time_s"`
	Hidden       bool           `json:"hidden"`
	Unrestricted bool           `json:"unrestricted"`
	LoginNonce   int64          `json:"login_nonce"`
	ContestName  string         `json:"contest_name"`
	TeamCode     *string        `json:"team_code"`
}

func (q *Queries) AdminListUserParticipations(ctx context.Context, userID int64) ([]AdminListUserParticipationsRow, error) {
	rows, err := q.db.Query(ctx, adminListUserParticipations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUserParticipationsRow{}
	for rows.Next() {
		var i AdminListUserParticipationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.TeamID,
			&i.PasswordHash,
			&i.Ip,
			&i.StartingTime,
			&i.DelayTimeS,
			&i.ExtraTimeS,
			&i.Hidden,
			&i.Unrestricted,
			&i.LoginNonce,
			&i.ContestName,
			&i.TeamCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.password_hash, u.timezone, u.preferred_languages, u.created_at, (SELECT count(*) FROM participations p WHERE p.user_id = u.id) AS participations
FROM users u
WHERE ($1::text IS NULL
       OR u.username ILIKE '%' || $1::text || '%'
       OR u.first_name ILIKE '%' || $1::text || '%'
       OR u.last_name ILIKE '%' || $1::text || '%')
ORDER BY u.username
LIMIT $3::int OFFSET $2::int
`

type AdminListUsersParams struct {
	Search *string `json:"search"`
	Off    int32   `json:"off"`
	Lim    int32   `json:"lim"`
}

type AdminListUsersRow struct {
	ID                 int64     `json:"id"`
	Username           string    `json:"username"`
	FirstName          string    `json:"first_name"`
	LastName           string    `json:"last_name"`
	Email              string    `json:"email"`
	PasswordHash       string    `json:"password_hash"`
	Timezone           *string   `json:"timezone"`
	PreferredLanguages []string  `json:"preferred_languages"`
	CreatedAt          time.Time `json:"created_at"`
	Participations     int64     `json:"participations"`
}

// Users with the number of participations, filtered by a search string.
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.Timezone,
			&i.PreferredLanguages,
			&i.CreatedAt,
			&i.Participations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminNextTaskNum = `-- name: AdminNextTaskNum :one
SELECT COALESCE(max(num) + 1, 0)::int FROM tasks WHERE contest_id = $1
`

func (q *Queries) AdminNextTaskNum(ctx context.Context, contestID *int64) (int32, error) {
	row := q.db.QueryRow(ctx, adminNextTaskNum, contestID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminTaskSubmissionStats = `-- name: AdminTaskSubmissionStats :many
SELECT t.id AS task_id,
       count(s.id) AS submissions,
       count(DISTINCT s.participation_id) AS participants,
       count(s.id) FILTER (WHERE sr.compilation_outcome = 'fail') AS compile_failed,
       count(s.id) FILTER (WHERE sr.scored_at IS NULL AND sr.system_error IS NULL) AS pending,
       count(s.id) FILTER (WHERE sr.system_error IS NOT NULL) AS errors
FROM tasks t
LEFT JOIN submissions s ON s.task_id = t.id AND s.official
LEFT JOIN submission_results sr ON sr.submission_id = s.id AND sr.dataset_id = t.active_dataset_id
WHERE t.contest_id = $1
GROUP BY t.id
`

type AdminTaskSubmissionStatsRow struct {
	TaskID        int64 `json:"task_id"`
	Submissions   int64 `json:"submissions"`
	Participants  int64 `json:"participants"`
	CompileFailed int64 `json:"compile_failed"`
	Pending       int64 `json:"pending"`
	Errors        int64 `json:"errors"`
}

// Per-task submission counters on the live dataset.
func (q *Queries) AdminTaskSubmissionStats(ctx context.Context, contestID *int64) ([]AdminTaskSubmissionStatsRow, error) {
	rows, err := q.db.Query(ctx, adminTaskSubmissionStats, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminTaskSubmissionStatsRow{}
	for rows.Next() {
		var i AdminTaskSubmissionStatsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Submissions,
			&i.Participants,
			&i.CompileFailed,
			&i.Pending,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminTaskVerdictStats = `-- name: AdminTaskVerdictStats :many
SELECT s.task_id,
       (CASE WHEN e.exit_status <> 'ok' THEN e.exit_status
             WHEN e.outcome >= 1 THEN 'correct'
             WHEN e.outcome <= 0 THEN 'wrong'
             ELSE 'partial' END)::text AS verdict,
       count(*) AS n,
       COALESCE(avg(e.execution_time), 0)::float8 AS avg_time,
       COALESCE(max(e.execution_time), 0)::float8 AS max_time,
       COALESCE(max(e.execution_memory), 0)::bigint AS max_memory
FROM evaluations e
JOIN submissions s ON s.id = e.submission_id
JOIN tasks t ON t.id = s.task_id AND t.active_dataset_id = e.dataset_id
WHERE t.contest_id = $1 AND s.official
GROUP BY s.task_id, verdict
ORDER BY s.task_id, verdict
`

type AdminTaskVerdictStatsRow struct {
	TaskID    int64   `json:"task_id"`
	Verdict   string  `json:"verdict"`
	N         int64   `json:"n"`
	AvgTime   float64 `json:"avg_time"`
	MaxTime   float64 `json:"max_time"`
	MaxMemory int64   `json:"max_memory"`
}

// Testcase verdict distribution on the live dataset of each task.
func (q *Queries) AdminTaskVerdictStats(ctx context.Context, contestID *int64) ([]AdminTaskVerdictStatsRow, error) {
	rows, err := q.db.Query(ctx, adminTaskVerdictStats, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminTaskVerdictStatsRow{}
	for rows.Next() {
		var i AdminTaskVerdictStatsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Verdict,
			&i.N,
			&i.AvgTime,
			&i.MaxTime,
			&i.MaxMemory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUnassignedTasks = `-- name: AdminUnassignedTasks :many
SELECT id, contest_id, num, name, title, primary_statements, submission_format, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, feedback_level, score_precision, score_mode, active_dataset_id, created_at, updated_at FROM tasks WHERE contest_id IS NULL ORDER BY name
`

func (q *Queries) AdminUnassignedTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, adminUnassignedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.Num,
			&i.Name,
			&i.Title,
			&i.PrimaryStatements,
			&i.SubmissionFormat,
			&i.TokenMode,
			&i.TokenMaxNumber,
			&i.TokenMinIntervalS,
			&i.TokenGenInitial,
			&i.TokenGenNumber,
			&i.TokenGenIntervalS,
			&i.TokenGenMax,
			&i.MaxSubmissionNumber,
			&i.MaxUserTestNumber,
			&i.MinSubmissionIntervalS,
			&i.MinUserTestIntervalS,
			&i.FeedbackLevel,
			&i.ScorePrecision,
			&i.ScoreMode,
			&i.ActiveDatasetID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
