// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balloons.sql

package sqlc

import (
	"context"
	"time"
)

const deliverBalloon = `-- name: DeliverBalloon :exec
INSERT INTO balloons (task_id, recipient, delivered_by) VALUES ($1, $2, $3)
ON CONFLICT (task_id, recipient) DO NOTHING
`

type DeliverBalloonParams struct {
	TaskID      int64  `json:"task_id"`
	Recipient   string `json:"recipient"`
	DeliveredBy *int64 `json:"delivered_by"`
}

func (q *Queries) DeliverBalloon(ctx context.Context, arg DeliverBalloonParams) error {
	_, err := q.db.Exec(ctx, deliverBalloon, arg.TaskID, arg.Recipient, arg.DeliveredBy)
	return err
}

const listBalloonDeliveries = `-- name: ListBalloonDeliveries :many
SELECT b.task_id, b.recipient, b.delivered_at, COALESCE(a.username, '')::text AS delivered_by
FROM balloons b
JOIN tasks t ON t.id = b.task_id
LEFT JOIN admins a ON a.id = b.delivered_by
WHERE t.contest_id = $1::bigint
`

type ListBalloonDeliveriesRow struct {
	TaskID      int64     `json:"task_id"`
	Recipient   string    `json:"recipient"`
	DeliveredAt time.Time `json:"delivered_at"`
	DeliveredBy string    `json:"delivered_by"`
}

func (q *Queries) ListBalloonDeliveries(ctx context.Context, contestID int64) ([]ListBalloonDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listBalloonDeliveries, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalloonDeliveriesRow{}
	for rows.Next() {
		var i ListBalloonDeliveriesRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Recipient,
			&i.DeliveredAt,
			&i.DeliveredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestSolves = `-- name: ListContestSolves :many
SELECT p.id AS participation_id, s.task_id, s.icpc_solved_at, u.username, u.first_name, u.last_name,
       tm.code AS team_code, tm.name AS team_name, st.name AS site_name
FROM participations p
JOIN participation_task_scores s ON s.participation_id = p.id
JOIN users u ON u.id = p.user_id
LEFT JOIN teams tm ON tm.id = p.team_id
LEFT JOIN sites st ON st.id = p.site_id
WHERE p.contest_id = $1 AND s.icpc_solved AND s.icpc_solved_at IS NOT NULL AND NOT p.hidden AND p.approved
ORDER BY s.icpc_solved_at, p.id
`

type ListContestSolvesRow struct {
	ParticipationID int64      `json:"participation_id"`
	TaskID          int64      `json:"task_id"`
	IcpcSolvedAt    *time.Time `json:"icpc_solved_at"`
	Username        string     `json:"username"`
	FirstName       string     `json:"first_name"`
	LastName        string     `json:"last_name"`
	TeamCode        *string    `json:"team_code"`
	TeamName        *string    `json:"team_name"`
	SiteName        *string    `json:"site_name"`
}

// Every solved (participation, task) of a contest, first solves first, for
// the balloons page (index: participations (contest_id, user_id) unique,
// then the participation_task_scores primary key).
func (q *Queries) ListContestSolves(ctx context.Context, contestID int64) ([]ListContestSolvesRow, error) {
	rows, err := q.db.Query(ctx, listContestSolves, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestSolvesRow{}
	for rows.Next() {
		var i ListContestSolvesRow
		if err := rows.Scan(
			&i.ParticipationID,
			&i.TaskID,
			&i.IcpcSolvedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.TeamCode,
			&i.TeamName,
			&i.SiteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const undeliverBalloon = `-- name: UndeliverBalloon :exec
DELETE FROM balloons WHERE task_id = $1 AND recipient = $2
`

type UndeliverBalloonParams struct {
	TaskID    int64  `json:"task_id"`
	Recipient string `json:"recipient"`
}

func (q *Queries) UndeliverBalloon(ctx context.Context, arg UndeliverBalloonParams) error {
	_, err := q.db.Exec(ctx, undeliverBalloon, arg.TaskID, arg.Recipient)
	return err
}
