// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blobs.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const deleteBlobRecord = `-- name: DeleteBlobRecord :exec
DELETE FROM blobs WHERE digest = $1
`

func (q *Queries) DeleteBlobRecord(ctx context.Context, digest string) error {
	_, err := q.db.Exec(ctx, deleteBlobRecord, digest)
	return err
}

const getBlob = `-- name: GetBlob :one
SELECT digest, size, description, created_at FROM blobs WHERE digest = $1
`

func (q *Queries) GetBlob(ctx context.Context, digest string) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlob, digest)
	var i Blob
	err := row.Scan(
		&i.Digest,
		&i.Size,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listLanguages = `-- name: ListLanguages :many
SELECT id, name, config, updated_at FROM languages ORDER BY id
`

func (q *Queries) ListLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Language{}
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Config,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreferencedBlobs = `-- name: ListUnreferencedBlobs :many
SELECT b.digest, b.size FROM blobs b
WHERE b.created_at < $2::timestamptz
  AND NOT EXISTS (SELECT 1 FROM statements x WHERE x.digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM attachments x WHERE x.digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM managers x WHERE x.digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM testcases x WHERE x.input_digest = b.digest OR x.output_digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM submission_files x WHERE x.digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM executables x WHERE x.digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM user_tests x WHERE x.input_digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM user_test_files x WHERE x.digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM user_test_executables x WHERE x.digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM user_test_results x WHERE x.output_digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM print_jobs x WHERE x.digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM teams x WHERE x.flag_digest = b.digest OR x.photo_digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM users x WHERE x.photo_digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM certificate_templates x WHERE x.logo_digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM task_examples x WHERE x.input_digest = b.digest OR x.output_digest = b.digest)
  AND NOT EXISTS (SELECT 1 FROM contests x WHERE x.banner_digest = b.digest)
LIMIT $1
`

type ListUnreferencedBlobsParams struct {
	Limit     int32     `json:"limit"`
	OlderThan time.Time `json:"older_than"`
}

type ListUnreferencedBlobsRow struct {
	Digest string `json:"digest"`
	Size   int64  `json:"size"`
}

// Garbage-collection candidates: registered blobs no table references,
// older than the grace period (uploads in flight are not yet referenced).
func (q *Queries) ListUnreferencedBlobs(ctx context.Context, arg ListUnreferencedBlobsParams) ([]ListUnreferencedBlobsRow, error) {
	rows, err := q.db.Query(ctx, listUnreferencedBlobs, arg.Limit, arg.OlderThan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreferencedBlobsRow{}
	for rows.Next() {
		var i ListUnreferencedBlobsRow
		if err := rows.Scan(&i.Digest, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerBlob = `-- name: RegisterBlob :exec
INSERT INTO blobs (digest, size, description) VALUES ($1, $2, $3) ON CONFLICT (digest) DO NOTHING
`

type RegisterBlobParams struct {
	Digest      string `json:"digest"`
	Size        int64  `json:"size"`
	Description string `json:"description"`
}

func (q *Queries) RegisterBlob(ctx context.Context, arg RegisterBlobParams) error {
	_, err := q.db.Exec(ctx, registerBlob, arg.Digest, arg.Size, arg.Description)
	return err
}

const upsertLanguage = `-- name: UpsertLanguage :exec
INSERT INTO languages (id, name, config) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, config = EXCLUDED.config, updated_at = now()
`

type UpsertLanguageParams struct {
	ID     string          `json:"id"`
	Name   string          `json:"name"`
	Config json.RawMessage `json:"config"`
}

func (q *Queries) UpsertLanguage(ctx context.Context, arg UpsertLanguageParams) error {
	_, err := q.db.Exec(ctx, upsertLanguage, arg.ID, arg.Name, arg.Config)
	return err
}
