// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificates.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getCertificateTemplate = `-- name: GetCertificateTemplate :one
SELECT contest_id, title, body, footer, date_text, signatures, awards, min_score, only_awarded, logo_digest, contestants_can_download, updated_at FROM certificate_templates WHERE contest_id = $1
`

func (q *Queries) GetCertificateTemplate(ctx context.Context, contestID int64) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, getCertificateTemplate, contestID)
	var i CertificateTemplate
	err := row.Scan(
		&i.ContestID,
		&i.Title,
		&i.Body,
		&i.Footer,
		&i.DateText,
		&i.Signatures,
		&i.Awards,
		&i.MinScore,
		&i.OnlyAwarded,
		&i.LogoDigest,
		&i.ContestantsCanDownload,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCertificateTemplate = `-- name: UpsertCertificateTemplate :exec
INSERT INTO certificate_templates (contest_id, title, body, footer, date_text, signatures, awards, min_score,
    only_awarded, logo_digest, contestants_can_download, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, now())
ON CONFLICT (contest_id) DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body, footer = EXCLUDED.footer,
    date_text = EXCLUDED.date_text, signatures = EXCLUDED.signatures, awards = EXCLUDED.awards,
    min_score = EXCLUDED.min_score, only_awarded = EXCLUDED.only_awarded, logo_digest = EXCLUDED.logo_digest,
    contestants_can_download = EXCLUDED.contestants_can_download, updated_at = now()
`

type UpsertCertificateTemplateParams struct {
	ContestID              int64           `json:"contest_id"`
	Title                  string          `json:"title"`
	Body                   string          `json:"body"`
	Footer                 string          `json:"footer"`
	DateText               string          `json:"date_text"`
	Signatures             json.RawMessage `json:"signatures"`
	Awards                 json.RawMessage `json:"awards"`
	MinScore               *float64        `json:"min_score"`
	OnlyAwarded            bool            `json:"only_awarded"`
	LogoDigest             *string         `json:"logo_digest"`
	ContestantsCanDownload bool            `json:"contestants_can_download"`
}

func (q *Queries) UpsertCertificateTemplate(ctx context.Context, arg UpsertCertificateTemplateParams) error {
	_, err := q.db.Exec(ctx, upsertCertificateTemplate,
		arg.ContestID,
		arg.Title,
		arg.Body,
		arg.Footer,
		arg.DateText,
		arg.Signatures,
		arg.Awards,
		arg.MinScore,
		arg.OnlyAwarded,
		arg.LogoDigest,
		arg.ContestantsCanDownload,
	)
	return err
}
