// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: communication.sql

package sqlc

import (
	"context"
	"time"
)

const adminListQuestions = `-- name: AdminListQuestions :many
SELECT q.id, q.participation_id, q.asked_at, q.subject, q.text, q.reply_at, q.reply_subject, q.reply_text, q.reply_admin_id, q.ignored, q.contest_id, q.task_id, q.public, u.username, c.name AS contest_name, t.name AS task_name,
       (q.reply_at IS NULL AND NOT q.ignored)::boolean AS pending
FROM questions q
JOIN participations p ON p.id = q.participation_id
JOIN users u ON u.id = p.user_id
JOIN contests c ON c.id = q.contest_id
LEFT JOIN tasks t ON t.id = q.task_id
WHERE ($1::bigint IS NULL OR q.contest_id = $1)
  AND ($2::bigint IS NULL OR q.task_id = $2)
  AND ($3::bigint IS NULL OR q.id = $3)
  AND ($4::boolean OR (q.reply_at IS NULL AND NOT q.ignored))
ORDER BY (q.reply_at IS NULL AND NOT q.ignored) DESC,
         CASE WHEN q.reply_at IS NULL AND NOT q.ignored THEN q.asked_at END ASC,
         COALESCE(q.reply_at, q.asked_at) DESC
LIMIT 300
`

type AdminListQuestionsParams struct {
	ContestID    *int64 `json:"contest_id"`
	TaskID       *int64 `json:"task_id"`
	QuestionID   *int64 `json:"question_id"`
	WithAnswered bool   `json:"with_answered"`
}

type AdminListQuestionsRow struct {
	ID              int64      `json:"id"`
	ParticipationID int64      `json:"participation_id"`
	AskedAt         time.Time  `json:"asked_at"`
	Subject         string     `json:"subject"`
	Text            string     `json:"text"`
	ReplyAt         *time.Time `json:"reply_at"`
	ReplySubject    *string    `json:"reply_subject"`
	ReplyText       *string    `json:"reply_text"`
	ReplyAdminID    *int64     `json:"reply_admin_id"`
	Ignored         bool       `json:"ignored"`
	ContestID       int64      `json:"contest_id"`
	TaskID          *int64     `json:"task_id"`
	Public          bool       `json:"public"`
	Username        string     `json:"username"`
	ContestName     string     `json:"contest_name"`
	TaskName        *string    `json:"task_name"`
	Pending         bool       `json:"pending"`
}

// Staff inbox: pending questions oldest first (questions_pending_idx), then
// the most recently answered or ignored ones; optionally one contest/task.
func (q *Queries) AdminListQuestions(ctx context.Context, arg AdminListQuestionsParams) ([]AdminListQuestionsRow, error) {
	rows, err := q.db.Query(ctx, adminListQuestions,
		arg.ContestID,
		arg.TaskID,
		arg.QuestionID,
		arg.WithAnswered,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListQuestionsRow{}
	for rows.Next() {
		var i AdminListQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.AskedAt,
			&i.Subject,
			&i.Text,
			&i.ReplyAt,
			&i.ReplySubject,
			&i.ReplyText,
			&i.ReplyAdminID,
			&i.Ignored,
			&i.ContestID,
			&i.TaskID,
			&i.Public,
			&i.Username,
			&i.ContestName,
			&i.TaskName,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimPrintJob = `-- name: ClaimPrintJob :one
UPDATE print_jobs SET status = 'printing'
WHERE id = (SELECT id FROM print_jobs WHERE status = 'queued' ORDER BY id LIMIT 1 FOR UPDATE SKIP LOCKED)
RETURNING id, participation_id, created_at, filename, digest, status, status_text, pages
`

// Printing service: atomically take the oldest queued job.
func (q *Queries) ClaimPrintJob(ctx context.Context) (PrintJob, error) {
	row := q.db.QueryRow(ctx, claimPrintJob)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.CreatedAt,
		&i.Filename,
		&i.Digest,
		&i.Status,
		&i.StatusText,
		&i.Pages,
	)
	return i, err
}

const countPendingQuestions = `-- name: CountPendingQuestions :one
SELECT count(*) FROM questions WHERE reply_at IS NULL AND NOT ignored
`

// Admin menu counter (questions_pending_idx).
func (q *Queries) CountPendingQuestions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingQuestions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrintJobsByParticipation = `-- name: CountPrintJobsByParticipation :one
SELECT count(*) FROM print_jobs WHERE participation_id = $1
`

func (q *Queries) CountPrintJobsByParticipation(ctx context.Context, participationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPrintJobsByParticipation, participationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadCommunication = `-- name: CountUnreadCommunication :one
WITH seen AS (SELECT communication_seen_at AS since FROM participations WHERE id = $2)
SELECT ((SELECT count(*) FROM announcements a, seen WHERE a.contest_id = $1 AND a.created_at > seen.since)
      + (SELECT count(*) FROM messages m, seen WHERE m.participation_id = $2 AND m.created_at > seen.since)
      + (SELECT count(*) FROM questions q, seen WHERE q.participation_id = $2 AND q.reply_at > seen.since)
      + (SELECT count(*) FROM questions q, seen WHERE q.contest_id = $1 AND q.public AND q.reply_at > seen.since
             AND q.participation_id <> $2))::bigint AS unread
`

type CountUnreadCommunicationParams struct {
	ContestID       int64 `json:"contest_id"`
	ParticipationID int64 `json:"participation_id"`
}

// Announcements, messages and answers (own, or public ones of others)
// newer than the participant's last visit to the communication page (read
// here, not from the participation cache, so a visit resets it at once).
func (q *Queries) CountUnreadCommunication(ctx context.Context, arg CountUnreadCommunicationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadCommunication, arg.ContestID, arg.ParticipationID)
	var unread int64
	err := row.Scan(&unread)
	return unread, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (contest_id, subject, text, admin_id) VALUES ($1, $2, $3, $4) RETURNING id, contest_id, created_at, subject, text, admin_id
`

type CreateAnnouncementParams struct {
	ContestID int64  `json:"contest_id"`
	Subject   string `json:"subject"`
	Text      string `json:"text"`
	AdminID   *int64 `json:"admin_id"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.ContestID,
		arg.Subject,
		arg.Text,
		arg.AdminID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.CreatedAt,
		&i.Subject,
		&i.Text,
		&i.AdminID,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (participation_id, subject, text, admin_id) VALUES ($1, $2, $3, $4) RETURNING id, participation_id, created_at, subject, text, admin_id
`

type CreateMessageParams struct {
	ParticipationID int64  `json:"participation_id"`
	Subject         string `json:"subject"`
	Text            string `json:"text"`
	AdminID         *int64 `json:"admin_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ParticipationID,
		arg.Subject,
		arg.Text,
		arg.AdminID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.CreatedAt,
		&i.Subject,
		&i.Text,
		&i.AdminID,
	)
	return i, err
}

const createPrintJob = `-- name: CreatePrintJob :one
INSERT INTO print_jobs (participation_id, created_at, filename, digest) VALUES ($1, $2, $3, $4) RETURNING id, participation_id, created_at, filename, digest, status, status_text, pages
`

type CreatePrintJobParams struct {
	ParticipationID int64     `json:"participation_id"`
	CreatedAt       time.Time `json:"created_at"`
	Filename        string    `json:"filename"`
	Digest          string    `json:"digest"`
}

func (q *Queries) CreatePrintJob(ctx context.Context, arg CreatePrintJobParams) (PrintJob, error) {
	row := q.db.QueryRow(ctx, createPrintJob,
		arg.ParticipationID,
		arg.CreatedAt,
		arg.Filename,
		arg.Digest,
	)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.CreatedAt,
		&i.Filename,
		&i.Digest,
		&i.Status,
		&i.StatusText,
		&i.Pages,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (participation_id, contest_id, task_id, asked_at, subject, text)
VALUES ($1, (SELECT contest_id FROM participations WHERE id = $1), $2, $3, $4, $5)
RETURNING id, participation_id, asked_at, subject, text, reply_at, reply_subject, reply_text, reply_admin_id, ignored, contest_id, task_id, public
`

type CreateQuestionParams struct {
	ParticipationID int64     `json:"participation_id"`
	TaskID          *int64    `json:"task_id"`
	AskedAt         time.Time `json:"asked_at"`
	Subject         string    `json:"subject"`
	Text            string    `json:"text"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ParticipationID,
		arg.TaskID,
		arg.AskedAt,
		arg.Subject,
		arg.Text,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AskedAt,
		&i.Subject,
		&i.Text,
		&i.ReplyAt,
		&i.ReplySubject,
		&i.ReplyText,
		&i.ReplyAdminID,
		&i.Ignored,
		&i.ContestID,
		&i.TaskID,
		&i.Public,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, id)
	return err
}

const finishPrintJob = `-- name: FinishPrintJob :exec
UPDATE print_jobs SET status = $2, status_text = $3, pages = $4 WHERE id = $1
`

type FinishPrintJobParams struct {
	ID         int64  `json:"id"`
	Status     string `json:"status"`
	StatusText string `json:"status_text"`
	Pages      *int32 `json:"pages"`
}

func (q *Queries) FinishPrintJob(ctx context.Context, arg FinishPrintJobParams) error {
	_, err := q.db.Exec(ctx, finishPrintJob,
		arg.ID,
		arg.Status,
		arg.StatusText,
		arg.Pages,
	)
	return err
}

const getAnnouncement = `-- name: GetAnnouncement :one
SELECT id, contest_id, created_at, subject, text, admin_id FROM announcements WHERE id = $1
`

func (q *Queries) GetAnnouncement(ctx context.Context, id int64) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncement, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.CreatedAt,
		&i.Subject,
		&i.Text,
		&i.AdminID,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, participation_id, asked_at, subject, text, reply_at, reply_subject, reply_text, reply_admin_id, ignored, contest_id, task_id, public FROM questions WHERE id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AskedAt,
		&i.Subject,
		&i.Text,
		&i.ReplyAt,
		&i.ReplySubject,
		&i.ReplyText,
		&i.ReplyAdminID,
		&i.Ignored,
		&i.ContestID,
		&i.TaskID,
		&i.Public,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, contest_id, created_at, subject, text, admin_id FROM announcements WHERE contest_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAnnouncements(ctx context.Context, contestID int64) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.CreatedAt,
			&i.Subject,
			&i.Text,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByContest = `-- name: ListMessagesByContest :many
SELECT m.id, m.participation_id, m.created_at, m.subject, m.text, m.admin_id, u.username, a.username AS admin_username
FROM messages m
JOIN participations p ON p.id = m.participation_id
JOIN users u ON u.id = p.user_id
LEFT JOIN admins a ON a.id = m.admin_id
WHERE p.contest_id = $1
ORDER BY m.created_at DESC, m.id DESC
LIMIT 200
`

type ListMessagesByContestRow struct {
	ID              int64     `json:"id"`
	ParticipationID int64     `json:"participation_id"`
	CreatedAt       time.Time `json:"created_at"`
	Subject         string    `json:"subject"`
	Text            string    `json:"text"`
	AdminID         *int64    `json:"admin_id"`
	Username        string    `json:"username"`
	AdminUsername   *string   `json:"admin_username"`
}

// Messages sent in a contest, newest first (for the staff).
func (q *Queries) ListMessagesByContest(ctx context.Context, contestID int64) ([]ListMessagesByContestRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByContestRow{}
	for rows.Next() {
		var i ListMessagesByContestRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.CreatedAt,
			&i.Subject,
			&i.Text,
			&i.AdminID,
			&i.Username,
			&i.AdminUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByParticipation = `-- name: ListMessagesByParticipation :many
SELECT id, participation_id, created_at, subject, text, admin_id FROM messages WHERE participation_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListMessagesByParticipation(ctx context.Context, participationID int64) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.CreatedAt,
			&i.Subject,
			&i.Text,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrintJobsByContest = `-- name: ListPrintJobsByContest :many
SELECT j.id, j.participation_id, j.created_at, j.filename, j.digest, j.status, j.status_text, j.pages, u.username FROM print_jobs j
JOIN participations p ON p.id = j.participation_id
JOIN users u ON u.id = p.user_id
WHERE p.contest_id = $1 ORDER BY j.created_at DESC
`

type ListPrintJobsByContestRow struct {
	ID              int64     `json:"id"`
	ParticipationID int64     `json:"participation_id"`
	CreatedAt       time.Time `json:"created_at"`
	Filename        string    `json:"filename"`
	Digest          string    `json:"digest"`
	Status          string    `json:"status"`
	StatusText      string    `json:"status_text"`
	Pages           *int32    `json:"pages"`
	Username        string    `json:"username"`
}

func (q *Queries) ListPrintJobsByContest(ctx context.Context, contestID int64) ([]ListPrintJobsByContestRow, error) {
	rows, err := q.db.Query(ctx, listPrintJobsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrintJobsByContestRow{}
	for rows.Next() {
		var i ListPrintJobsByContestRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.CreatedAt,
			&i.Filename,
			&i.Digest,
			&i.Status,
			&i.StatusText,
			&i.Pages,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrintJobsByParticipation = `-- name: ListPrintJobsByParticipation :many
SELECT id, participation_id, created_at, filename, digest, status, status_text, pages FROM print_jobs WHERE participation_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPrintJobsByParticipation(ctx context.Context, participationID int64) ([]PrintJob, error) {
	rows, err := q.db.Query(ctx, listPrintJobsByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrintJob{}
	for rows.Next() {
		var i PrintJob
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.CreatedAt,
			&i.Filename,
			&i.Digest,
			&i.Status,
			&i.StatusText,
			&i.Pages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicAnswers = `-- name: ListPublicAnswers :many
SELECT id, participation_id, asked_at, subject, text, reply_at, reply_subject, reply_text, reply_admin_id, ignored, contest_id, task_id, public FROM questions WHERE contest_id = $1 AND public AND reply_at IS NOT NULL
ORDER BY reply_at DESC LIMIT 200
`

// Public answers of a contest, newest first (questions_public_idx).
func (q *Queries) ListPublicAnswers(ctx context.Context, contestID int64) ([]Question, error) {
	rows, err := q.db.Query(ctx, listPublicAnswers, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.AskedAt,
			&i.Subject,
			&i.Text,
			&i.ReplyAt,
			&i.ReplySubject,
			&i.ReplyText,
			&i.ReplyAdminID,
			&i.Ignored,
			&i.ContestID,
			&i.TaskID,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByContest = `-- name: ListQuestionsByContest :many
SELECT q.id, q.participation_id, q.asked_at, q.subject, q.text, q.reply_at, q.reply_subject, q.reply_text, q.reply_admin_id, q.ignored, q.contest_id, q.task_id, q.public, u.username
FROM questions q
JOIN participations p ON p.id = q.participation_id
JOIN users u ON u.id = p.user_id
WHERE q.contest_id = $1
ORDER BY (q.reply_at IS NULL AND NOT q.ignored) DESC, q.asked_at DESC
`

type ListQuestionsByContestRow struct {
	ID              int64      `json:"id"`
	ParticipationID int64      `json:"participation_id"`
	AskedAt         time.Time  `json:"asked_at"`
	Subject         string     `json:"subject"`
	Text            string     `json:"text"`
	ReplyAt         *time.Time `json:"reply_at"`
	ReplySubject    *string    `json:"reply_subject"`
	ReplyText       *string    `json:"reply_text"`
	ReplyAdminID    *int64     `json:"reply_admin_id"`
	Ignored         bool       `json:"ignored"`
	ContestID       int64      `json:"contest_id"`
	TaskID          *int64     `json:"task_id"`
	Public          bool       `json:"public"`
	Username        string     `json:"username"`
}

func (q *Queries) ListQuestionsByContest(ctx context.Context, contestID int64) ([]ListQuestionsByContestRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsByContestRow{}
	for rows.Next() {
		var i ListQuestionsByContestRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.AskedAt,
			&i.Subject,
			&i.Text,
			&i.ReplyAt,
			&i.ReplySubject,
			&i.ReplyText,
			&i.ReplyAdminID,
			&i.Ignored,
			&i.ContestID,
			&i.TaskID,
			&i.Public,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByParticipation = `-- name: ListQuestionsByParticipation :many
SELECT id, participation_id, asked_at, subject, text, reply_at, reply_subject, reply_text, reply_admin_id, ignored, contest_id, task_id, public FROM questions WHERE participation_id = $1 ORDER BY asked_at DESC, id DESC
`

func (q *Queries) ListQuestionsByParticipation(ctx context.Context, participationID int64) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.AskedAt,
			&i.Subject,
			&i.Text,
			&i.ReplyAt,
			&i.ReplySubject,
			&i.ReplyText,
			&i.ReplyAdminID,
			&i.Ignored,
			&i.ContestID,
			&i.TaskID,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamParticipations = `-- name: ListTeamParticipations :many
SELECT p.id FROM participations p WHERE p.contest_id = $1 AND p.team_id = $2
`

type ListTeamParticipationsParams struct {
	ContestID int64  `json:"contest_id"`
	TeamID    *int64 `json:"team_id"`
}

// Participations of a team in a contest (messages to a team; a rare staff
// action scanning the contest's participations).
func (q *Queries) ListTeamParticipations(ctx context.Context, arg ListTeamParticipationsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listTeamParticipations, arg.ContestID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replyQuestion = `-- name: ReplyQuestion :one
UPDATE questions SET reply_at = now(), reply_subject = $2, reply_text = $3, reply_admin_id = $4, ignored = false,
    public = $5
WHERE id = $1 RETURNING id, participation_id, asked_at, subject, text, reply_at, reply_subject, reply_text, reply_admin_id, ignored, contest_id, task_id, public
`

type ReplyQuestionParams struct {
	ID           int64   `json:"id"`
	ReplySubject *string `json:"reply_subject"`
	ReplyText    *string `json:"reply_text"`
	ReplyAdminID *int64  `json:"reply_admin_id"`
	Public       bool    `json:"public"`
}

func (q *Queries) ReplyQuestion(ctx context.Context, arg ReplyQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, replyQuestion,
		arg.ID,
		arg.ReplySubject,
		arg.ReplyText,
		arg.ReplyAdminID,
		arg.Public,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AskedAt,
		&i.Subject,
		&i.Text,
		&i.ReplyAt,
		&i.ReplySubject,
		&i.ReplyText,
		&i.ReplyAdminID,
		&i.Ignored,
		&i.ContestID,
		&i.TaskID,
		&i.Public,
	)
	return i, err
}

const setCommunicationSeen = `-- name: SetCommunicationSeen :exec
UPDATE participations SET communication_seen_at = now() WHERE id = $1
`

func (q *Queries) SetCommunicationSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setCommunicationSeen, id)
	return err
}

const setQuestionIgnored = `-- name: SetQuestionIgnored :exec
UPDATE questions SET ignored = $2 WHERE id = $1
`

type SetQuestionIgnoredParams struct {
	ID      int64 `json:"id"`
	Ignored bool  `json:"ignored"`
}

func (q *Queries) SetQuestionIgnored(ctx context.Context, arg SetQuestionIgnoredParams) error {
	_, err := q.db.Exec(ctx, setQuestionIgnored, arg.ID, arg.Ignored)
	return err
}
