// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: communication.sql

package sqlc

import (
	"context"
	"time"
)

const claimPrintJob = `-- name: ClaimPrintJob :one
UPDATE print_jobs SET status = 'printing'
WHERE id = (SELECT id FROM print_jobs WHERE status = 'queued' ORDER BY id LIMIT 1 FOR UPDATE SKIP LOCKED)
RETURNING id, participation_id, created_at, filename, digest, status, status_text, pages
`

// Printing service: atomically take the oldest queued job.
func (q *Queries) ClaimPrintJob(ctx context.Context) (PrintJob, error) {
	row := q.db.QueryRow(ctx, claimPrintJob)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.CreatedAt,
		&i.Filename,
		&i.Digest,
		&i.Status,
		&i.StatusText,
		&i.Pages,
	)
	return i, err
}

const countPrintJobsByParticipation = `-- name: CountPrintJobsByParticipation :one
SELECT count(*) FROM print_jobs WHERE participation_id = $1
`

func (q *Queries) CountPrintJobsByParticipation(ctx context.Context, participationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPrintJobsByParticipation, participationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (contest_id, subject, text, admin_id) VALUES ($1, $2, $3, $4) RETURNING id, contest_id, created_at, subject, text, admin_id
`

type CreateAnnouncementParams struct {
	ContestID int64  `json:"contest_id"`
	Subject   string `json:"subject"`
	Text      string `json:"text"`
	AdminID   *int64 `json:"admin_id"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.ContestID,
		arg.Subject,
		arg.Text,
		arg.AdminID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.CreatedAt,
		&i.Subject,
		&i.Text,
		&i.AdminID,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (participation_id, subject, text, admin_id) VALUES ($1, $2, $3, $4) RETURNING id, participation_id, created_at, subject, text, admin_id
`

type CreateMessageParams struct {
	ParticipationID int64  `json:"participation_id"`
	Subject         string `json:"subject"`
	Text            string `json:"text"`
	AdminID         *int64 `json:"admin_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ParticipationID,
		arg.Subject,
		arg.Text,
		arg.AdminID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.CreatedAt,
		&i.Subject,
		&i.Text,
		&i.AdminID,
	)
	return i, err
}

const createPrintJob = `-- name: CreatePrintJob :one
INSERT INTO print_jobs (participation_id, created_at, filename, digest) VALUES ($1, $2, $3, $4) RETURNING id, participation_id, created_at, filename, digest, status, status_text, pages
`

type CreatePrintJobParams struct {
	ParticipationID int64     `json:"participation_id"`
	CreatedAt       time.Time `json:"created_at"`
	Filename        string    `json:"filename"`
	Digest          string    `json:"digest"`
}

func (q *Queries) CreatePrintJob(ctx context.Context, arg CreatePrintJobParams) (PrintJob, error) {
	row := q.db.QueryRow(ctx, createPrintJob,
		arg.ParticipationID,
		arg.CreatedAt,
		arg.Filename,
		arg.Digest,
	)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.CreatedAt,
		&i.Filename,
		&i.Digest,
		&i.Status,
		&i.StatusText,
		&i.Pages,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (participation_id, asked_at, subject, text) VALUES ($1, $2, $3, $4) RETURNING id, participation_id, asked_at, subject, text, reply_at, reply_subject, reply_text, reply_admin_id, ignored
`

type CreateQuestionParams struct {
	ParticipationID int64     `json:"participation_id"`
	AskedAt         time.Time `json:"asked_at"`
	Subject         string    `json:"subject"`
	Text            string    `json:"text"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ParticipationID,
		arg.AskedAt,
		arg.Subject,
		arg.Text,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AskedAt,
		&i.Subject,
		&i.Text,
		&i.ReplyAt,
		&i.ReplySubject,
		&i.ReplyText,
		&i.ReplyAdminID,
		&i.Ignored,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, id)
	return err
}

const finishPrintJob = `-- name: FinishPrintJob :exec
UPDATE print_jobs SET status = $2, status_text = $3, pages = $4 WHERE id = $1
`

type FinishPrintJobParams struct {
	ID         int64  `json:"id"`
	Status     string `json:"status"`
	StatusText string `json:"status_text"`
	Pages      *int32 `json:"pages"`
}

func (q *Queries) FinishPrintJob(ctx context.Context, arg FinishPrintJobParams) error {
	_, err := q.db.Exec(ctx, finishPrintJob,
		arg.ID,
		arg.Status,
		arg.StatusText,
		arg.Pages,
	)
	return err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, participation_id, asked_at, subject, text, reply_at, reply_subject, reply_text, reply_admin_id, ignored FROM questions WHERE id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AskedAt,
		&i.Subject,
		&i.Text,
		&i.ReplyAt,
		&i.ReplySubject,
		&i.ReplyText,
		&i.ReplyAdminID,
		&i.Ignored,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, contest_id, created_at, subject, text, admin_id FROM announcements WHERE contest_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAnnouncements(ctx context.Context, contestID int64) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.CreatedAt,
			&i.Subject,
			&i.Text,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByParticipation = `-- name: ListMessagesByParticipation :many
SELECT id, participation_id, created_at, subject, text, admin_id FROM messages WHERE participation_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListMessagesByParticipation(ctx context.Context, participationID int64) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.CreatedAt,
			&i.Subject,
			&i.Text,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrintJobsByContest = `-- name: ListPrintJobsByContest :many
SELECT j.id, j.participation_id, j.created_at, j.filename, j.digest, j.status, j.status_text, j.pages, u.username FROM print_jobs j
JOIN participations p ON p.id = j.participation_id
JOIN users u ON u.id = p.user_id
WHERE p.contest_id = $1 ORDER BY j.created_at DESC
`

type ListPrintJobsByContestRow struct {
	ID              int64     `json:"id"`
	ParticipationID int64     `json:"participation_id"`
	CreatedAt       time.Time `json:"created_at"`
	Filename        string    `json:"filename"`
	Digest          string    `json:"digest"`
	Status          string    `json:"status"`
	StatusText      string    `json:"status_text"`
	Pages           *int32    `json:"pages"`
	Username        string    `json:"username"`
}

func (q *Queries) ListPrintJobsByContest(ctx context.Context, contestID int64) ([]ListPrintJobsByContestRow, error) {
	rows, err := q.db.Query(ctx, listPrintJobsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrintJobsByContestRow{}
	for rows.Next() {
		var i ListPrintJobsByContestRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.CreatedAt,
			&i.Filename,
			&i.Digest,
			&i.Status,
			&i.StatusText,
			&i.Pages,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrintJobsByParticipation = `-- name: ListPrintJobsByParticipation :many
SELECT id, participation_id, created_at, filename, digest, status, status_text, pages FROM print_jobs WHERE participation_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPrintJobsByParticipation(ctx context.Context, participationID int64) ([]PrintJob, error) {
	rows, err := q.db.Query(ctx, listPrintJobsByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrintJob{}
	for rows.Next() {
		var i PrintJob
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.CreatedAt,
			&i.Filename,
			&i.Digest,
			&i.Status,
			&i.StatusText,
			&i.Pages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByContest = `-- name: ListQuestionsByContest :many
SELECT q.id, q.participation_id, q.asked_at, q.subject, q.text, q.reply_at, q.reply_subject, q.reply_text, q.reply_admin_id, q.ignored, u.username
FROM questions q
JOIN participations p ON p.id = q.participation_id
JOIN users u ON u.id = p.user_id
WHERE p.contest_id = $1
ORDER BY (q.reply_at IS NULL AND NOT q.ignored) DESC, q.asked_at DESC
`

type ListQuestionsByContestRow struct {
	ID              int64      `json:"id"`
	ParticipationID int64      `json:"participation_id"`
	AskedAt         time.Time  `json:"asked_at"`
	Subject         string     `json:"subject"`
	Text            string     `json:"text"`
	ReplyAt         *time.Time `json:"reply_at"`
	ReplySubject    *string    `json:"reply_subject"`
	ReplyText       *string    `json:"reply_text"`
	ReplyAdminID    *int64     `json:"reply_admin_id"`
	Ignored         bool       `json:"ignored"`
	Username        string     `json:"username"`
}

func (q *Queries) ListQuestionsByContest(ctx context.Context, contestID int64) ([]ListQuestionsByContestRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsByContestRow{}
	for rows.Next() {
		var i ListQuestionsByContestRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.AskedAt,
			&i.Subject,
			&i.Text,
			&i.ReplyAt,
			&i.ReplySubject,
			&i.ReplyText,
			&i.ReplyAdminID,
			&i.Ignored,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByParticipation = `-- name: ListQuestionsByParticipation :many
SELECT id, participation_id, asked_at, subject, text, reply_at, reply_subject, reply_text, reply_admin_id, ignored FROM questions WHERE participation_id = $1 ORDER BY asked_at DESC, id DESC
`

func (q *Queries) ListQuestionsByParticipation(ctx context.Context, participationID int64) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.AskedAt,
			&i.Subject,
			&i.Text,
			&i.ReplyAt,
			&i.ReplySubject,
			&i.ReplyText,
			&i.ReplyAdminID,
			&i.Ignored,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replyQuestion = `-- name: ReplyQuestion :one
UPDATE questions SET reply_at = now(), reply_subject = $2, reply_text = $3, reply_admin_id = $4, ignored = false
WHERE id = $1 RETURNING id, participation_id, asked_at, subject, text, reply_at, reply_subject, reply_text, reply_admin_id, ignored
`

type ReplyQuestionParams struct {
	ID           int64   `json:"id"`
	ReplySubject *string `json:"reply_subject"`
	ReplyText    *string `json:"reply_text"`
	ReplyAdminID *int64  `json:"reply_admin_id"`
}

func (q *Queries) ReplyQuestion(ctx context.Context, arg ReplyQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, replyQuestion,
		arg.ID,
		arg.ReplySubject,
		arg.ReplyText,
		arg.ReplyAdminID,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.AskedAt,
		&i.Subject,
		&i.Text,
		&i.ReplyAt,
		&i.ReplySubject,
		&i.ReplyText,
		&i.ReplyAdminID,
		&i.Ignored,
	)
	return i, err
}

const setQuestionIgnored = `-- name: SetQuestionIgnored :exec
UPDATE questions SET ignored = $2 WHERE id = $1
`

type SetQuestionIgnoredParams struct {
	ID      int64 `json:"id"`
	Ignored bool  `json:"ignored"`
}

func (q *Queries) SetQuestionIgnored(ctx context.Context, arg SetQuestionIgnoredParams) error {
	_, err := q.db.Exec(ctx, setQuestionIgnored, arg.ID, arg.Ignored)
	return err
}
