// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contests.sql

package sqlc

import (
	"context"
	"time"
)

const createContest = `-- name: CreateContest :one
INSERT INTO contests (
    name, description, allowed_localizations, languages, submissions_download_allowed,
    allow_questions, allow_user_tests, allow_printing, block_hidden_participations,
    allow_password_authentication, ip_restriction, ip_autologin, single_login,
    token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number,
    token_gen_interval_s, token_gen_max, start_time, stop_time, analysis_enabled,
    analysis_start, analysis_stop, timezone, per_user_time_s, max_submission_number,
    max_user_test_number, min_submission_interval_s, min_user_test_interval_s, score_precision,
    scoring_mode, icpc_penalty_minutes, ranking_freeze_time, max_print_jobs, max_print_pages
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37
) RETURNING id, name, description, allowed_localizations, languages, submissions_download_allowed, allow_questions, allow_user_tests, allow_printing, block_hidden_participations, allow_password_authentication, ip_restriction, ip_autologin, single_login, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, start_time, stop_time, analysis_enabled, analysis_start, analysis_stop, timezone, per_user_time_s, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, score_precision, scoring_mode, icpc_penalty_minutes, ranking_freeze_time, ranking_unfrozen, max_print_jobs, max_print_pages, created_at, updated_at, team_mode, max_team_size, questions_per_minute, ranking_visibility, ranking_contestant_view, ranking_when, ranking_freeze_minutes, ranking_show_subtasks, ranking_show_flags, ranking_show_institutions, ranking_show_hidden, ranking_anonymous, status, practice_enabled, default_score_mode, score_visibility, show_compilation_output, max_submission_bytes, registration, invitation_code, password_min_length, session_minutes, max_print_total_pages
`

type CreateContestParams struct {
	Name                        string     `json:"name"`
	Description                 string     `json:"description"`
	AllowedLocalizations        []string   `json:"allowed_localizations"`
	Languages                   []string   `json:"languages"`
	SubmissionsDownloadAllowed  bool       `json:"submissions_download_allowed"`
	AllowQuestions              bool       `json:"allow_questions"`
	AllowUserTests              bool       `json:"allow_user_tests"`
	AllowPrinting               bool       `json:"allow_printing"`
	BlockHiddenParticipations   bool       `json:"block_hidden_participations"`
	AllowPasswordAuthentication bool       `json:"allow_password_authentication"`
	IpRestriction               bool       `json:"ip_restriction"`
	IpAutologin                 bool       `json:"ip_autologin"`
	SingleLogin                 bool       `json:"single_login"`
	TokenMode                   string     `json:"token_mode"`
	TokenMaxNumber              *int32     `json:"token_max_number"`
	TokenMinIntervalS           int64      `json:"token_min_interval_s"`
	TokenGenInitial             int32      `json:"token_gen_initial"`
	TokenGenNumber              int32      `json:"token_gen_number"`
	TokenGenIntervalS           int64      `json:"token_gen_interval_s"`
	TokenGenMax                 *int32     `json:"token_gen_max"`
	StartTime                   time.Time  `json:"start_time"`
	StopTime                    time.Time  `json:"stop_time"`
	AnalysisEnabled             bool       `json:"analysis_enabled"`
	AnalysisStart               *time.Time `json:"analysis_start"`
	AnalysisStop                *time.Time `json:"analysis_stop"`
	Timezone                    string     `json:"timezone"`
	PerUserTimeS                *int64     `json:"per_user_time_s"`
	MaxSubmissionNumber         *int32     `json:"max_submission_number"`
	MaxUserTestNumber           *int32     `json:"max_user_test_number"`
	MinSubmissionIntervalS      *int64     `json:"min_submission_interval_s"`
	MinUserTestIntervalS        *int64     `json:"min_user_test_interval_s"`
	ScorePrecision              int32      `json:"score_precision"`
	ScoringMode                 string     `json:"scoring_mode"`
	IcpcPenaltyMinutes          int32      `json:"icpc_penalty_minutes"`
	RankingFreezeTime           *time.Time `json:"ranking_freeze_time"`
	MaxPrintJobs                int32      `json:"max_print_jobs"`
	MaxPrintPages               int32      `json:"max_print_pages"`
}

func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, createContest,
		arg.Name,
		arg.Description,
		arg.AllowedLocalizations,
		arg.Languages,
		arg.SubmissionsDownloadAllowed,
		arg.AllowQuestions,
		arg.AllowUserTests,
		arg.AllowPrinting,
		arg.BlockHiddenParticipations,
		arg.AllowPasswordAuthentication,
		arg.IpRestriction,
		arg.IpAutologin,
		arg.SingleLogin,
		arg.TokenMode,
		arg.TokenMaxNumber,
		arg.TokenMinIntervalS,
		arg.TokenGenInitial,
		arg.TokenGenNumber,
		arg.TokenGenIntervalS,
		arg.TokenGenMax,
		arg.StartTime,
		arg.StopTime,
		arg.AnalysisEnabled,
		arg.AnalysisStart,
		arg.AnalysisStop,
		arg.Timezone,
		arg.PerUserTimeS,
		arg.MaxSubmissionNumber,
		arg.MaxUserTestNumber,
		arg.MinSubmissionIntervalS,
		arg.MinUserTestIntervalS,
		arg.ScorePrecision,
		arg.ScoringMode,
		arg.IcpcPenaltyMinutes,
		arg.RankingFreezeTime,
		arg.MaxPrintJobs,
		arg.MaxPrintPages,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AllowedLocalizations,
		&i.Languages,
		&i.SubmissionsDownloadAllowed,
		&i.AllowQuestions,
		&i.AllowUserTests,
		&i.AllowPrinting,
		&i.BlockHiddenParticipations,
		&i.AllowPasswordAuthentication,
		&i.IpRestriction,
		&i.IpAutologin,
		&i.SingleLogin,
		&i.TokenMode,
		&i.TokenMaxNumber,
		&i.TokenMinIntervalS,
		&i.TokenGenInitial,
		&i.TokenGenNumber,
		&i.TokenGenIntervalS,
		&i.TokenGenMax,
		&i.StartTime,
		&i.StopTime,
		&i.AnalysisEnabled,
		&i.AnalysisStart,
		&i.AnalysisStop,
		&i.Timezone,
		&i.PerUserTimeS,
		&i.MaxSubmissionNumber,
		&i.MaxUserTestNumber,
		&i.MinSubmissionIntervalS,
		&i.MinUserTestIntervalS,
		&i.ScorePrecision,
		&i.ScoringMode,
		&i.IcpcPenaltyMinutes,
		&i.RankingFreezeTime,
		&i.RankingUnfrozen,
		&i.MaxPrintJobs,
		&i.MaxPrintPages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamMode,
		&i.MaxTeamSize,
		&i.QuestionsPerMinute,
		&i.RankingVisibility,
		&i.RankingContestantView,
		&i.RankingWhen,
		&i.RankingFreezeMinutes,
		&i.RankingShowSubtasks,
		&i.RankingShowFlags,
		&i.RankingShowInstitutions,
		&i.RankingShowHidden,
		&i.RankingAnonymous,
		&i.Status,
		&i.PracticeEnabled,
		&i.DefaultScoreMode,
		&i.ScoreVisibility,
		&i.ShowCompilationOutput,
		&i.MaxSubmissionBytes,
		&i.Registration,
		&i.InvitationCode,
		&i.PasswordMinLength,
		&i.SessionMinutes,
		&i.MaxPrintTotalPages,
	)
	return i, err
}

const deleteContest = `-- name: DeleteContest :exec
DELETE FROM contests WHERE id = $1
`

func (q *Queries) DeleteContest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteContest, id)
	return err
}

const extendContest = `-- name: ExtendContest :exec
UPDATE contests SET
    stop_time = stop_time + ($1::integer * interval '1 minute'),
    per_user_time_s = per_user_time_s + ($1::integer * 60),
    updated_at = now()
WHERE id = $2::bigint
`

type ExtendContestParams struct {
	Minutes int32 `json:"minutes"`
	ID      int64 `json:"id"`
}

// Moves the end (and each per-user window) by some minutes.
func (q *Queries) ExtendContest(ctx context.Context, arg ExtendContestParams) error {
	_, err := q.db.Exec(ctx, extendContest, arg.Minutes, arg.ID)
	return err
}

const getContest = `-- name: GetContest :one
SELECT id, name, description, allowed_localizations, languages, submissions_download_allowed, allow_questions, allow_user_tests, allow_printing, block_hidden_participations, allow_password_authentication, ip_restriction, ip_autologin, single_login, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, start_time, stop_time, analysis_enabled, analysis_start, analysis_stop, timezone, per_user_time_s, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, score_precision, scoring_mode, icpc_penalty_minutes, ranking_freeze_time, ranking_unfrozen, max_print_jobs, max_print_pages, created_at, updated_at, team_mode, max_team_size, questions_per_minute, ranking_visibility, ranking_contestant_view, ranking_when, ranking_freeze_minutes, ranking_show_subtasks, ranking_show_flags, ranking_show_institutions, ranking_show_hidden, ranking_anonymous, status, practice_enabled, default_score_mode, score_visibility, show_compilation_output, max_submission_bytes, registration, invitation_code, password_min_length, session_minutes, max_print_total_pages FROM contests WHERE id = $1
`

func (q *Queries) GetContest(ctx context.Context, id int64) (Contest, error) {
	row := q.db.QueryRow(ctx, getContest, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AllowedLocalizations,
		&i.Languages,
		&i.SubmissionsDownloadAllowed,
		&i.AllowQuestions,
		&i.AllowUserTests,
		&i.AllowPrinting,
		&i.BlockHiddenParticipations,
		&i.AllowPasswordAuthentication,
		&i.IpRestriction,
		&i.IpAutologin,
		&i.SingleLogin,
		&i.TokenMode,
		&i.TokenMaxNumber,
		&i.TokenMinIntervalS,
		&i.TokenGenInitial,
		&i.TokenGenNumber,
		&i.TokenGenIntervalS,
		&i.TokenGenMax,
		&i.StartTime,
		&i.StopTime,
		&i.AnalysisEnabled,
		&i.AnalysisStart,
		&i.AnalysisStop,
		&i.Timezone,
		&i.PerUserTimeS,
		&i.MaxSubmissionNumber,
		&i.MaxUserTestNumber,
		&i.MinSubmissionIntervalS,
		&i.MinUserTestIntervalS,
		&i.ScorePrecision,
		&i.ScoringMode,
		&i.IcpcPenaltyMinutes,
		&i.RankingFreezeTime,
		&i.RankingUnfrozen,
		&i.MaxPrintJobs,
		&i.MaxPrintPages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamMode,
		&i.MaxTeamSize,
		&i.QuestionsPerMinute,
		&i.RankingVisibility,
		&i.RankingContestantView,
		&i.RankingWhen,
		&i.RankingFreezeMinutes,
		&i.RankingShowSubtasks,
		&i.RankingShowFlags,
		&i.RankingShowInstitutions,
		&i.RankingShowHidden,
		&i.RankingAnonymous,
		&i.Status,
		&i.PracticeEnabled,
		&i.DefaultScoreMode,
		&i.ScoreVisibility,
		&i.ShowCompilationOutput,
		&i.MaxSubmissionBytes,
		&i.Registration,
		&i.InvitationCode,
		&i.PasswordMinLength,
		&i.SessionMinutes,
		&i.MaxPrintTotalPages,
	)
	return i, err
}

const getContestByName = `-- name: GetContestByName :one
SELECT id, name, description, allowed_localizations, languages, submissions_download_allowed, allow_questions, allow_user_tests, allow_printing, block_hidden_participations, allow_password_authentication, ip_restriction, ip_autologin, single_login, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, start_time, stop_time, analysis_enabled, analysis_start, analysis_stop, timezone, per_user_time_s, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, score_precision, scoring_mode, icpc_penalty_minutes, ranking_freeze_time, ranking_unfrozen, max_print_jobs, max_print_pages, created_at, updated_at, team_mode, max_team_size, questions_per_minute, ranking_visibility, ranking_contestant_view, ranking_when, ranking_freeze_minutes, ranking_show_subtasks, ranking_show_flags, ranking_show_institutions, ranking_show_hidden, ranking_anonymous, status, practice_enabled, default_score_mode, score_visibility, show_compilation_output, max_submission_bytes, registration, invitation_code, password_min_length, session_minutes, max_print_total_pages FROM contests WHERE name = $1
`

func (q *Queries) GetContestByName(ctx context.Context, name string) (Contest, error) {
	row := q.db.QueryRow(ctx, getContestByName, name)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AllowedLocalizations,
		&i.Languages,
		&i.SubmissionsDownloadAllowed,
		&i.AllowQuestions,
		&i.AllowUserTests,
		&i.AllowPrinting,
		&i.BlockHiddenParticipations,
		&i.AllowPasswordAuthentication,
		&i.IpRestriction,
		&i.IpAutologin,
		&i.SingleLogin,
		&i.TokenMode,
		&i.TokenMaxNumber,
		&i.TokenMinIntervalS,
		&i.TokenGenInitial,
		&i.TokenGenNumber,
		&i.TokenGenIntervalS,
		&i.TokenGenMax,
		&i.StartTime,
		&i.StopTime,
		&i.AnalysisEnabled,
		&i.AnalysisStart,
		&i.AnalysisStop,
		&i.Timezone,
		&i.PerUserTimeS,
		&i.MaxSubmissionNumber,
		&i.MaxUserTestNumber,
		&i.MinSubmissionIntervalS,
		&i.MinUserTestIntervalS,
		&i.ScorePrecision,
		&i.ScoringMode,
		&i.IcpcPenaltyMinutes,
		&i.RankingFreezeTime,
		&i.RankingUnfrozen,
		&i.MaxPrintJobs,
		&i.MaxPrintPages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamMode,
		&i.MaxTeamSize,
		&i.QuestionsPerMinute,
		&i.RankingVisibility,
		&i.RankingContestantView,
		&i.RankingWhen,
		&i.RankingFreezeMinutes,
		&i.RankingShowSubtasks,
		&i.RankingShowFlags,
		&i.RankingShowInstitutions,
		&i.RankingShowHidden,
		&i.RankingAnonymous,
		&i.Status,
		&i.PracticeEnabled,
		&i.DefaultScoreMode,
		&i.ScoreVisibility,
		&i.ShowCompilationOutput,
		&i.MaxSubmissionBytes,
		&i.Registration,
		&i.InvitationCode,
		&i.PasswordMinLength,
		&i.SessionMinutes,
		&i.MaxPrintTotalPages,
	)
	return i, err
}

const listContests = `-- name: ListContests :many
SELECT id, name, description, allowed_localizations, languages, submissions_download_allowed, allow_questions, allow_user_tests, allow_printing, block_hidden_participations, allow_password_authentication, ip_restriction, ip_autologin, single_login, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, start_time, stop_time, analysis_enabled, analysis_start, analysis_stop, timezone, per_user_time_s, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, score_precision, scoring_mode, icpc_penalty_minutes, ranking_freeze_time, ranking_unfrozen, max_print_jobs, max_print_pages, created_at, updated_at, team_mode, max_team_size, questions_per_minute, ranking_visibility, ranking_contestant_view, ranking_when, ranking_freeze_minutes, ranking_show_subtasks, ranking_show_flags, ranking_show_institutions, ranking_show_hidden, ranking_anonymous, status, practice_enabled, default_score_mode, score_visibility, show_compilation_output, max_submission_bytes, registration, invitation_code, password_min_length, session_minutes, max_print_total_pages FROM contests ORDER BY start_time DESC, id DESC
`

func (q *Queries) ListContests(ctx context.Context) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contest{}
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AllowedLocalizations,
			&i.Languages,
			&i.SubmissionsDownloadAllowed,
			&i.AllowQuestions,
			&i.AllowUserTests,
			&i.AllowPrinting,
			&i.BlockHiddenParticipations,
			&i.AllowPasswordAuthentication,
			&i.IpRestriction,
			&i.IpAutologin,
			&i.SingleLogin,
			&i.TokenMode,
			&i.TokenMaxNumber,
			&i.TokenMinIntervalS,
			&i.TokenGenInitial,
			&i.TokenGenNumber,
			&i.TokenGenIntervalS,
			&i.TokenGenMax,
			&i.StartTime,
			&i.StopTime,
			&i.AnalysisEnabled,
			&i.AnalysisStart,
			&i.AnalysisStop,
			&i.Timezone,
			&i.PerUserTimeS,
			&i.MaxSubmissionNumber,
			&i.MaxUserTestNumber,
			&i.MinSubmissionIntervalS,
			&i.MinUserTestIntervalS,
			&i.ScorePrecision,
			&i.ScoringMode,
			&i.IcpcPenaltyMinutes,
			&i.RankingFreezeTime,
			&i.RankingUnfrozen,
			&i.MaxPrintJobs,
			&i.MaxPrintPages,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamMode,
			&i.MaxTeamSize,
			&i.QuestionsPerMinute,
			&i.RankingVisibility,
			&i.RankingContestantView,
			&i.RankingWhen,
			&i.RankingFreezeMinutes,
			&i.RankingShowSubtasks,
			&i.RankingShowFlags,
			&i.RankingShowInstitutions,
			&i.RankingShowHidden,
			&i.RankingAnonymous,
			&i.Status,
			&i.PracticeEnabled,
			&i.DefaultScoreMode,
			&i.ScoreVisibility,
			&i.ShowCompilationOutput,
			&i.MaxSubmissionBytes,
			&i.Registration,
			&i.InvitationCode,
			&i.PasswordMinLength,
			&i.SessionMinutes,
			&i.MaxPrintTotalPages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningContests = `-- name: ListRunningContests :many
SELECT c.id, c.name,
       (c.stop_time + make_interval(secs => coalesce(max(p.delay_time_s + p.extra_time_s), 0)::double precision))::timestamptz AS ends_at
FROM contests c
LEFT JOIN participations p ON p.contest_id = c.id
WHERE c.status = 'published' AND c.start_time <= now()
GROUP BY c.id
HAVING c.stop_time + make_interval(secs => coalesce(max(p.delay_time_s + p.extra_time_s), 0)::double precision) > now()
ORDER BY c.start_time
`

type ListRunningContestsRow struct {
	ID     int64     `json:"id"`
	Name   string    `json:"name"`
	EndsAt time.Time `json:"ends_at"`
}

// Published contests whose official window is open now for somebody (the
// stop time plus the longest delay and extra time of a participant):
// `cmsctl upgrade` does not stop the services then. Few contests: the scan
// needs no index (participations are read through their contest_id index).
func (q *Queries) ListRunningContests(ctx context.Context) ([]ListRunningContestsRow, error) {
	rows, err := q.db.Query(ctx, listRunningContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningContestsRow{}
	for rows.Next() {
		var i ListRunningContestsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContestRankingUnfrozen = `-- name: SetContestRankingUnfrozen :exec
UPDATE contests SET ranking_unfrozen = $2, updated_at = now() WHERE id = $1
`

type SetContestRankingUnfrozenParams struct {
	ID              int64 `json:"id"`
	RankingUnfrozen bool  `json:"ranking_unfrozen"`
}

func (q *Queries) SetContestRankingUnfrozen(ctx context.Context, arg SetContestRankingUnfrozenParams) error {
	_, err := q.db.Exec(ctx, setContestRankingUnfrozen, arg.ID, arg.RankingUnfrozen)
	return err
}

const updateContest = `-- name: UpdateContest :one
UPDATE contests SET
    name = $2, description = $3, allowed_localizations = $4, languages = $5,
    submissions_download_allowed = $6, allow_questions = $7, allow_user_tests = $8,
    allow_printing = $9, block_hidden_participations = $10, allow_password_authentication = $11,
    ip_restriction = $12, ip_autologin = $13, single_login = $14, token_mode = $15,
    token_max_number = $16, token_min_interval_s = $17, token_gen_initial = $18,
    token_gen_number = $19, token_gen_interval_s = $20, token_gen_max = $21, start_time = $22,
    stop_time = $23, analysis_enabled = $24, analysis_start = $25, analysis_stop = $26,
    timezone = $27, per_user_time_s = $28, max_submission_number = $29,
    max_user_test_number = $30, min_submission_interval_s = $31, min_user_test_interval_s = $32,
    score_precision = $33, scoring_mode = $34, icpc_penalty_minutes = $35,
    ranking_freeze_time = $36, max_print_jobs = $37, max_print_pages = $38, questions_per_minute = $39,
    ranking_visibility = $40, ranking_contestant_view = $41, ranking_when = $42, ranking_freeze_minutes = $43,
    ranking_show_subtasks = $44, ranking_show_flags = $45, ranking_show_institutions = $46,
    ranking_show_hidden = $47, ranking_anonymous = $48, status = $49, practice_enabled = $50,
    default_score_mode = $51, score_visibility = $52, show_compilation_output = $53,
    max_submission_bytes = $54, registration = $55, invitation_code = $56, password_min_length = $57,
    session_minutes = $58, team_mode = $59, max_team_size = $60, max_print_total_pages = $61, updated_at = now()
WHERE id = $1
RETURNING id, name, description, allowed_localizations, languages, submissions_download_allowed, allow_questions, allow_user_tests, allow_printing, block_hidden_participations, allow_password_authentication, ip_restriction, ip_autologin, single_login, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, start_time, stop_time, analysis_enabled, analysis_start, analysis_stop, timezone, per_user_time_s, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, score_precision, scoring_mode, icpc_penalty_minutes, ranking_freeze_time, ranking_unfrozen, max_print_jobs, max_print_pages, created_at, updated_at, team_mode, max_team_size, questions_per_minute, ranking_visibility, ranking_contestant_view, ranking_when, ranking_freeze_minutes, ranking_show_subtasks, ranking_show_flags, ranking_show_institutions, ranking_show_hidden, ranking_anonymous, status, practice_enabled, default_score_mode, score_visibility, show_compilation_output, max_submission_bytes, registration, invitation_code, password_min_length, session_minutes, max_print_total_pages
`

type UpdateContestParams struct {
	ID                          int64      `json:"id"`
	Name                        string     `json:"name"`
	Description                 string     `json:"description"`
	AllowedLocalizations        []string   `json:"allowed_localizations"`
	Languages                   []string   `json:"languages"`
	SubmissionsDownloadAllowed  bool       `json:"submissions_download_allowed"`
	AllowQuestions              bool       `json:"allow_questions"`
	AllowUserTests              bool       `json:"allow_user_tests"`
	AllowPrinting               bool       `json:"allow_printing"`
	BlockHiddenParticipations   bool       `json:"block_hidden_participations"`
	AllowPasswordAuthentication bool       `json:"allow_password_authentication"`
	IpRestriction               bool       `json:"ip_restriction"`
	IpAutologin                 bool       `json:"ip_autologin"`
	SingleLogin                 bool       `json:"single_login"`
	TokenMode                   string     `json:"token_mode"`
	TokenMaxNumber              *int32     `json:"token_max_number"`
	TokenMinIntervalS           int64      `json:"token_min_interval_s"`
	TokenGenInitial             int32      `json:"token_gen_initial"`
	TokenGenNumber              int32      `json:"token_gen_number"`
	TokenGenIntervalS           int64      `json:"token_gen_interval_s"`
	TokenGenMax                 *int32     `json:"token_gen_max"`
	StartTime                   time.Time  `json:"start_time"`
	StopTime                    time.Time  `json:"stop_time"`
	AnalysisEnabled             bool       `json:"analysis_enabled"`
	AnalysisStart               *time.Time `json:"analysis_start"`
	AnalysisStop                *time.Time `json:"analysis_stop"`
	Timezone                    string     `json:"timezone"`
	PerUserTimeS                *int64     `json:"per_user_time_s"`
	MaxSubmissionNumber         *int32     `json:"max_submission_number"`
	MaxUserTestNumber           *int32     `json:"max_user_test_number"`
	MinSubmissionIntervalS      *int64     `json:"min_submission_interval_s"`
	MinUserTestIntervalS        *int64     `json:"min_user_test_interval_s"`
	ScorePrecision              int32      `json:"score_precision"`
	ScoringMode                 string     `json:"scoring_mode"`
	IcpcPenaltyMinutes          int32      `json:"icpc_penalty_minutes"`
	RankingFreezeTime           *time.Time `json:"ranking_freeze_time"`
	MaxPrintJobs                int32      `json:"max_print_jobs"`
	MaxPrintPages               int32      `json:"max_print_pages"`
	QuestionsPerMinute          int32      `json:"questions_per_minute"`
	RankingVisibility           string     `json:"ranking_visibility"`
	RankingContestantView       string     `json:"ranking_contestant_view"`
	RankingWhen                 string     `json:"ranking_when"`
	RankingFreezeMinutes        int32      `json:"ranking_freeze_minutes"`
	RankingShowSubtasks         bool       `json:"ranking_show_subtasks"`
	RankingShowFlags            bool       `json:"ranking_show_flags"`
	RankingShowInstitutions     bool       `json:"ranking_show_institutions"`
	RankingShowHidden           bool       `json:"ranking_show_hidden"`
	RankingAnonymous            bool       `json:"ranking_anonymous"`
	Status                      string     `json:"status"`
	PracticeEnabled             bool       `json:"practice_enabled"`
	DefaultScoreMode            string     `json:"default_score_mode"`
	ScoreVisibility             string     `json:"score_visibility"`
	ShowCompilationOutput       bool       `json:"show_compilation_output"`
	MaxSubmissionBytes          *int64     `json:"max_submission_bytes"`
	Registration                string     `json:"registration"`
	InvitationCode              string     `json:"invitation_code"`
	PasswordMinLength           int32      `json:"password_min_length"`
	SessionMinutes              *int32     `json:"session_minutes"`
	TeamMode                    bool       `json:"team_mode"`
	MaxTeamSize                 *int32     `json:"max_team_size"`
	MaxPrintTotalPages          *int32     `json:"max_print_total_pages"`
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, updateContest,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AllowedLocalizations,
		arg.Languages,
		arg.SubmissionsDownloadAllowed,
		arg.AllowQuestions,
		arg.AllowUserTests,
		arg.AllowPrinting,
		arg.BlockHiddenParticipations,
		arg.AllowPasswordAuthentication,
		arg.IpRestriction,
		arg.IpAutologin,
		arg.SingleLogin,
		arg.TokenMode,
		arg.TokenMaxNumber,
		arg.TokenMinIntervalS,
		arg.TokenGenInitial,
		arg.TokenGenNumber,
		arg.TokenGenIntervalS,
		arg.TokenGenMax,
		arg.StartTime,
		arg.StopTime,
		arg.AnalysisEnabled,
		arg.AnalysisStart,
		arg.AnalysisStop,
		arg.Timezone,
		arg.PerUserTimeS,
		arg.MaxSubmissionNumber,
		arg.MaxUserTestNumber,
		arg.MinSubmissionIntervalS,
		arg.MinUserTestIntervalS,
		arg.ScorePrecision,
		arg.ScoringMode,
		arg.IcpcPenaltyMinutes,
		arg.RankingFreezeTime,
		arg.MaxPrintJobs,
		arg.MaxPrintPages,
		arg.QuestionsPerMinute,
		arg.RankingVisibility,
		arg.RankingContestantView,
		arg.RankingWhen,
		arg.RankingFreezeMinutes,
		arg.RankingShowSubtasks,
		arg.RankingShowFlags,
		arg.RankingShowInstitutions,
		arg.RankingShowHidden,
		arg.RankingAnonymous,
		arg.Status,
		arg.PracticeEnabled,
		arg.DefaultScoreMode,
		arg.ScoreVisibility,
		arg.ShowCompilationOutput,
		arg.MaxSubmissionBytes,
		arg.Registration,
		arg.InvitationCode,
		arg.PasswordMinLength,
		arg.SessionMinutes,
		arg.TeamMode,
		arg.MaxTeamSize,
		arg.MaxPrintTotalPages,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AllowedLocalizations,
		&i.Languages,
		&i.SubmissionsDownloadAllowed,
		&i.AllowQuestions,
		&i.AllowUserTests,
		&i.AllowPrinting,
		&i.BlockHiddenParticipations,
		&i.AllowPasswordAuthentication,
		&i.IpRestriction,
		&i.IpAutologin,
		&i.SingleLogin,
		&i.TokenMode,
		&i.TokenMaxNumber,
		&i.TokenMinIntervalS,
		&i.TokenGenInitial,
		&i.TokenGenNumber,
		&i.TokenGenIntervalS,
		&i.TokenGenMax,
		&i.StartTime,
		&i.StopTime,
		&i.AnalysisEnabled,
		&i.AnalysisStart,
		&i.AnalysisStop,
		&i.Timezone,
		&i.PerUserTimeS,
		&i.MaxSubmissionNumber,
		&i.MaxUserTestNumber,
		&i.MinSubmissionIntervalS,
		&i.MinUserTestIntervalS,
		&i.ScorePrecision,
		&i.ScoringMode,
		&i.IcpcPenaltyMinutes,
		&i.RankingFreezeTime,
		&i.RankingUnfrozen,
		&i.MaxPrintJobs,
		&i.MaxPrintPages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamMode,
		&i.MaxTeamSize,
		&i.QuestionsPerMinute,
		&i.RankingVisibility,
		&i.RankingContestantView,
		&i.RankingWhen,
		&i.RankingFreezeMinutes,
		&i.RankingShowSubtasks,
		&i.RankingShowFlags,
		&i.RankingShowInstitutions,
		&i.RankingShowHidden,
		&i.RankingAnonymous,
		&i.Status,
		&i.PracticeEnabled,
		&i.DefaultScoreMode,
		&i.ScoreVisibility,
		&i.ShowCompilationOutput,
		&i.MaxSubmissionBytes,
		&i.Registration,
		&i.InvitationCode,
		&i.PasswordMinLength,
		&i.SessionMinutes,
		&i.MaxPrintTotalPages,
	)
	return i, err
}
