// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateSubmissionFiles implements pgx.CopyFromSource.
type iteratorForCreateSubmissionFiles struct {
	rows                 []CreateSubmissionFilesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSubmissionFiles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSubmissionFiles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SubmissionID,
		r.rows[0].Filename,
		r.rows[0].Digest,
	}, nil
}

func (r iteratorForCreateSubmissionFiles) Err() error {
	return nil
}

func (q *Queries) CreateSubmissionFiles(ctx context.Context, arg []CreateSubmissionFilesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"submission_files"}, []string{"submission_id", "filename", "digest"}, &iteratorForCreateSubmissionFiles{rows: arg})
}

// iteratorForCreateUserTestFiles implements pgx.CopyFromSource.
type iteratorForCreateUserTestFiles struct {
	rows                 []CreateUserTestFilesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateUserTestFiles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateUserTestFiles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserTestID,
		r.rows[0].Filename,
		r.rows[0].Digest,
	}, nil
}

func (r iteratorForCreateUserTestFiles) Err() error {
	return nil
}

func (q *Queries) CreateUserTestFiles(ctx context.Context, arg []CreateUserTestFilesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_test_files"}, []string{"user_test_id", "filename", "digest"}, &iteratorForCreateUserTestFiles{rows: arg})
}
