// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cws.sql

package sqlc

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"
)

const bestPreviousOutputs = `-- name: BestPreviousOutputs :many
SELECT DISTINCT ON (f.filename) f.filename, f.digest
FROM submissions s
JOIN submission_files f ON f.submission_id = s.id
LEFT JOIN testcases tc ON tc.dataset_id = $1::bigint AND f.filename = replace($2::text, '%s', tc.codename)
LEFT JOIN evaluations e ON e.submission_id = s.id AND e.dataset_id = $1::bigint AND e.testcase_id = tc.id
WHERE s.participation_id = $3::bigint AND s.task_id = $4::bigint
ORDER BY f.filename, e.outcome DESC NULLS LAST, s.submitted_at DESC, s.id DESC
`

type BestPreviousOutputsParams struct {
	DatasetID       int64  `json:"dataset_id"`
	Pattern         string `json:"pattern"`
	ParticipationID int64  `json:"participation_id"`
	TaskID          int64  `json:"task_id"`
}

type BestPreviousOutputsRow struct {
	Filename string `json:"filename"`
	Digest   string `json:"digest"`
}

// Output-only tasks: for every output file name, the file of the
// participation's previous submission that scored best on the matching
// testcase of the dataset (the latest one on ties or when unjudged).
func (q *Queries) BestPreviousOutputs(ctx context.Context, arg BestPreviousOutputsParams) ([]BestPreviousOutputsRow, error) {
	rows, err := q.db.Query(ctx, bestPreviousOutputs,
		arg.DatasetID,
		arg.Pattern,
		arg.ParticipationID,
		arg.TaskID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BestPreviousOutputsRow{}
	for rows.Next() {
		var i BestPreviousOutputsRow
		if err := rows.Scan(&i.Filename, &i.Digest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipationView = `-- name: GetParticipationView :one
SELECT p.id, p.contest_id, p.user_id, p.starting_time, p.delay_time_s, p.extra_time_s, p.hidden, p.unrestricted,
       p.login_nonce, p.ip, u.username, u.first_name, u.last_name, u.timezone, u.preferred_languages,
       u.disabled, t.code AS team_code, t.name AS team_name, s.start_time AS site_start_time
FROM participations p
JOIN users u ON u.id = p.user_id
LEFT JOIN teams t ON t.id = p.team_id
LEFT JOIN sites s ON s.id = p.site_id
WHERE p.id = $1
`

type GetParticipationViewRow struct {
	ID                 int64          `json:"id"`
	ContestID          int64          `json:"contest_id"`
	UserID             int64          `json:"user_id"`
	StartingTime       *time.Time     `json:"starting_time"`
	DelayTimeS         int64          `json:"delay_time_s"`
	ExtraTimeS         int64          `json:"extra_time_s"`
	Hidden             bool           `json:"hidden"`
	Unrestricted       bool           `json:"unrestricted"`
	LoginNonce         int64          `json:"login_nonce"`
	Ip                 []netip.Prefix `json:"ip"`
	Username           string         `json:"username"`
	FirstName          string         `json:"first_name"`
	LastName           string         `json:"last_name"`
	Timezone           *string        `json:"timezone"`
	PreferredLanguages []string       `json:"preferred_languages"`
	Disabled           bool           `json:"disabled"`
	TeamCode           *string        `json:"team_code"`
	TeamName           *string        `json:"team_name"`
	SiteStartTime      *time.Time     `json:"site_start_time"`
}

// A contestant's participation with the fields every page needs.
func (q *Queries) GetParticipationView(ctx context.Context, id int64) (GetParticipationViewRow, error) {
	row := q.db.QueryRow(ctx, getParticipationView, id)
	var i GetParticipationViewRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.StartingTime,
		&i.DelayTimeS,
		&i.ExtraTimeS,
		&i.Hidden,
		&i.Unrestricted,
		&i.LoginNonce,
		&i.Ip,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Timezone,
		&i.PreferredLanguages,
		&i.Disabled,
		&i.TeamCode,
		&i.TeamName,
		&i.SiteStartTime,
	)
	return i, err
}

const getSubmissionWithResult = `-- name: GetSubmissionWithResult :one
SELECT s.id, s.participation_id, s.task_id, s.submitted_at, s.language, s.official,
       (k.submission_id IS NOT NULL)::boolean AS tokened,
       sr.compilation_outcome, sr.compilation_text, sr.compilation_stdout, sr.compilation_stderr,
       sr.compilation_time, sr.compilation_memory,
       sr.evaluation_outcome, sr.testcases_done, sr.testcases_total,
       sr.score, sr.score_details, sr.public_score, sr.public_score_details, sr.scored_at, sr.system_error
FROM submissions s
LEFT JOIN submission_results sr ON sr.submission_id = s.id AND sr.dataset_id = $1::bigint
LEFT JOIN tokens k ON k.submission_id = s.id
WHERE s.id = $2::bigint
`

type GetSubmissionWithResultParams struct {
	DatasetID int64 `json:"dataset_id"`
	ID        int64 `json:"id"`
}

type GetSubmissionWithResultRow struct {
	ID                 int64           `json:"id"`
	ParticipationID    *int64          `json:"participation_id"`
	TaskID             int64           `json:"task_id"`
	SubmittedAt        time.Time       `json:"submitted_at"`
	Language           *string         `json:"language"`
	Official           bool            `json:"official"`
	Tokened            bool            `json:"tokened"`
	CompilationOutcome *string         `json:"compilation_outcome"`
	CompilationText    *string         `json:"compilation_text"`
	CompilationStdout  *string         `json:"compilation_stdout"`
	CompilationStderr  *string         `json:"compilation_stderr"`
	CompilationTime    *float64        `json:"compilation_time"`
	CompilationMemory  *int64          `json:"compilation_memory"`
	EvaluationOutcome  *string         `json:"evaluation_outcome"`
	TestcasesDone      *int32          `json:"testcases_done"`
	TestcasesTotal     *int32          `json:"testcases_total"`
	Score              *float64        `json:"score"`
	ScoreDetails       json.RawMessage `json:"score_details"`
	PublicScore        *float64        `json:"public_score"`
	PublicScoreDetails json.RawMessage `json:"public_score_details"`
	ScoredAt           *time.Time      `json:"scored_at"`
	SystemError        *string         `json:"system_error"`
}

func (q *Queries) GetSubmissionWithResult(ctx context.Context, arg GetSubmissionWithResultParams) (GetSubmissionWithResultRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionWithResult, arg.DatasetID, arg.ID)
	var i GetSubmissionWithResultRow
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.SubmittedAt,
		&i.Language,
		&i.Official,
		&i.Tokened,
		&i.CompilationOutcome,
		&i.CompilationText,
		&i.CompilationStdout,
		&i.CompilationStderr,
		&i.CompilationTime,
		&i.CompilationMemory,
		&i.EvaluationOutcome,
		&i.TestcasesDone,
		&i.TestcasesTotal,
		&i.Score,
		&i.ScoreDetails,
		&i.PublicScore,
		&i.PublicScoreDetails,
		&i.ScoredAt,
		&i.SystemError,
	)
	return i, err
}

const listActiveContests = `-- name: ListActiveContests :many
SELECT id, name, description, start_time, stop_time FROM contests
WHERE stop_time > now() - interval '30 days' OR analysis_stop > now()
ORDER BY start_time DESC
`

type ListActiveContestsRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	StartTime   time.Time `json:"start_time"`
	StopTime    time.Time `json:"stop_time"`
}

// Contests shown on the CWS landing page.
func (q *Queries) ListActiveContests(ctx context.Context) ([]ListActiveContestsRow, error) {
	rows, err := q.db.Query(ctx, listActiveContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveContestsRow{}
	for rows.Next() {
		var i ListActiveContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StartTime,
			&i.StopTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoresByParticipation = `-- name: ListScoresByParticipation :many
SELECT task_id, score, subtask_scores, icpc_solved, icpc_attempts, icpc_solved_at, pending
FROM participation_task_scores WHERE participation_id = $1
`

type ListScoresByParticipationRow struct {
	TaskID        int64           `json:"task_id"`
	Score         float64         `json:"score"`
	SubtaskScores json.RawMessage `json:"subtask_scores"`
	IcpcSolved    bool            `json:"icpc_solved"`
	IcpcAttempts  int32           `json:"icpc_attempts"`
	IcpcSolvedAt  *time.Time      `json:"icpc_solved_at"`
	Pending       int32           `json:"pending"`
}

func (q *Queries) ListScoresByParticipation(ctx context.Context, participationID int64) ([]ListScoresByParticipationRow, error) {
	rows, err := q.db.Query(ctx, listScoresByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScoresByParticipationRow{}
	for rows.Next() {
		var i ListScoresByParticipationRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Score,
			&i.SubtaskScores,
			&i.IcpcSolved,
			&i.IcpcAttempts,
			&i.IcpcSolvedAt,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsWithResults = `-- name: ListSubmissionsWithResults :many
SELECT s.id, s.submitted_at, s.language, s.official, (k.submission_id IS NOT NULL)::boolean AS tokened,
       sr.compilation_outcome, sr.evaluation_outcome, sr.testcases_done, sr.testcases_total,
       sr.score, sr.public_score, sr.scored_at, sr.system_error
FROM submissions s
LEFT JOIN submission_results sr ON sr.submission_id = s.id AND sr.dataset_id = $1::bigint
LEFT JOIN tokens k ON k.submission_id = s.id
WHERE s.participation_id = $2::bigint AND s.task_id = $3::bigint
ORDER BY s.submitted_at DESC, s.id DESC
`

type ListSubmissionsWithResultsParams struct {
	DatasetID       int64 `json:"dataset_id"`
	ParticipationID int64 `json:"participation_id"`
	TaskID          int64 `json:"task_id"`
}

type ListSubmissionsWithResultsRow struct {
	ID                 int64      `json:"id"`
	SubmittedAt        time.Time  `json:"submitted_at"`
	Language           *string    `json:"language"`
	Official           bool       `json:"official"`
	Tokened            bool       `json:"tokened"`
	CompilationOutcome *string    `json:"compilation_outcome"`
	EvaluationOutcome  *string    `json:"evaluation_outcome"`
	TestcasesDone      *int32     `json:"testcases_done"`
	TestcasesTotal     *int32     `json:"testcases_total"`
	Score              *float64   `json:"score"`
	PublicScore        *float64   `json:"public_score"`
	ScoredAt           *time.Time `json:"scored_at"`
	SystemError        *string    `json:"system_error"`
}

// A contestant's submissions to a task with their result on the live
// dataset (index: submissions_participation_task_idx + result PK).
func (q *Queries) ListSubmissionsWithResults(ctx context.Context, arg ListSubmissionsWithResultsParams) ([]ListSubmissionsWithResultsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionsWithResults, arg.DatasetID, arg.ParticipationID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsWithResultsRow{}
	for rows.Next() {
		var i ListSubmissionsWithResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedAt,
			&i.Language,
			&i.Official,
			&i.Tokened,
			&i.CompilationOutcome,
			&i.EvaluationOutcome,
			&i.TestcasesDone,
			&i.TestcasesTotal,
			&i.Score,
			&i.PublicScore,
			&i.ScoredAt,
			&i.SystemError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
