// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dispatcher.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const getParticipationTiming = `-- name: GetParticipationTiming :one
SELECT p.starting_time, p.delay_time_s, c.start_time, c.per_user_time_s, c.scoring_mode, c.icpc_penalty_minutes
FROM participations p JOIN contests c ON c.id = p.contest_id
WHERE p.id = $1
`

type GetParticipationTimingRow struct {
	StartingTime       *time.Time `json:"starting_time"`
	DelayTimeS         int64      `json:"delay_time_s"`
	StartTime          time.Time  `json:"start_time"`
	PerUserTimeS       *int64     `json:"per_user_time_s"`
	ScoringMode        string     `json:"scoring_mode"`
	IcpcPenaltyMinutes int32      `json:"icpc_penalty_minutes"`
}

func (q *Queries) GetParticipationTiming(ctx context.Context, id int64) (GetParticipationTimingRow, error) {
	row := q.db.QueryRow(ctx, getParticipationTiming, id)
	var i GetParticipationTimingRow
	err := row.Scan(
		&i.StartingTime,
		&i.DelayTimeS,
		&i.StartTime,
		&i.PerUserTimeS,
		&i.ScoringMode,
		&i.IcpcPenaltyMinutes,
	)
	return i, err
}

const getSubmissionMeta = `-- name: GetSubmissionMeta :one
SELECT s.id, s.participation_id, s.task_id, s.submitted_at, s.language, s.official,
       p.contest_id, t.active_dataset_id, t.score_mode, t.score_precision
FROM submissions s
JOIN participations p ON p.id = s.participation_id
JOIN tasks t ON t.id = s.task_id
WHERE s.id = $1
`

type GetSubmissionMetaRow struct {
	ID              int64     `json:"id"`
	ParticipationID int64     `json:"participation_id"`
	TaskID          int64     `json:"task_id"`
	SubmittedAt     time.Time `json:"submitted_at"`
	Language        *string   `json:"language"`
	Official        bool      `json:"official"`
	ContestID       int64     `json:"contest_id"`
	ActiveDatasetID *int64    `json:"active_dataset_id"`
	ScoreMode       string    `json:"score_mode"`
	ScorePrecision  int32     `json:"score_precision"`
}

// What the dispatcher needs about a submission, in one round trip.
func (q *Queries) GetSubmissionMeta(ctx context.Context, id int64) (GetSubmissionMetaRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionMeta, id)
	var i GetSubmissionMetaRow
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.SubmittedAt,
		&i.Language,
		&i.Official,
		&i.ContestID,
		&i.ActiveDatasetID,
		&i.ScoreMode,
		&i.ScorePrecision,
	)
	return i, err
}

const getUserTestMeta = `-- name: GetUserTestMeta :one
SELECT u.id, u.participation_id, u.task_id, u.language, u.input_digest, t.active_dataset_id
FROM user_tests u JOIN tasks t ON t.id = u.task_id
WHERE u.id = $1
`

type GetUserTestMetaRow struct {
	ID              int64   `json:"id"`
	ParticipationID int64   `json:"participation_id"`
	TaskID          int64   `json:"task_id"`
	Language        *string `json:"language"`
	InputDigest     string  `json:"input_digest"`
	ActiveDatasetID *int64  `json:"active_dataset_id"`
}

func (q *Queries) GetUserTestMeta(ctx context.Context, id int64) (GetUserTestMetaRow, error) {
	row := q.db.QueryRow(ctx, getUserTestMeta, id)
	var i GetUserTestMetaRow
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.Language,
		&i.InputDigest,
		&i.ActiveDatasetID,
	)
	return i, err
}

const listEvaluatedTestcaseIDs = `-- name: ListEvaluatedTestcaseIDs :many
SELECT testcase_id FROM evaluations WHERE submission_id = $1 AND dataset_id = $2
`

type ListEvaluatedTestcaseIDsParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

func (q *Queries) ListEvaluatedTestcaseIDs(ctx context.Context, arg ListEvaluatedTestcaseIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listEvaluatedTestcaseIDs, arg.SubmissionID, arg.DatasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var testcase_id int64
		if err := rows.Scan(&testcase_id); err != nil {
			return nil, err
		}
		items = append(items, testcase_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipationsWithSubmissions = `-- name: ListParticipationsWithSubmissions :many
SELECT DISTINCT participation_id FROM submissions WHERE task_id = $1
`

// (participation, task) pairs with submissions on a task (re-aggregation
// after the live dataset changes).
func (q *Queries) ListParticipationsWithSubmissions(ctx context.Context, taskID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listParticipationsWithSubmissions, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var participation_id int64
		if err := rows.Scan(&participation_id); err != nil {
			return nil, err
		}
		items = append(items, participation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsMissingResults = `-- name: ListSubmissionsMissingResults :many
SELECT s.id AS submission_id, d.id AS dataset_id
FROM submissions s
JOIN tasks t ON t.id = s.task_id
JOIN datasets d ON d.task_id = s.task_id AND (d.id = t.active_dataset_id OR d.autojudge)
WHERE NOT EXISTS (SELECT 1 FROM submission_results sr WHERE sr.submission_id = s.id AND sr.dataset_id = d.id)
ORDER BY s.id
LIMIT $1
`

type ListSubmissionsMissingResultsRow struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

// Submissions lacking a result on a dataset they must be judged on (live
// or autojudge), e.g. a lost "new submission" notification.
func (q *Queries) ListSubmissionsMissingResults(ctx context.Context, limit int32) ([]ListSubmissionsMissingResultsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionsMissingResults, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsMissingResultsRow{}
	for rows.Next() {
		var i ListSubmissionsMissingResultsRow
		if err := rows.Scan(&i.SubmissionID, &i.DatasetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweepableResults = `-- name: ListSweepableResults :many
SELECT submission_id, dataset_id, generation, compilation_outcome, evaluation_outcome, jobs_enqueued_at
FROM submission_results
WHERE scored_at IS NULL AND system_error IS NULL
  AND (jobs_enqueued_at IS NULL OR jobs_enqueued_at < $1::timestamptz)
ORDER BY jobs_enqueued_at NULLS FIRST, submission_id
LIMIT $2::integer
`

type ListSweepableResultsParams struct {
	StaleBefore time.Time `json:"stale_before"`
	MaxRows     int32     `json:"max_rows"`
}

type ListSweepableResultsRow struct {
	SubmissionID       int64      `json:"submission_id"`
	DatasetID          int64      `json:"dataset_id"`
	Generation         int32      `json:"generation"`
	CompilationOutcome *string    `json:"compilation_outcome"`
	EvaluationOutcome  *string    `json:"evaluation_outcome"`
	JobsEnqueuedAt     *time.Time `json:"jobs_enqueued_at"`
}

// Results needing work: never enqueued (new or invalidated) or enqueued
// longer ago than the grace period.
func (q *Queries) ListSweepableResults(ctx context.Context, arg ListSweepableResultsParams) ([]ListSweepableResultsRow, error) {
	rows, err := q.db.Query(ctx, listSweepableResults, arg.StaleBefore, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSweepableResultsRow{}
	for rows.Next() {
		var i ListSweepableResultsRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.DatasetID,
			&i.Generation,
			&i.CompilationOutcome,
			&i.EvaluationOutcome,
			&i.JobsEnqueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweepableUserTests = `-- name: ListSweepableUserTests :many
SELECT user_test_id, dataset_id, generation
FROM user_test_results
WHERE completed_at IS NULL AND system_error IS NULL
  AND (jobs_enqueued_at IS NULL OR jobs_enqueued_at < $1::timestamptz)
ORDER BY jobs_enqueued_at NULLS FIRST, user_test_id
LIMIT $2::integer
`

type ListSweepableUserTestsParams struct {
	StaleBefore time.Time `json:"stale_before"`
	MaxRows     int32     `json:"max_rows"`
}

type ListSweepableUserTestsRow struct {
	UserTestID int64 `json:"user_test_id"`
	DatasetID  int64 `json:"dataset_id"`
	Generation int32 `json:"generation"`
}

func (q *Queries) ListSweepableUserTests(ctx context.Context, arg ListSweepableUserTestsParams) ([]ListSweepableUserTestsRow, error) {
	rows, err := q.db.Query(ctx, listSweepableUserTests, arg.StaleBefore, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSweepableUserTestsRow{}
	for rows.Next() {
		var i ListSweepableUserTestsRow
		if err := rows.Scan(&i.UserTestID, &i.DatasetID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskSubmissionsForScore = `-- name: ListTaskSubmissionsForScore :many
SELECT s.id, s.submitted_at, s.official, (k.submission_id IS NOT NULL)::boolean AS tokened,
       sr.compilation_outcome, sr.score, sr.ranking_score_details, sr.scored_at
FROM submissions s
LEFT JOIN submission_results sr ON sr.submission_id = s.id AND sr.dataset_id = $1::bigint
LEFT JOIN tokens k ON k.submission_id = s.id
WHERE s.participation_id = $2::bigint AND s.task_id = $3::bigint
ORDER BY s.submitted_at, s.id
`

type ListTaskSubmissionsForScoreParams struct {
	DatasetID       int64 `json:"dataset_id"`
	ParticipationID int64 `json:"participation_id"`
	TaskID          int64 `json:"task_id"`
}

type ListTaskSubmissionsForScoreRow struct {
	ID                  int64           `json:"id"`
	SubmittedAt         time.Time       `json:"submitted_at"`
	Official            bool            `json:"official"`
	Tokened             bool            `json:"tokened"`
	CompilationOutcome  *string         `json:"compilation_outcome"`
	Score               *float64        `json:"score"`
	RankingScoreDetails json.RawMessage `json:"ranking_score_details"`
	ScoredAt            *time.Time      `json:"scored_at"`
}

// Every submission of a participation on a task with its result on a
// dataset, for the task-score aggregation.
func (q *Queries) ListTaskSubmissionsForScore(ctx context.Context, arg ListTaskSubmissionsForScoreParams) ([]ListTaskSubmissionsForScoreRow, error) {
	rows, err := q.db.Query(ctx, listTaskSubmissionsForScore, arg.DatasetID, arg.ParticipationID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskSubmissionsForScoreRow{}
	for rows.Next() {
		var i ListTaskSubmissionsForScoreRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedAt,
			&i.Official,
			&i.Tokened,
			&i.CompilationOutcome,
			&i.Score,
			&i.RankingScoreDetails,
			&i.ScoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTestsMissingResults = `-- name: ListUserTestsMissingResults :many
SELECT u.id AS user_test_id, t.active_dataset_id::bigint AS dataset_id
FROM user_tests u JOIN tasks t ON t.id = u.task_id
WHERE t.active_dataset_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM user_test_results r WHERE r.user_test_id = u.id AND r.dataset_id = t.active_dataset_id)
ORDER BY u.id
LIMIT $1
`

type ListUserTestsMissingResultsRow struct {
	UserTestID int64 `json:"user_test_id"`
	DatasetID  int64 `json:"dataset_id"`
}

func (q *Queries) ListUserTestsMissingResults(ctx context.Context, limit int32) ([]ListUserTestsMissingResultsRow, error) {
	rows, err := q.db.Query(ctx, listUserTestsMissingResults, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTestsMissingResultsRow{}
	for rows.Next() {
		var i ListUserTestsMissingResultsRow
		if err := rows.Scan(&i.UserTestID, &i.DatasetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSubmissionResult = `-- name: LockSubmissionResult :one
SELECT generation, compilation_outcome, evaluation_outcome, testcases_total, scored_at, system_error
FROM submission_results WHERE submission_id = $1 AND dataset_id = $2
FOR UPDATE
`

type LockSubmissionResultParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

type LockSubmissionResultRow struct {
	Generation         int32      `json:"generation"`
	CompilationOutcome *string    `json:"compilation_outcome"`
	EvaluationOutcome  *string    `json:"evaluation_outcome"`
	TestcasesTotal     int32      `json:"testcases_total"`
	ScoredAt           *time.Time `json:"scored_at"`
	SystemError        *string    `json:"system_error"`
}

// Serialises result processing per (submission, dataset).
func (q *Queries) LockSubmissionResult(ctx context.Context, arg LockSubmissionResultParams) (LockSubmissionResultRow, error) {
	row := q.db.QueryRow(ctx, lockSubmissionResult, arg.SubmissionID, arg.DatasetID)
	var i LockSubmissionResultRow
	err := row.Scan(
		&i.Generation,
		&i.CompilationOutcome,
		&i.EvaluationOutcome,
		&i.TestcasesTotal,
		&i.ScoredAt,
		&i.SystemError,
	)
	return i, err
}

const lockUserTestResult = `-- name: LockUserTestResult :one
SELECT generation, compilation_outcome, completed_at FROM user_test_results
WHERE user_test_id = $1 AND dataset_id = $2 FOR UPDATE
`

type LockUserTestResultParams struct {
	UserTestID int64 `json:"user_test_id"`
	DatasetID  int64 `json:"dataset_id"`
}

type LockUserTestResultRow struct {
	Generation         int32      `json:"generation"`
	CompilationOutcome *string    `json:"compilation_outcome"`
	CompletedAt        *time.Time `json:"completed_at"`
}

func (q *Queries) LockUserTestResult(ctx context.Context, arg LockUserTestResultParams) (LockUserTestResultRow, error) {
	row := q.db.QueryRow(ctx, lockUserTestResult, arg.UserTestID, arg.DatasetID)
	var i LockUserTestResultRow
	err := row.Scan(&i.Generation, &i.CompilationOutcome, &i.CompletedAt)
	return i, err
}

const markJobsEnqueued = `-- name: MarkJobsEnqueued :exec
UPDATE submission_results SET jobs_enqueued_at = now() WHERE submission_id = $1 AND dataset_id = $2
`

type MarkJobsEnqueuedParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

func (q *Queries) MarkJobsEnqueued(ctx context.Context, arg MarkJobsEnqueuedParams) error {
	_, err := q.db.Exec(ctx, markJobsEnqueued, arg.SubmissionID, arg.DatasetID)
	return err
}

const setCompilationFailedScore = `-- name: SetCompilationFailedScore :exec
UPDATE submission_results SET score = 0, public_score = 0, score_details = '{}', public_score_details = '{}',
    ranking_score_details = '[]', scored_at = now()
WHERE submission_id = $1 AND dataset_id = $2
`

type SetCompilationFailedScoreParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

// A submission that does not compile scores zero.
func (q *Queries) SetCompilationFailedScore(ctx context.Context, arg SetCompilationFailedScoreParams) error {
	_, err := q.db.Exec(ctx, setCompilationFailedScore, arg.SubmissionID, arg.DatasetID)
	return err
}

const setUserTestJobsEnqueued = `-- name: SetUserTestJobsEnqueued :exec
UPDATE user_test_results SET jobs_enqueued_at = now() WHERE user_test_id = $1 AND dataset_id = $2
`

type SetUserTestJobsEnqueuedParams struct {
	UserTestID int64 `json:"user_test_id"`
	DatasetID  int64 `json:"dataset_id"`
}

func (q *Queries) SetUserTestJobsEnqueued(ctx context.Context, arg SetUserTestJobsEnqueuedParams) error {
	_, err := q.db.Exec(ctx, setUserTestJobsEnqueued, arg.UserTestID, arg.DatasetID)
	return err
}
