// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"net/netip"
	"time"
)

type Admin struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Enabled      bool      `json:"enabled"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	TotpSecret   *string   `json:"totp_secret"`
}

type Announcement struct {
	ID        int64     `json:"id"`
	ContestID int64     `json:"contest_id"`
	CreatedAt time.Time `json:"created_at"`
	Subject   string    `json:"subject"`
	Text      string    `json:"text"`
	AdminID   *int64    `json:"admin_id"`
}

type Attachment struct {
	ID       int64  `json:"id"`
	TaskID   int64  `json:"task_id"`
	Filename string `json:"filename"`
	Digest   string `json:"digest"`
}

type AuditLog struct {
	ID         int64           `json:"id"`
	AdminID    *int64          `json:"admin_id"`
	CreatedAt  time.Time       `json:"created_at"`
	Action     string          `json:"action"`
	TargetType string          `json:"target_type"`
	TargetID   *int64          `json:"target_id"`
	Details    json.RawMessage `json:"details"`
	Ip         string          `json:"ip"`
}

type Balloon struct {
	TaskID      int64     `json:"task_id"`
	Recipient   string    `json:"recipient"`
	DeliveredAt time.Time `json:"delivered_at"`
	DeliveredBy *int64    `json:"delivered_by"`
}

type Blob struct {
	Digest      string    `json:"digest"`
	Size        int64     `json:"size"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Contest struct {
	ID                          int64      `json:"id"`
	Name                        string     `json:"name"`
	Description                 string     `json:"description"`
	AllowedLocalizations        []string   `json:"allowed_localizations"`
	Languages                   []string   `json:"languages"`
	SubmissionsDownloadAllowed  bool       `json:"submissions_download_allowed"`
	AllowQuestions              bool       `json:"allow_questions"`
	AllowUserTests              bool       `json:"allow_user_tests"`
	AllowPrinting               bool       `json:"allow_printing"`
	BlockHiddenParticipations   bool       `json:"block_hidden_participations"`
	AllowPasswordAuthentication bool       `json:"allow_password_authentication"`
	IpRestriction               bool       `json:"ip_restriction"`
	IpAutologin                 bool       `json:"ip_autologin"`
	SingleLogin                 bool       `json:"single_login"`
	TokenMode                   string     `json:"token_mode"`
	TokenMaxNumber              *int32     `json:"token_max_number"`
	TokenMinIntervalS           int64      `json:"token_min_interval_s"`
	TokenGenInitial             int32      `json:"token_gen_initial"`
	TokenGenNumber              int32      `json:"token_gen_number"`
	TokenGenIntervalS           int64      `json:"token_gen_interval_s"`
	TokenGenMax                 *int32     `json:"token_gen_max"`
	StartTime                   time.Time  `json:"start_time"`
	StopTime                    time.Time  `json:"stop_time"`
	AnalysisEnabled             bool       `json:"analysis_enabled"`
	AnalysisStart               *time.Time `json:"analysis_start"`
	AnalysisStop                *time.Time `json:"analysis_stop"`
	Timezone                    string     `json:"timezone"`
	PerUserTimeS                *int64     `json:"per_user_time_s"`
	MaxSubmissionNumber         *int32     `json:"max_submission_number"`
	MaxUserTestNumber           *int32     `json:"max_user_test_number"`
	MinSubmissionIntervalS      *int64     `json:"min_submission_interval_s"`
	MinUserTestIntervalS        *int64     `json:"min_user_test_interval_s"`
	ScorePrecision              int32      `json:"score_precision"`
	ScoringMode                 string     `json:"scoring_mode"`
	IcpcPenaltyMinutes          int32      `json:"icpc_penalty_minutes"`
	RankingFreezeTime           *time.Time `json:"ranking_freeze_time"`
	RankingUnfrozen             bool       `json:"ranking_unfrozen"`
	MaxPrintJobs                int32      `json:"max_print_jobs"`
	MaxPrintPages               int32      `json:"max_print_pages"`
	CreatedAt                   time.Time  `json:"created_at"`
	UpdatedAt                   time.Time  `json:"updated_at"`
	TeamMode                    bool       `json:"team_mode"`
	MaxTeamSize                 *int32     `json:"max_team_size"`
	QuestionsPerMinute          int32      `json:"questions_per_minute"`
	RankingVisibility           string     `json:"ranking_visibility"`
	RankingContestantView       string     `json:"ranking_contestant_view"`
	RankingWhen                 string     `json:"ranking_when"`
	RankingFreezeMinutes        int32      `json:"ranking_freeze_minutes"`
	RankingShowSubtasks         bool       `json:"ranking_show_subtasks"`
	RankingShowFlags            bool       `json:"ranking_show_flags"`
	RankingShowInstitutions     bool       `json:"ranking_show_institutions"`
	RankingShowHidden           bool       `json:"ranking_show_hidden"`
	RankingAnonymous            bool       `json:"ranking_anonymous"`
	Status                      string     `json:"status"`
	PracticeEnabled             bool       `json:"practice_enabled"`
	DefaultScoreMode            string     `json:"default_score_mode"`
	ScoreVisibility             string     `json:"score_visibility"`
	ShowCompilationOutput       bool       `json:"show_compilation_output"`
	MaxSubmissionBytes          *int64     `json:"max_submission_bytes"`
	Registration                string     `json:"registration"`
	InvitationCode              string     `json:"invitation_code"`
	PasswordMinLength           int32      `json:"password_min_length"`
	SessionMinutes              *int32     `json:"session_minutes"`
}

type Dataset struct {
	ID                   int64           `json:"id"`
	TaskID               int64           `json:"task_id"`
	Description          string          `json:"description"`
	Autojudge            bool            `json:"autojudge"`
	TimeLimitMs          *int32          `json:"time_limit_ms"`
	WallTimeLimitMs      *int32          `json:"wall_time_limit_ms"`
	MemoryLimitBytes     *int64          `json:"memory_limit_bytes"`
	OutputLimitBytes     int64           `json:"output_limit_bytes"`
	ProcessLimit         int32           `json:"process_limit"`
	SourceSizeLimitBytes *int64          `json:"source_size_limit_bytes"`
	TaskType             string          `json:"task_type"`
	TaskTypeParams       json.RawMessage `json:"task_type_params"`
	ScoreType            string          `json:"score_type"`
	ScoreTypeParams      json.RawMessage `json:"score_type_params"`
	CreatedAt            time.Time       `json:"created_at"`
}

type Evaluation struct {
	SubmissionID      int64     `json:"submission_id"`
	DatasetID         int64     `json:"dataset_id"`
	TestcaseID        int64     `json:"testcase_id"`
	Outcome           float64   `json:"outcome"`
	Text              string    `json:"text"`
	ExecutionTime     *float64  `json:"execution_time"`
	ExecutionWallTime *float64  `json:"execution_wall_time"`
	ExecutionMemory   *int64    `json:"execution_memory"`
	ExitStatus        string    `json:"exit_status"`
	ExitCode          *int32    `json:"exit_code"`
	Signal            *int32    `json:"signal"`
	Worker            *string   `json:"worker"`
	CreatedAt         time.Time `json:"created_at"`
}

type Executable struct {
	ID           int64  `json:"id"`
	SubmissionID int64  `json:"submission_id"`
	DatasetID    int64  `json:"dataset_id"`
	Filename     string `json:"filename"`
	Digest       string `json:"digest"`
}

type Language struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Config    json.RawMessage `json:"config"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Manager struct {
	ID        int64  `json:"id"`
	DatasetID int64  `json:"dataset_id"`
	Filename  string `json:"filename"`
	Digest    string `json:"digest"`
}

type Message struct {
	ID              int64     `json:"id"`
	ParticipationID int64     `json:"participation_id"`
	CreatedAt       time.Time `json:"created_at"`
	Subject         string    `json:"subject"`
	Text            string    `json:"text"`
	AdminID         *int64    `json:"admin_id"`
}

type Participation struct {
	ID                  int64          `json:"id"`
	ContestID           int64          `json:"contest_id"`
	UserID              int64          `json:"user_id"`
	TeamID              *int64         `json:"team_id"`
	PasswordHash        *string        `json:"password_hash"`
	Ip                  []netip.Prefix `json:"ip"`
	StartingTime        *time.Time     `json:"starting_time"`
	DelayTimeS          int64          `json:"delay_time_s"`
	ExtraTimeS          int64          `json:"extra_time_s"`
	Hidden              bool           `json:"hidden"`
	Unrestricted        bool           `json:"unrestricted"`
	LoginNonce          int64          `json:"login_nonce"`
	SiteID              *int64         `json:"site_id"`
	CommunicationSeenAt time.Time      `json:"communication_seen_at"`
	Approved            bool           `json:"approved"`
}

type ParticipationTaskScore struct {
	ParticipationID  int64           `json:"participation_id"`
	TaskID           int64           `json:"task_id"`
	Score            float64         `json:"score"`
	SubtaskScores    json.RawMessage `json:"subtask_scores"`
	IcpcSolved       bool            `json:"icpc_solved"`
	IcpcAttempts     int32           `json:"icpc_attempts"`
	IcpcSolvedAt     *time.Time      `json:"icpc_solved_at"`
	Pending          int32           `json:"pending"`
	LastSubmissionAt *time.Time      `json:"last_submission_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type PrintJob struct {
	ID              int64     `json:"id"`
	ParticipationID int64     `json:"participation_id"`
	CreatedAt       time.Time `json:"created_at"`
	Filename        string    `json:"filename"`
	Digest          string    `json:"digest"`
	Status          string    `json:"status"`
	StatusText      string    `json:"status_text"`
	Pages           *int32    `json:"pages"`
}

type Question struct {
	ID              int64      `json:"id"`
	ParticipationID int64      `json:"participation_id"`
	AskedAt         time.Time  `json:"asked_at"`
	Subject         string     `json:"subject"`
	Text            string     `json:"text"`
	ReplyAt         *time.Time `json:"reply_at"`
	ReplySubject    *string    `json:"reply_subject"`
	ReplyText       *string    `json:"reply_text"`
	ReplyAdminID    *int64     `json:"reply_admin_id"`
	Ignored         bool       `json:"ignored"`
	ContestID       int64      `json:"contest_id"`
	TaskID          *int64     `json:"task_id"`
	Public          bool       `json:"public"`
}

type Site struct {
	ID        int64      `json:"id"`
	ContestID int64      `json:"contest_id"`
	Name      string     `json:"name"`
	StartTime *time.Time `json:"start_time"`
}

type Statement struct {
	ID          int64  `json:"id"`
	TaskID      int64  `json:"task_id"`
	Language    string `json:"language"`
	Digest      string `json:"digest"`
	ContentType string `json:"content_type"`
}

type Submission struct {
	ID                int64      `json:"id"`
	ParticipationID   *int64     `json:"participation_id"`
	TaskID            int64      `json:"task_id"`
	SubmittedAt       time.Time  `json:"submitted_at"`
	Language          *string    `json:"language"`
	Comment           string     `json:"comment"`
	Official          bool       `json:"official"`
	Tester            bool       `json:"tester"`
	TesterAdminID     *int64     `json:"tester_admin_id"`
	InvalidatedAt     *time.Time `json:"invalidated_at"`
	InvalidatedReason string     `json:"invalidated_reason"`
	InvalidatedBy     *int64     `json:"invalidated_by"`
}

type SubmissionFile struct {
	ID           int64  `json:"id"`
	SubmissionID int64  `json:"submission_id"`
	Filename     string `json:"filename"`
	Digest       string `json:"digest"`
}

type SubmissionResult struct {
	SubmissionID        int64           `json:"submission_id"`
	DatasetID           int64           `json:"dataset_id"`
	Generation          int32           `json:"generation"`
	CompilationOutcome  *string         `json:"compilation_outcome"`
	CompilationText     string          `json:"compilation_text"`
	CompilationStdout   string          `json:"compilation_stdout"`
	CompilationStderr   string          `json:"compilation_stderr"`
	CompilationTries    int32           `json:"compilation_tries"`
	CompilationTime     *float64        `json:"compilation_time"`
	CompilationWallTime *float64        `json:"compilation_wall_time"`
	CompilationMemory   *int64          `json:"compilation_memory"`
	CompilationWorker   *string         `json:"compilation_worker"`
	EvaluationOutcome   *string         `json:"evaluation_outcome"`
	EvaluationTries     int32           `json:"evaluation_tries"`
	TestcasesTotal      int32           `json:"testcases_total"`
	TestcasesDone       int32           `json:"testcases_done"`
	Score               *float64        `json:"score"`
	ScoreDetails        json.RawMessage `json:"score_details"`
	PublicScore         *float64        `json:"public_score"`
	PublicScoreDetails  json.RawMessage `json:"public_score_details"`
	RankingScoreDetails json.RawMessage `json:"ranking_score_details"`
	ScoredAt            *time.Time      `json:"scored_at"`
	SystemError         *string         `json:"system_error"`
	CreatedAt           time.Time       `json:"created_at"`
	JobsEnqueuedAt      *time.Time      `json:"jobs_enqueued_at"`
	Verdict             *string         `json:"verdict"`
}

type Task struct {
	ID                     int64     `json:"id"`
	ContestID              *int64    `json:"contest_id"`
	Num                    *int32    `json:"num"`
	Name                   string    `json:"name"`
	Title                  string    `json:"title"`
	PrimaryStatements      []string  `json:"primary_statements"`
	SubmissionFormat       []string  `json:"submission_format"`
	TokenMode              string    `json:"token_mode"`
	TokenMaxNumber         *int32    `json:"token_max_number"`
	TokenMinIntervalS      int64     `json:"token_min_interval_s"`
	TokenGenInitial        int32     `json:"token_gen_initial"`
	TokenGenNumber         int32     `json:"token_gen_number"`
	TokenGenIntervalS      int64     `json:"token_gen_interval_s"`
	TokenGenMax            *int32    `json:"token_gen_max"`
	MaxSubmissionNumber    *int32    `json:"max_submission_number"`
	MaxUserTestNumber      *int32    `json:"max_user_test_number"`
	MinSubmissionIntervalS *int64    `json:"min_submission_interval_s"`
	MinUserTestIntervalS   *int64    `json:"min_user_test_interval_s"`
	FeedbackLevel          string    `json:"feedback_level"`
	ScorePrecision         int32     `json:"score_precision"`
	ScoreMode              string    `json:"score_mode"`
	ActiveDatasetID        *int64    `json:"active_dataset_id"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
	Languages              []string  `json:"languages"`
}

type Team struct {
	ID          int64   `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	FlagDigest  *string `json:"flag_digest"`
	PhotoDigest *string `json:"photo_digest"`
	Institution string  `json:"institution"`
}

type Testcase struct {
	ID           int64  `json:"id"`
	DatasetID    int64  `json:"dataset_id"`
	Codename     string `json:"codename"`
	Public       bool   `json:"public"`
	InputDigest  string `json:"input_digest"`
	OutputDigest string `json:"output_digest"`
}

type Token struct {
	ID           int64     `json:"id"`
	SubmissionID int64     `json:"submission_id"`
	PlayedAt     time.Time `json:"played_at"`
}

type User struct {
	ID                 int64     `json:"id"`
	Username           string    `json:"username"`
	FirstName          string    `json:"first_name"`
	LastName           string    `json:"last_name"`
	Email              string    `json:"email"`
	PasswordHash       string    `json:"password_hash"`
	Timezone           *string   `json:"timezone"`
	PreferredLanguages []string  `json:"preferred_languages"`
	CreatedAt          time.Time `json:"created_at"`
	Institution        string    `json:"institution"`
	Country            string    `json:"country"`
	Region             string    `json:"region"`
	PhotoDigest        *string   `json:"photo_digest"`
	Disabled           bool      `json:"disabled"`
}

type UserTest struct {
	ID              int64     `json:"id"`
	ParticipationID int64     `json:"participation_id"`
	TaskID          int64     `json:"task_id"`
	SubmittedAt     time.Time `json:"submitted_at"`
	Language        *string   `json:"language"`
	InputDigest     string    `json:"input_digest"`
}

type UserTestExecutable struct {
	ID         int64  `json:"id"`
	UserTestID int64  `json:"user_test_id"`
	DatasetID  int64  `json:"dataset_id"`
	Filename   string `json:"filename"`
	Digest     string `json:"digest"`
}

type UserTestFile struct {
	ID         int64  `json:"id"`
	UserTestID int64  `json:"user_test_id"`
	Filename   string `json:"filename"`
	Digest     string `json:"digest"`
}

type UserTestResult struct {
	UserTestID          int64      `json:"user_test_id"`
	DatasetID           int64      `json:"dataset_id"`
	Generation          int32      `json:"generation"`
	CompilationOutcome  *string    `json:"compilation_outcome"`
	CompilationText     string     `json:"compilation_text"`
	CompilationStdout   string     `json:"compilation_stdout"`
	CompilationStderr   string     `json:"compilation_stderr"`
	CompilationTries    int32      `json:"compilation_tries"`
	CompilationTime     *float64   `json:"compilation_time"`
	CompilationWallTime *float64   `json:"compilation_wall_time"`
	CompilationMemory   *int64     `json:"compilation_memory"`
	EvaluationOutcome   *string    `json:"evaluation_outcome"`
	EvaluationText      string     `json:"evaluation_text"`
	EvaluationTries     int32      `json:"evaluation_tries"`
	OutputDigest        *string    `json:"output_digest"`
	ExecutionTime       *float64   `json:"execution_time"`
	ExecutionWallTime   *float64   `json:"execution_wall_time"`
	ExecutionMemory     *int64     `json:"execution_memory"`
	ExitStatus          *string    `json:"exit_status"`
	SystemError         *string    `json:"system_error"`
	CompletedAt         *time.Time `json:"completed_at"`
	JobsEnqueuedAt      *time.Time `json:"jobs_enqueued_at"`
}
