// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rehearsal.sql

package sqlc

import (
	"context"
	"time"
)

const listReplaySubmissions = `-- name: ListReplaySubmissions :many
SELECT s.id, s.submitted_at, s.language, u.username, t.num AS task_num, t.name AS task_name
FROM participations p
JOIN users u ON u.id = p.user_id
JOIN submissions s ON s.participation_id = p.id
JOIN tasks t ON t.id = s.task_id AND t.contest_id = p.contest_id
WHERE p.contest_id = $1::bigint AND s.official AND s.invalidated_at IS NULL AND NOT s.tester
ORDER BY s.submitted_at, s.id
`

type ListReplaySubmissionsRow struct {
	ID          int64     `json:"id"`
	SubmittedAt time.Time `json:"submitted_at"`
	Language    *string   `json:"language"`
	Username    string    `json:"username"`
	TaskNum     *int32    `json:"task_num"`
	TaskName    string    `json:"task_name"`
}

// A contest's official, valid submissions in arrival order, with who and
// which task (by its place in the contest): what a rehearsal replays
// (submissions_participation_task_idx through the contest's
// participations).
func (q *Queries) ListReplaySubmissions(ctx context.Context, contestID int64) ([]ListReplaySubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listReplaySubmissions, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReplaySubmissionsRow{}
	for rows.Next() {
		var i ListReplaySubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedAt,
			&i.Language,
			&i.Username,
			&i.TaskNum,
			&i.TaskName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replayLatencies = `-- name: ReplayLatencies :many
SELECT s.id, COALESCE(extract(epoch FROM sr.scored_at - s.submitted_at), -1)::float8 AS seconds, (sr.system_error IS NOT NULL)::boolean AS failed
FROM submissions s
JOIN tasks t ON t.id = s.task_id
LEFT JOIN submission_results sr ON sr.submission_id = s.id AND sr.dataset_id = t.active_dataset_id
WHERE s.id = ANY($1::bigint[])
`

type ReplayLatenciesRow struct {
	ID      int64   `json:"id"`
	Seconds float64 `json:"seconds"`
	Failed  bool    `json:"failed"`
}

// For replayed submissions: seconds from arrival to score on the live
// dataset (-1 while not scored).
func (q *Queries) ReplayLatencies(ctx context.Context, ids []int64) ([]ReplayLatenciesRow, error) {
	rows, err := q.db.Query(ctx, replayLatencies, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReplayLatenciesRow{}
	for rows.Next() {
		var i ReplayLatenciesRow
		if err := rows.Scan(&i.ID, &i.Seconds, &i.Failed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
