// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const getParticipationTaskScore = `-- name: GetParticipationTaskScore :one
SELECT participation_id, task_id, score, subtask_scores, icpc_solved, icpc_attempts, icpc_solved_at, pending, last_submission_at, updated_at FROM participation_task_scores WHERE participation_id = $1 AND task_id = $2
`

type GetParticipationTaskScoreParams struct {
	ParticipationID int64 `json:"participation_id"`
	TaskID          int64 `json:"task_id"`
}

func (q *Queries) GetParticipationTaskScore(ctx context.Context, arg GetParticipationTaskScoreParams) (ParticipationTaskScore, error) {
	row := q.db.QueryRow(ctx, getParticipationTaskScore, arg.ParticipationID, arg.TaskID)
	var i ParticipationTaskScore
	err := row.Scan(
		&i.ParticipationID,
		&i.TaskID,
		&i.Score,
		&i.SubtaskScores,
		&i.IcpcSolved,
		&i.IcpcAttempts,
		&i.IcpcSolvedAt,
		&i.Pending,
		&i.LastSubmissionAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParticipationTaskScoresByContest = `-- name: ListParticipationTaskScoresByContest :many
SELECT s.participation_id, s.task_id, s.score, s.subtask_scores, s.icpc_solved, s.icpc_attempts, s.icpc_solved_at, s.pending, s.last_submission_at, s.updated_at FROM participation_task_scores s
JOIN participations p ON p.id = s.participation_id
WHERE p.contest_id = $1
`

func (q *Queries) ListParticipationTaskScoresByContest(ctx context.Context, contestID int64) ([]ParticipationTaskScore, error) {
	rows, err := q.db.Query(ctx, listParticipationTaskScoresByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParticipationTaskScore{}
	for rows.Next() {
		var i ParticipationTaskScore
		if err := rows.Scan(
			&i.ParticipationID,
			&i.TaskID,
			&i.Score,
			&i.SubtaskScores,
			&i.IcpcSolved,
			&i.IcpcAttempts,
			&i.IcpcSolvedAt,
			&i.Pending,
			&i.LastSubmissionAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertParticipationTaskScore = `-- name: UpsertParticipationTaskScore :exec
INSERT INTO participation_task_scores (participation_id, task_id, score, subtask_scores, icpc_solved,
    icpc_attempts, icpc_solved_at, pending, last_submission_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (participation_id, task_id) DO UPDATE SET
    score = EXCLUDED.score, subtask_scores = EXCLUDED.subtask_scores, icpc_solved = EXCLUDED.icpc_solved,
    icpc_attempts = EXCLUDED.icpc_attempts, icpc_solved_at = EXCLUDED.icpc_solved_at,
    pending = EXCLUDED.pending, last_submission_at = EXCLUDED.last_submission_at, updated_at = now()
`

type UpsertParticipationTaskScoreParams struct {
	ParticipationID  int64           `json:"participation_id"`
	TaskID           int64           `json:"task_id"`
	Score            float64         `json:"score"`
	SubtaskScores    json.RawMessage `json:"subtask_scores"`
	IcpcSolved       bool            `json:"icpc_solved"`
	IcpcAttempts     int32           `json:"icpc_attempts"`
	IcpcSolvedAt     *time.Time      `json:"icpc_solved_at"`
	Pending          int32           `json:"pending"`
	LastSubmissionAt *time.Time      `json:"last_submission_at"`
}

func (q *Queries) UpsertParticipationTaskScore(ctx context.Context, arg UpsertParticipationTaskScoreParams) error {
	_, err := q.db.Exec(ctx, upsertParticipationTaskScore,
		arg.ParticipationID,
		arg.TaskID,
		arg.Score,
		arg.SubtaskScores,
		arg.IcpcSolved,
		arg.IcpcAttempts,
		arg.IcpcSolvedAt,
		arg.Pending,
		arg.LastSubmissionAt,
	)
	return err
}
