// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
	"time"
)

const getServerSettings = `-- name: GetServerSettings :one
SELECT timezone, updated_at FROM server_settings WHERE id
`

type GetServerSettingsRow struct {
	Timezone  string    `json:"timezone"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetServerSettings(ctx context.Context) (GetServerSettingsRow, error) {
	row := q.db.QueryRow(ctx, getServerSettings)
	var i GetServerSettingsRow
	err := row.Scan(&i.Timezone, &i.UpdatedAt)
	return i, err
}

const setServerTimezone = `-- name: SetServerTimezone :exec
UPDATE server_settings SET timezone = $1, updated_at = now() WHERE id
`

func (q *Queries) SetServerTimezone(ctx context.Context, timezone string) error {
	_, err := q.db.Exec(ctx, setServerTimezone, timezone)
	return err
}

const syncContestsTimezone = `-- name: SyncContestsTimezone :many
UPDATE contests SET timezone = $1 WHERE timezone <> $1 RETURNING id
`

// The contests follow the new zone (after SetServerTimezone, in the same
// transaction: the trigger copies the server's zone); their ids tell the
// web servers which caches to drop.
func (q *Queries) SyncContestsTimezone(ctx context.Context, timezone string) ([]int64, error) {
	rows, err := q.db.Query(ctx, syncContestsTimezone, timezone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
