// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (participation_id, task_id, submitted_at, language, comment, official)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, participation_id, task_id, submitted_at, language, comment, official, tester, tester_admin_id, invalidated_at, invalidated_reason, invalidated_by
`

type CreateSubmissionParams struct {
	ParticipationID *int64    `json:"participation_id"`
	TaskID          int64     `json:"task_id"`
	SubmittedAt     time.Time `json:"submitted_at"`
	Language        *string   `json:"language"`
	Comment         string    `json:"comment"`
	Official        bool      `json:"official"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ParticipationID,
		arg.TaskID,
		arg.SubmittedAt,
		arg.Language,
		arg.Comment,
		arg.Official,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.SubmittedAt,
		&i.Language,
		&i.Comment,
		&i.Official,
		&i.Tester,
		&i.TesterAdminID,
		&i.InvalidatedAt,
		&i.InvalidatedReason,
		&i.InvalidatedBy,
	)
	return i, err
}

type CreateSubmissionFilesParams struct {
	SubmissionID int64  `json:"submission_id"`
	Filename     string `json:"filename"`
	Digest       string `json:"digest"`
}

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (submission_id, played_at) VALUES ($1, $2) RETURNING id, submission_id, played_at
`

type CreateTokenParams struct {
	SubmissionID int64     `json:"submission_id"`
	PlayedAt     time.Time `json:"played_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken, arg.SubmissionID, arg.PlayedAt)
	var i Token
	err := row.Scan(&i.ID, &i.SubmissionID, &i.PlayedAt)
	return i, err
}

const deleteEvaluations = `-- name: DeleteEvaluations :exec
DELETE FROM evaluations WHERE submission_id = $1 AND dataset_id = $2
`

type DeleteEvaluationsParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

func (q *Queries) DeleteEvaluations(ctx context.Context, arg DeleteEvaluationsParams) error {
	_, err := q.db.Exec(ctx, deleteEvaluations, arg.SubmissionID, arg.DatasetID)
	return err
}

const deleteExecutables = `-- name: DeleteExecutables :exec
DELETE FROM executables WHERE submission_id = $1 AND dataset_id = $2
`

type DeleteExecutablesParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

func (q *Queries) DeleteExecutables(ctx context.Context, arg DeleteExecutablesParams) error {
	_, err := q.db.Exec(ctx, deleteExecutables, arg.SubmissionID, arg.DatasetID)
	return err
}

const deleteSubmission = `-- name: DeleteSubmission :exec
DELETE FROM submissions WHERE id = $1
`

func (q *Queries) DeleteSubmission(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSubmission, id)
	return err
}

const ensureSubmissionResult = `-- name: EnsureSubmissionResult :exec
INSERT INTO submission_results (submission_id, dataset_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type EnsureSubmissionResultParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

func (q *Queries) EnsureSubmissionResult(ctx context.Context, arg EnsureSubmissionResultParams) error {
	_, err := q.db.Exec(ctx, ensureSubmissionResult, arg.SubmissionID, arg.DatasetID)
	return err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, participation_id, task_id, submitted_at, language, comment, official, tester, tester_admin_id, invalidated_at, invalidated_reason, invalidated_by FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmission(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.SubmittedAt,
		&i.Language,
		&i.Comment,
		&i.Official,
		&i.Tester,
		&i.TesterAdminID,
		&i.InvalidatedAt,
		&i.InvalidatedReason,
		&i.InvalidatedBy,
	)
	return i, err
}

const getSubmissionResult = `-- name: GetSubmissionResult :one
SELECT submission_id, dataset_id, generation, compilation_outcome, compilation_text, compilation_stdout, compilation_stderr, compilation_tries, compilation_time, compilation_wall_time, compilation_memory, compilation_worker, evaluation_outcome, evaluation_tries, testcases_total, testcases_done, score, score_details, public_score, public_score_details, ranking_score_details, scored_at, system_error, created_at, jobs_enqueued_at FROM submission_results WHERE submission_id = $1 AND dataset_id = $2
`

type GetSubmissionResultParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

func (q *Queries) GetSubmissionResult(ctx context.Context, arg GetSubmissionResultParams) (SubmissionResult, error) {
	row := q.db.QueryRow(ctx, getSubmissionResult, arg.SubmissionID, arg.DatasetID)
	var i SubmissionResult
	err := row.Scan(
		&i.SubmissionID,
		&i.DatasetID,
		&i.Generation,
		&i.CompilationOutcome,
		&i.CompilationText,
		&i.CompilationStdout,
		&i.CompilationStderr,
		&i.CompilationTries,
		&i.CompilationTime,
		&i.CompilationWallTime,
		&i.CompilationMemory,
		&i.CompilationWorker,
		&i.EvaluationOutcome,
		&i.EvaluationTries,
		&i.TestcasesTotal,
		&i.TestcasesDone,
		&i.Score,
		&i.ScoreDetails,
		&i.PublicScore,
		&i.PublicScoreDetails,
		&i.RankingScoreDetails,
		&i.ScoredAt,
		&i.SystemError,
		&i.CreatedAt,
		&i.JobsEnqueuedAt,
	)
	return i, err
}

const getToken = `-- name: GetToken :one
SELECT id, submission_id, played_at FROM tokens WHERE submission_id = $1
`

func (q *Queries) GetToken(ctx context.Context, submissionID int64) (Token, error) {
	row := q.db.QueryRow(ctx, getToken, submissionID)
	var i Token
	err := row.Scan(&i.ID, &i.SubmissionID, &i.PlayedAt)
	return i, err
}

const insertExecutable = `-- name: InsertExecutable :exec
INSERT INTO executables (submission_id, dataset_id, filename, digest) VALUES ($1, $2, $3, $4)
ON CONFLICT (submission_id, dataset_id, filename) DO UPDATE SET digest = EXCLUDED.digest
`

type InsertExecutableParams struct {
	SubmissionID int64  `json:"submission_id"`
	DatasetID    int64  `json:"dataset_id"`
	Filename     string `json:"filename"`
	Digest       string `json:"digest"`
}

func (q *Queries) InsertExecutable(ctx context.Context, arg InsertExecutableParams) error {
	_, err := q.db.Exec(ctx, insertExecutable,
		arg.SubmissionID,
		arg.DatasetID,
		arg.Filename,
		arg.Digest,
	)
	return err
}

const invalidateSubmissionResult = `-- name: InvalidateSubmissionResult :one
UPDATE submission_results SET
    generation = generation + CASE WHEN $3::text = 'score' THEN 0 ELSE 1 END,
    compilation_outcome = CASE WHEN $3::text = 'compilation' THEN NULL ELSE compilation_outcome END,
    compilation_text = CASE WHEN $3::text = 'compilation' THEN '' ELSE compilation_text END,
    compilation_stdout = CASE WHEN $3::text = 'compilation' THEN '' ELSE compilation_stdout END,
    compilation_stderr = CASE WHEN $3::text = 'compilation' THEN '' ELSE compilation_stderr END,
    compilation_tries = CASE WHEN $3::text = 'compilation' THEN 0 ELSE compilation_tries END,
    evaluation_outcome = CASE WHEN $3::text = 'score' THEN evaluation_outcome ELSE NULL END,
    evaluation_tries = CASE WHEN $3::text = 'score' THEN evaluation_tries ELSE 0 END,
    testcases_done = CASE WHEN $3::text = 'score' THEN testcases_done ELSE 0 END,
    score = NULL, score_details = NULL, public_score = NULL, public_score_details = NULL,
    ranking_score_details = NULL, scored_at = NULL, system_error = NULL, jobs_enqueued_at = NULL
WHERE submission_id = $1 AND dataset_id = $2
RETURNING generation
`

type InvalidateSubmissionResultParams struct {
	SubmissionID int64  `json:"submission_id"`
	DatasetID    int64  `json:"dataset_id"`
	Level        string `json:"level"`
}

// level: 'compilation' drops everything; 'evaluation' keeps the executables;
// 'score' only clears the score. Returns the new generation.
func (q *Queries) InvalidateSubmissionResult(ctx context.Context, arg InvalidateSubmissionResultParams) (int32, error) {
	row := q.db.QueryRow(ctx, invalidateSubmissionResult, arg.SubmissionID, arg.DatasetID, arg.Level)
	var generation int32
	err := row.Scan(&generation)
	return generation, err
}

const listEvaluations = `-- name: ListEvaluations :many
SELECT submission_id, dataset_id, testcase_id, outcome, text, execution_time, execution_wall_time, execution_memory, exit_status, exit_code, signal, worker, created_at FROM evaluations WHERE submission_id = $1 AND dataset_id = $2
`

type ListEvaluationsParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

func (q *Queries) ListEvaluations(ctx context.Context, arg ListEvaluationsParams) ([]Evaluation, error) {
	rows, err := q.db.Query(ctx, listEvaluations, arg.SubmissionID, arg.DatasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Evaluation{}
	for rows.Next() {
		var i Evaluation
		if err := rows.Scan(
			&i.SubmissionID,
			&i.DatasetID,
			&i.TestcaseID,
			&i.Outcome,
			&i.Text,
			&i.ExecutionTime,
			&i.ExecutionWallTime,
			&i.ExecutionMemory,
			&i.ExitStatus,
			&i.ExitCode,
			&i.Signal,
			&i.Worker,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationsWithTestcase = `-- name: ListEvaluationsWithTestcase :many
SELECT e.submission_id, e.dataset_id, e.testcase_id, e.outcome, e.text, e.execution_time, e.execution_wall_time, e.execution_memory, e.exit_status, e.exit_code, e.signal, e.worker, e.created_at, t.codename, t.public
FROM evaluations e JOIN testcases t ON t.id = e.testcase_id
WHERE e.submission_id = $1 AND e.dataset_id = $2
ORDER BY t.codename
`

type ListEvaluationsWithTestcaseParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

type ListEvaluationsWithTestcaseRow struct {
	SubmissionID      int64     `json:"submission_id"`
	DatasetID         int64     `json:"dataset_id"`
	TestcaseID        int64     `json:"testcase_id"`
	Outcome           float64   `json:"outcome"`
	Text              string    `json:"text"`
	ExecutionTime     *float64  `json:"execution_time"`
	ExecutionWallTime *float64  `json:"execution_wall_time"`
	ExecutionMemory   *int64    `json:"execution_memory"`
	ExitStatus        string    `json:"exit_status"`
	ExitCode          *int32    `json:"exit_code"`
	Signal            *int32    `json:"signal"`
	Worker            *string   `json:"worker"`
	CreatedAt         time.Time `json:"created_at"`
	Codename          string    `json:"codename"`
	Public            bool      `json:"public"`
}

func (q *Queries) ListEvaluationsWithTestcase(ctx context.Context, arg ListEvaluationsWithTestcaseParams) ([]ListEvaluationsWithTestcaseRow, error) {
	rows, err := q.db.Query(ctx, listEvaluationsWithTestcase, arg.SubmissionID, arg.DatasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEvaluationsWithTestcaseRow{}
	for rows.Next() {
		var i ListEvaluationsWithTestcaseRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.DatasetID,
			&i.TestcaseID,
			&i.Outcome,
			&i.Text,
			&i.ExecutionTime,
			&i.ExecutionWallTime,
			&i.ExecutionMemory,
			&i.ExitStatus,
			&i.ExitCode,
			&i.Signal,
			&i.Worker,
			&i.CreatedAt,
			&i.Codename,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutables = `-- name: ListExecutables :many
SELECT id, submission_id, dataset_id, filename, digest FROM executables WHERE submission_id = $1 AND dataset_id = $2 ORDER BY filename
`

type ListExecutablesParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

func (q *Queries) ListExecutables(ctx context.Context, arg ListExecutablesParams) ([]Executable, error) {
	rows, err := q.db.Query(ctx, listExecutables, arg.SubmissionID, arg.DatasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Executable{}
	for rows.Next() {
		var i Executable
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.DatasetID,
			&i.Filename,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSubmissionResults = `-- name: ListPendingSubmissionResults :many
SELECT sr.submission_id, sr.dataset_id, sr.generation, sr.compilation_outcome, sr.evaluation_outcome,
       sr.compilation_tries, sr.evaluation_tries, sr.system_error
FROM submission_results sr
WHERE sr.scored_at IS NULL
ORDER BY sr.submission_id
LIMIT $1
`

type ListPendingSubmissionResultsRow struct {
	SubmissionID       int64   `json:"submission_id"`
	DatasetID          int64   `json:"dataset_id"`
	Generation         int32   `json:"generation"`
	CompilationOutcome *string `json:"compilation_outcome"`
	EvaluationOutcome  *string `json:"evaluation_outcome"`
	CompilationTries   int32   `json:"compilation_tries"`
	EvaluationTries    int32   `json:"evaluation_tries"`
	SystemError        *string `json:"system_error"`
}

// Sweeper: results not yet scored, oldest first.
func (q *Queries) ListPendingSubmissionResults(ctx context.Context, limit int32) ([]ListPendingSubmissionResultsRow, error) {
	rows, err := q.db.Query(ctx, listPendingSubmissionResults, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingSubmissionResultsRow{}
	for rows.Next() {
		var i ListPendingSubmissionResultsRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.DatasetID,
			&i.Generation,
			&i.CompilationOutcome,
			&i.EvaluationOutcome,
			&i.CompilationTries,
			&i.EvaluationTries,
			&i.SystemError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionFiles = `-- name: ListSubmissionFiles :many
SELECT id, submission_id, filename, digest FROM submission_files WHERE submission_id = $1 ORDER BY filename
`

func (q *Queries) ListSubmissionFiles(ctx context.Context, submissionID int64) ([]SubmissionFile, error) {
	rows, err := q.db.Query(ctx, listSubmissionFiles, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubmissionFile{}
	for rows.Next() {
		var i SubmissionFile
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.Filename,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionFilesBySubmissions = `-- name: ListSubmissionFilesBySubmissions :many
SELECT id, submission_id, filename, digest FROM submission_files WHERE submission_id = ANY($1::bigint[]) ORDER BY submission_id, filename
`

func (q *Queries) ListSubmissionFilesBySubmissions(ctx context.Context, ids []int64) ([]SubmissionFile, error) {
	rows, err := q.db.Query(ctx, listSubmissionFilesBySubmissions, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubmissionFile{}
	for rows.Next() {
		var i SubmissionFile
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.Filename,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionResultsBySubmissions = `-- name: ListSubmissionResultsBySubmissions :many
SELECT submission_id, dataset_id, generation, compilation_outcome, compilation_text, compilation_stdout, compilation_stderr, compilation_tries, compilation_time, compilation_wall_time, compilation_memory, compilation_worker, evaluation_outcome, evaluation_tries, testcases_total, testcases_done, score, score_details, public_score, public_score_details, ranking_score_details, scored_at, system_error, created_at, jobs_enqueued_at FROM submission_results WHERE submission_id = ANY($1::bigint[]) AND dataset_id = ANY($2::bigint[])
`

type ListSubmissionResultsBySubmissionsParams struct {
	Ids        []int64 `json:"ids"`
	DatasetIds []int64 `json:"dataset_ids"`
}

func (q *Queries) ListSubmissionResultsBySubmissions(ctx context.Context, arg ListSubmissionResultsBySubmissionsParams) ([]SubmissionResult, error) {
	rows, err := q.db.Query(ctx, listSubmissionResultsBySubmissions, arg.Ids, arg.DatasetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubmissionResult{}
	for rows.Next() {
		var i SubmissionResult
		if err := rows.Scan(
			&i.SubmissionID,
			&i.DatasetID,
			&i.Generation,
			&i.CompilationOutcome,
			&i.CompilationText,
			&i.CompilationStdout,
			&i.CompilationStderr,
			&i.CompilationTries,
			&i.CompilationTime,
			&i.CompilationWallTime,
			&i.CompilationMemory,
			&i.CompilationWorker,
			&i.EvaluationOutcome,
			&i.EvaluationTries,
			&i.TestcasesTotal,
			&i.TestcasesDone,
			&i.Score,
			&i.ScoreDetails,
			&i.PublicScore,
			&i.PublicScoreDetails,
			&i.RankingScoreDetails,
			&i.ScoredAt,
			&i.SystemError,
			&i.CreatedAt,
			&i.JobsEnqueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByParticipation = `-- name: ListSubmissionsByParticipation :many
SELECT id, participation_id, task_id, submitted_at, language, comment, official, tester, tester_admin_id, invalidated_at, invalidated_reason, invalidated_by FROM submissions WHERE participation_id = $1::bigint ORDER BY submitted_at, id
`

func (q *Queries) ListSubmissionsByParticipation(ctx context.Context, participationID int64) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.TaskID,
			&i.SubmittedAt,
			&i.Language,
			&i.Comment,
			&i.Official,
			&i.Tester,
			&i.TesterAdminID,
			&i.InvalidatedAt,
			&i.InvalidatedReason,
			&i.InvalidatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByParticipationTask = `-- name: ListSubmissionsByParticipationTask :many
SELECT id, participation_id, task_id, submitted_at, language, comment, official, tester, tester_admin_id, invalidated_at, invalidated_reason, invalidated_by FROM submissions WHERE participation_id = $1::bigint AND task_id = $2::bigint ORDER BY submitted_at, id
`

type ListSubmissionsByParticipationTaskParams struct {
	ParticipationID int64 `json:"participation_id"`
	TaskID          int64 `json:"task_id"`
}

func (q *Queries) ListSubmissionsByParticipationTask(ctx context.Context, arg ListSubmissionsByParticipationTaskParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByParticipationTask, arg.ParticipationID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.TaskID,
			&i.SubmittedAt,
			&i.Language,
			&i.Comment,
			&i.Official,
			&i.Tester,
			&i.TesterAdminID,
			&i.InvalidatedAt,
			&i.InvalidatedReason,
			&i.InvalidatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenTimesByParticipation = `-- name: ListTokenTimesByParticipation :many
SELECT s.task_id, k.played_at, k.submission_id
FROM tokens k JOIN submissions s ON s.id = k.submission_id
WHERE s.participation_id = $1::bigint
ORDER BY k.played_at
`

type ListTokenTimesByParticipationRow struct {
	TaskID       int64     `json:"task_id"`
	PlayedAt     time.Time `json:"played_at"`
	SubmissionID int64     `json:"submission_id"`
}

// Token history of a participation: (task, time) pairs for token accounting.
func (q *Queries) ListTokenTimesByParticipation(ctx context.Context, participationID int64) ([]ListTokenTimesByParticipationRow, error) {
	rows, err := q.db.Query(ctx, listTokenTimesByParticipation, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenTimesByParticipationRow{}
	for rows.Next() {
		var i ListTokenTimesByParticipationRow
		if err := rows.Scan(&i.TaskID, &i.PlayedAt, &i.SubmissionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTestcasesDone = `-- name: RefreshTestcasesDone :one
UPDATE submission_results sr
SET testcases_done = (SELECT count(*) FROM evaluations e WHERE e.submission_id = sr.submission_id AND e.dataset_id = sr.dataset_id)
WHERE sr.submission_id = $1 AND sr.dataset_id = $2
RETURNING testcases_done, testcases_total
`

type RefreshTestcasesDoneParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
}

type RefreshTestcasesDoneRow struct {
	TestcasesDone  int32 `json:"testcases_done"`
	TestcasesTotal int32 `json:"testcases_total"`
}

func (q *Queries) RefreshTestcasesDone(ctx context.Context, arg RefreshTestcasesDoneParams) (RefreshTestcasesDoneRow, error) {
	row := q.db.QueryRow(ctx, refreshTestcasesDone, arg.SubmissionID, arg.DatasetID)
	var i RefreshTestcasesDoneRow
	err := row.Scan(&i.TestcasesDone, &i.TestcasesTotal)
	return i, err
}

const setCompilationResult = `-- name: SetCompilationResult :one
UPDATE submission_results SET
    compilation_outcome = $3, compilation_text = $4, compilation_stdout = $5,
    compilation_stderr = $6, compilation_tries = compilation_tries + 1, compilation_time = $7,
    compilation_wall_time = $8, compilation_memory = $9, compilation_worker = $10,
    testcases_total = $11
WHERE submission_id = $1 AND dataset_id = $2 AND generation = $12::integer
RETURNING submission_id
`

type SetCompilationResultParams struct {
	SubmissionID        int64    `json:"submission_id"`
	DatasetID           int64    `json:"dataset_id"`
	CompilationOutcome  *string  `json:"compilation_outcome"`
	CompilationText     string   `json:"compilation_text"`
	CompilationStdout   string   `json:"compilation_stdout"`
	CompilationStderr   string   `json:"compilation_stderr"`
	CompilationTime     *float64 `json:"compilation_time"`
	CompilationWallTime *float64 `json:"compilation_wall_time"`
	CompilationMemory   *int64   `json:"compilation_memory"`
	CompilationWorker   *string  `json:"compilation_worker"`
	TestcasesTotal      int32    `json:"testcases_total"`
	Generation          int32    `json:"generation"`
}

// Stores a compilation outcome unless the result was invalidated meanwhile
// (generation mismatch); returns the number of updated rows.
func (q *Queries) SetCompilationResult(ctx context.Context, arg SetCompilationResultParams) (int64, error) {
	row := q.db.QueryRow(ctx, setCompilationResult,
		arg.SubmissionID,
		arg.DatasetID,
		arg.CompilationOutcome,
		arg.CompilationText,
		arg.CompilationStdout,
		arg.CompilationStderr,
		arg.CompilationTime,
		arg.CompilationWallTime,
		arg.CompilationMemory,
		arg.CompilationWorker,
		arg.TestcasesTotal,
		arg.Generation,
	)
	var submission_id int64
	err := row.Scan(&submission_id)
	return submission_id, err
}

const setEvaluationDone = `-- name: SetEvaluationDone :exec
UPDATE submission_results SET evaluation_outcome = 'ok', evaluation_tries = evaluation_tries + 1
WHERE submission_id = $1 AND dataset_id = $2 AND generation = $3::integer
`

type SetEvaluationDoneParams struct {
	SubmissionID int64 `json:"submission_id"`
	DatasetID    int64 `json:"dataset_id"`
	Generation   int32 `json:"generation"`
}

func (q *Queries) SetEvaluationDone(ctx context.Context, arg SetEvaluationDoneParams) error {
	_, err := q.db.Exec(ctx, setEvaluationDone, arg.SubmissionID, arg.DatasetID, arg.Generation)
	return err
}

const setScore = `-- name: SetScore :exec
UPDATE submission_results SET score = $3, score_details = $4, public_score = $5,
    public_score_details = $6, ranking_score_details = $7, scored_at = now()
WHERE submission_id = $1 AND dataset_id = $2
`

type SetScoreParams struct {
	SubmissionID        int64           `json:"submission_id"`
	DatasetID           int64           `json:"dataset_id"`
	Score               *float64        `json:"score"`
	ScoreDetails        json.RawMessage `json:"score_details"`
	PublicScore         *float64        `json:"public_score"`
	PublicScoreDetails  json.RawMessage `json:"public_score_details"`
	RankingScoreDetails json.RawMessage `json:"ranking_score_details"`
}

func (q *Queries) SetScore(ctx context.Context, arg SetScoreParams) error {
	_, err := q.db.Exec(ctx, setScore,
		arg.SubmissionID,
		arg.DatasetID,
		arg.Score,
		arg.ScoreDetails,
		arg.PublicScore,
		arg.PublicScoreDetails,
		arg.RankingScoreDetails,
	)
	return err
}

const setSubmissionSystemError = `-- name: SetSubmissionSystemError :exec
UPDATE submission_results SET system_error = $3 WHERE submission_id = $1 AND dataset_id = $2
`

type SetSubmissionSystemErrorParams struct {
	SubmissionID int64   `json:"submission_id"`
	DatasetID    int64   `json:"dataset_id"`
	SystemError  *string `json:"system_error"`
}

func (q *Queries) SetSubmissionSystemError(ctx context.Context, arg SetSubmissionSystemErrorParams) error {
	_, err := q.db.Exec(ctx, setSubmissionSystemError, arg.SubmissionID, arg.DatasetID, arg.SystemError)
	return err
}

const submissionStats = `-- name: SubmissionStats :one
SELECT count(*)::bigint AS contest_count,
       (count(*) FILTER (WHERE task_id = $1::bigint))::bigint AS task_count,
       COALESCE(max(submitted_at), 'epoch')::timestamptz AS contest_last,
       COALESCE(max(submitted_at) FILTER (WHERE task_id = $1::bigint), 'epoch')::timestamptz AS task_last
FROM submissions WHERE participation_id = $2::bigint AND official
`

type SubmissionStatsParams struct {
	TaskID          int64 `json:"task_id"`
	ParticipationID int64 `json:"participation_id"`
}

type SubmissionStatsRow struct {
	ContestCount int64     `json:"contest_count"`
	TaskCount    int64     `json:"task_count"`
	ContestLast  time.Time `json:"contest_last"`
	TaskLast     time.Time `json:"task_last"`
}

// Counts and last submission time used to enforce the contest-wide and
// per-task limits in a single index scan.
func (q *Queries) SubmissionStats(ctx context.Context, arg SubmissionStatsParams) (SubmissionStatsRow, error) {
	row := q.db.QueryRow(ctx, submissionStats, arg.TaskID, arg.ParticipationID)
	var i SubmissionStatsRow
	err := row.Scan(
		&i.ContestCount,
		&i.TaskCount,
		&i.ContestLast,
		&i.TaskLast,
	)
	return i, err
}

const upsertEvaluation = `-- name: UpsertEvaluation :exec
INSERT INTO evaluations (submission_id, dataset_id, testcase_id, outcome, text, execution_time,
    execution_wall_time, execution_memory, exit_status, exit_code, signal, worker)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (submission_id, dataset_id, testcase_id) DO UPDATE SET
    outcome = EXCLUDED.outcome, text = EXCLUDED.text, execution_time = EXCLUDED.execution_time,
    execution_wall_time = EXCLUDED.execution_wall_time, execution_memory = EXCLUDED.execution_memory,
    exit_status = EXCLUDED.exit_status, exit_code = EXCLUDED.exit_code, signal = EXCLUDED.signal,
    worker = EXCLUDED.worker, created_at = now()
`

type UpsertEvaluationParams struct {
	SubmissionID      int64    `json:"submission_id"`
	DatasetID         int64    `json:"dataset_id"`
	TestcaseID        int64    `json:"testcase_id"`
	Outcome           float64  `json:"outcome"`
	Text              string   `json:"text"`
	ExecutionTime     *float64 `json:"execution_time"`
	ExecutionWallTime *float64 `json:"execution_wall_time"`
	ExecutionMemory   *int64   `json:"execution_memory"`
	ExitStatus        string   `json:"exit_status"`
	ExitCode          *int32   `json:"exit_code"`
	Signal            *int32   `json:"signal"`
	Worker            *string  `json:"worker"`
}

func (q *Queries) UpsertEvaluation(ctx context.Context, arg UpsertEvaluationParams) error {
	_, err := q.db.Exec(ctx, upsertEvaluation,
		arg.SubmissionID,
		arg.DatasetID,
		arg.TestcaseID,
		arg.Outcome,
		arg.Text,
		arg.ExecutionTime,
		arg.ExecutionWallTime,
		arg.ExecutionMemory,
		arg.ExitStatus,
		arg.ExitCode,
		arg.Signal,
		arg.Worker,
	)
	return err
}
