// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    contest_id, num, name, title, primary_statements, submission_format,
    token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number,
    token_gen_interval_s, token_gen_max, max_submission_number, max_user_test_number,
    min_submission_interval_s, min_user_test_interval_s, feedback_level, score_precision, score_mode, languages
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
) RETURNING id, contest_id, num, name, title, primary_statements, submission_format, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, feedback_level, score_precision, score_mode, active_dataset_id, created_at, updated_at, languages
`

type CreateTaskParams struct {
	ContestID              *int64   `json:"contest_id"`
	Num                    *int32   `json:"num"`
	Name                   string   `json:"name"`
	Title                  string   `json:"title"`
	PrimaryStatements      []string `json:"primary_statements"`
	SubmissionFormat       []string `json:"submission_format"`
	TokenMode              string   `json:"token_mode"`
	TokenMaxNumber         *int32   `json:"token_max_number"`
	TokenMinIntervalS      int64    `json:"token_min_interval_s"`
	TokenGenInitial        int32    `json:"token_gen_initial"`
	TokenGenNumber         int32    `json:"token_gen_number"`
	TokenGenIntervalS      int64    `json:"token_gen_interval_s"`
	TokenGenMax            *int32   `json:"token_gen_max"`
	MaxSubmissionNumber    *int32   `json:"max_submission_number"`
	MaxUserTestNumber      *int32   `json:"max_user_test_number"`
	MinSubmissionIntervalS *int64   `json:"min_submission_interval_s"`
	MinUserTestIntervalS   *int64   `json:"min_user_test_interval_s"`
	FeedbackLevel          string   `json:"feedback_level"`
	ScorePrecision         int32    `json:"score_precision"`
	ScoreMode              string   `json:"score_mode"`
	Languages              []string `json:"languages"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ContestID,
		arg.Num,
		arg.Name,
		arg.Title,
		arg.PrimaryStatements,
		arg.SubmissionFormat,
		arg.TokenMode,
		arg.TokenMaxNumber,
		arg.TokenMinIntervalS,
		arg.TokenGenInitial,
		arg.TokenGenNumber,
		arg.TokenGenIntervalS,
		arg.TokenGenMax,
		arg.MaxSubmissionNumber,
		arg.MaxUserTestNumber,
		arg.MinSubmissionIntervalS,
		arg.MinUserTestIntervalS,
		arg.FeedbackLevel,
		arg.ScorePrecision,
		arg.ScoreMode,
		arg.Languages,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Num,
		&i.Name,
		&i.Title,
		&i.PrimaryStatements,
		&i.SubmissionFormat,
		&i.TokenMode,
		&i.TokenMaxNumber,
		&i.TokenMinIntervalS,
		&i.TokenGenInitial,
		&i.TokenGenNumber,
		&i.TokenGenIntervalS,
		&i.TokenGenMax,
		&i.MaxSubmissionNumber,
		&i.MaxUserTestNumber,
		&i.MinSubmissionIntervalS,
		&i.MinUserTestIntervalS,
		&i.FeedbackLevel,
		&i.ScorePrecision,
		&i.ScoreMode,
		&i.ActiveDatasetID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Languages,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE task_id = $1 AND filename = $2
`

type DeleteAttachmentParams struct {
	TaskID   int64  `json:"task_id"`
	Filename string `json:"filename"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteAttachment, arg.TaskID, arg.Filename)
	return err
}

const deleteStatement = `-- name: DeleteStatement :exec
DELETE FROM statements WHERE task_id = $1 AND language = $2
`

type DeleteStatementParams struct {
	TaskID   int64  `json:"task_id"`
	Language string `json:"language"`
}

func (q *Queries) DeleteStatement(ctx context.Context, arg DeleteStatementParams) error {
	_, err := q.db.Exec(ctx, deleteStatement, arg.TaskID, arg.Language)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const deleteTaskExample = `-- name: DeleteTaskExample :exec
DELETE FROM task_examples WHERE id = $1 AND task_id = $2
`

type DeleteTaskExampleParams struct {
	ID     int64 `json:"id"`
	TaskID int64 `json:"task_id"`
}

func (q *Queries) DeleteTaskExample(ctx context.Context, arg DeleteTaskExampleParams) error {
	_, err := q.db.Exec(ctx, deleteTaskExample, arg.ID, arg.TaskID)
	return err
}

const deleteTaskExamples = `-- name: DeleteTaskExamples :exec
DELETE FROM task_examples WHERE task_id = $1
`

func (q *Queries) DeleteTaskExamples(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, deleteTaskExamples, taskID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, contest_id, num, name, title, primary_statements, submission_format, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, feedback_level, score_precision, score_mode, active_dataset_id, created_at, updated_at, languages FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Num,
		&i.Name,
		&i.Title,
		&i.PrimaryStatements,
		&i.SubmissionFormat,
		&i.TokenMode,
		&i.TokenMaxNumber,
		&i.TokenMinIntervalS,
		&i.TokenGenInitial,
		&i.TokenGenNumber,
		&i.TokenGenIntervalS,
		&i.TokenGenMax,
		&i.MaxSubmissionNumber,
		&i.MaxUserTestNumber,
		&i.MinSubmissionIntervalS,
		&i.MinUserTestIntervalS,
		&i.FeedbackLevel,
		&i.ScorePrecision,
		&i.ScoreMode,
		&i.ActiveDatasetID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Languages,
	)
	return i, err
}

const getTaskByName = `-- name: GetTaskByName :one
SELECT id, contest_id, num, name, title, primary_statements, submission_format, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, feedback_level, score_precision, score_mode, active_dataset_id, created_at, updated_at, languages FROM tasks WHERE name = $1
`

func (q *Queries) GetTaskByName(ctx context.Context, name string) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByName, name)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Num,
		&i.Name,
		&i.Title,
		&i.PrimaryStatements,
		&i.SubmissionFormat,
		&i.TokenMode,
		&i.TokenMaxNumber,
		&i.TokenMinIntervalS,
		&i.TokenGenInitial,
		&i.TokenGenNumber,
		&i.TokenGenIntervalS,
		&i.TokenGenMax,
		&i.MaxSubmissionNumber,
		&i.MaxUserTestNumber,
		&i.MinSubmissionIntervalS,
		&i.MinUserTestIntervalS,
		&i.FeedbackLevel,
		&i.ScorePrecision,
		&i.ScoreMode,
		&i.ActiveDatasetID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Languages,
	)
	return i, err
}

const insertTaskExample = `-- name: InsertTaskExample :one
INSERT INTO task_examples (task_id, position, input_digest, output_digest, note)
VALUES ($1, COALESCE((SELECT max(position) + 1 FROM task_examples WHERE task_id = $1), 1), $2, $3, $4)
RETURNING id, task_id, position, input_digest, output_digest, note
`

type InsertTaskExampleParams struct {
	TaskID       int64  `json:"task_id"`
	InputDigest  string `json:"input_digest"`
	OutputDigest string `json:"output_digest"`
	Note         string `json:"note"`
}

func (q *Queries) InsertTaskExample(ctx context.Context, arg InsertTaskExampleParams) (TaskExample, error) {
	row := q.db.QueryRow(ctx, insertTaskExample,
		arg.TaskID,
		arg.InputDigest,
		arg.OutputDigest,
		arg.Note,
	)
	var i TaskExample
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Position,
		&i.InputDigest,
		&i.OutputDigest,
		&i.Note,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, task_id, filename, digest FROM attachments WHERE task_id = $1 ORDER BY filename
`

func (q *Queries) ListAttachments(ctx context.Context, taskID int64) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Filename,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByContest = `-- name: ListAttachmentsByContest :many
SELECT a.id, a.task_id, a.filename, a.digest FROM attachments a JOIN tasks t ON t.id = a.task_id WHERE t.contest_id = $1 ORDER BY a.task_id, a.filename
`

func (q *Queries) ListAttachmentsByContest(ctx context.Context, contestID *int64) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Filename,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatements = `-- name: ListStatements :many
SELECT id, task_id, language, digest, content_type FROM statements WHERE task_id = $1 ORDER BY language
`

func (q *Queries) ListStatements(ctx context.Context, taskID int64) ([]Statement, error) {
	rows, err := q.db.Query(ctx, listStatements, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Statement{}
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Language,
			&i.Digest,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatementsByContest = `-- name: ListStatementsByContest :many
SELECT s.id, s.task_id, s.language, s.digest, s.content_type FROM statements s JOIN tasks t ON t.id = s.task_id WHERE t.contest_id = $1 ORDER BY s.task_id, s.language
`

func (q *Queries) ListStatementsByContest(ctx context.Context, contestID *int64) ([]Statement, error) {
	rows, err := q.db.Query(ctx, listStatementsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Statement{}
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Language,
			&i.Digest,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExamples = `-- name: ListTaskExamples :many
SELECT id, task_id, position, input_digest, output_digest, note FROM task_examples WHERE task_id = $1 ORDER BY position, id
`

func (q *Queries) ListTaskExamples(ctx context.Context, taskID int64) ([]TaskExample, error) {
	rows, err := q.db.Query(ctx, listTaskExamples, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExample{}
	for rows.Next() {
		var i TaskExample
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Position,
			&i.InputDigest,
			&i.OutputDigest,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExamplesByContest = `-- name: ListTaskExamplesByContest :many
SELECT e.id, e.task_id, e.position, e.input_digest, e.output_digest, e.note FROM task_examples e JOIN tasks t ON t.id = e.task_id WHERE t.contest_id = $1 ORDER BY e.task_id, e.position, e.id
`

func (q *Queries) ListTaskExamplesByContest(ctx context.Context, contestID *int64) ([]TaskExample, error) {
	rows, err := q.db.Query(ctx, listTaskExamplesByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExample{}
	for rows.Next() {
		var i TaskExample
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Position,
			&i.InputDigest,
			&i.OutputDigest,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, contest_id, num, name, title, primary_statements, submission_format, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, feedback_level, score_precision, score_mode, active_dataset_id, created_at, updated_at, languages FROM tasks ORDER BY contest_id NULLS LAST, num, id
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.Num,
			&i.Name,
			&i.Title,
			&i.PrimaryStatements,
			&i.SubmissionFormat,
			&i.TokenMode,
			&i.TokenMaxNumber,
			&i.TokenMinIntervalS,
			&i.TokenGenInitial,
			&i.TokenGenNumber,
			&i.TokenGenIntervalS,
			&i.TokenGenMax,
			&i.MaxSubmissionNumber,
			&i.MaxUserTestNumber,
			&i.MinSubmissionIntervalS,
			&i.MinUserTestIntervalS,
			&i.FeedbackLevel,
			&i.ScorePrecision,
			&i.ScoreMode,
			&i.ActiveDatasetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Languages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByContest = `-- name: ListTasksByContest :many
SELECT id, contest_id, num, name, title, primary_statements, submission_format, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, feedback_level, score_precision, score_mode, active_dataset_id, created_at, updated_at, languages FROM tasks WHERE contest_id = $1 ORDER BY num, id
`

func (q *Queries) ListTasksByContest(ctx context.Context, contestID *int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.Num,
			&i.Name,
			&i.Title,
			&i.PrimaryStatements,
			&i.SubmissionFormat,
			&i.TokenMode,
			&i.TokenMaxNumber,
			&i.TokenMinIntervalS,
			&i.TokenGenInitial,
			&i.TokenGenNumber,
			&i.TokenGenIntervalS,
			&i.TokenGenMax,
			&i.MaxSubmissionNumber,
			&i.MaxUserTestNumber,
			&i.MinSubmissionIntervalS,
			&i.MinUserTestIntervalS,
			&i.FeedbackLevel,
			&i.ScorePrecision,
			&i.ScoreMode,
			&i.ActiveDatasetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Languages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveDataset = `-- name: SetActiveDataset :exec
UPDATE tasks SET active_dataset_id = $2, updated_at = now() WHERE id = $1
`

type SetActiveDatasetParams struct {
	ID              int64  `json:"id"`
	ActiveDatasetID *int64 `json:"active_dataset_id"`
}

func (q *Queries) SetActiveDataset(ctx context.Context, arg SetActiveDatasetParams) error {
	_, err := q.db.Exec(ctx, setActiveDataset, arg.ID, arg.ActiveDatasetID)
	return err
}

const setTaskContest = `-- name: SetTaskContest :exec
UPDATE tasks SET contest_id = $2, num = $3, updated_at = now() WHERE id = $1
`

type SetTaskContestParams struct {
	ID        int64  `json:"id"`
	ContestID *int64 `json:"contest_id"`
	Num       *int32 `json:"num"`
}

func (q *Queries) SetTaskContest(ctx context.Context, arg SetTaskContestParams) error {
	_, err := q.db.Exec(ctx, setTaskContest, arg.ID, arg.ContestID, arg.Num)
	return err
}

const setTaskExamplePosition = `-- name: SetTaskExamplePosition :exec
UPDATE task_examples SET position = $3 WHERE id = $1 AND task_id = $2
`

type SetTaskExamplePositionParams struct {
	ID       int64 `json:"id"`
	TaskID   int64 `json:"task_id"`
	Position int32 `json:"position"`
}

func (q *Queries) SetTaskExamplePosition(ctx context.Context, arg SetTaskExamplePositionParams) error {
	_, err := q.db.Exec(ctx, setTaskExamplePosition, arg.ID, arg.TaskID, arg.Position)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    contest_id = $2, num = $3, name = $4, title = $5, primary_statements = $6,
    submission_format = $7, token_mode = $8, token_max_number = $9, token_min_interval_s = $10,
    token_gen_initial = $11, token_gen_number = $12, token_gen_interval_s = $13,
    token_gen_max = $14, max_submission_number = $15, max_user_test_number = $16,
    min_submission_interval_s = $17, min_user_test_interval_s = $18, feedback_level = $19,
    score_precision = $20, score_mode = $21, languages = $22, updated_at = now()
WHERE id = $1
RETURNING id, contest_id, num, name, title, primary_statements, submission_format, token_mode, token_max_number, token_min_interval_s, token_gen_initial, token_gen_number, token_gen_interval_s, token_gen_max, max_submission_number, max_user_test_number, min_submission_interval_s, min_user_test_interval_s, feedback_level, score_precision, score_mode, active_dataset_id, created_at, updated_at, languages
`

type UpdateTaskParams struct {
	ID                     int64    `json:"id"`
	ContestID              *int64   `json:"contest_id"`
	Num                    *int32   `json:"num"`
	Name                   string   `json:"name"`
	Title                  string   `json:"title"`
	PrimaryStatements      []string `json:"primary_statements"`
	SubmissionFormat       []string `json:"submission_format"`
	TokenMode              string   `json:"token_mode"`
	TokenMaxNumber         *int32   `json:"token_max_number"`
	TokenMinIntervalS      int64    `json:"token_min_interval_s"`
	TokenGenInitial        int32    `json:"token_gen_initial"`
	TokenGenNumber         int32    `json:"token_gen_number"`
	TokenGenIntervalS      int64    `json:"token_gen_interval_s"`
	TokenGenMax            *int32   `json:"token_gen_max"`
	MaxSubmissionNumber    *int32   `json:"max_submission_number"`
	MaxUserTestNumber      *int32   `json:"max_user_test_number"`
	MinSubmissionIntervalS *int64   `json:"min_submission_interval_s"`
	MinUserTestIntervalS   *int64   `json:"min_user_test_interval_s"`
	FeedbackLevel          string   `json:"feedback_level"`
	ScorePrecision         int32    `json:"score_precision"`
	ScoreMode              string   `json:"score_mode"`
	Languages              []string `json:"languages"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.ContestID,
		arg.Num,
		arg.Name,
		arg.Title,
		arg.PrimaryStatements,
		arg.SubmissionFormat,
		arg.TokenMode,
		arg.TokenMaxNumber,
		arg.TokenMinIntervalS,
		arg.TokenGenInitial,
		arg.TokenGenNumber,
		arg.TokenGenIntervalS,
		arg.TokenGenMax,
		arg.MaxSubmissionNumber,
		arg.MaxUserTestNumber,
		arg.MinSubmissionIntervalS,
		arg.MinUserTestIntervalS,
		arg.FeedbackLevel,
		arg.ScorePrecision,
		arg.ScoreMode,
		arg.Languages,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Num,
		&i.Name,
		&i.Title,
		&i.PrimaryStatements,
		&i.SubmissionFormat,
		&i.TokenMode,
		&i.TokenMaxNumber,
		&i.TokenMinIntervalS,
		&i.TokenGenInitial,
		&i.TokenGenNumber,
		&i.TokenGenIntervalS,
		&i.TokenGenMax,
		&i.MaxSubmissionNumber,
		&i.MaxUserTestNumber,
		&i.MinSubmissionIntervalS,
		&i.MinUserTestIntervalS,
		&i.FeedbackLevel,
		&i.ScorePrecision,
		&i.ScoreMode,
		&i.ActiveDatasetID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Languages,
	)
	return i, err
}

const updateTaskExample = `-- name: UpdateTaskExample :exec
UPDATE task_examples SET input_digest = $3, output_digest = $4, note = $5 WHERE id = $1 AND task_id = $2
`

type UpdateTaskExampleParams struct {
	ID           int64  `json:"id"`
	TaskID       int64  `json:"task_id"`
	InputDigest  string `json:"input_digest"`
	OutputDigest string `json:"output_digest"`
	Note         string `json:"note"`
}

func (q *Queries) UpdateTaskExample(ctx context.Context, arg UpdateTaskExampleParams) error {
	_, err := q.db.Exec(ctx, updateTaskExample,
		arg.ID,
		arg.TaskID,
		arg.InputDigest,
		arg.OutputDigest,
		arg.Note,
	)
	return err
}

const upsertAttachment = `-- name: UpsertAttachment :one
INSERT INTO attachments (task_id, filename, digest) VALUES ($1, $2, $3)
ON CONFLICT (task_id, filename) DO UPDATE SET digest = EXCLUDED.digest
RETURNING id, task_id, filename, digest
`

type UpsertAttachmentParams struct {
	TaskID   int64  `json:"task_id"`
	Filename string `json:"filename"`
	Digest   string `json:"digest"`
}

func (q *Queries) UpsertAttachment(ctx context.Context, arg UpsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, upsertAttachment, arg.TaskID, arg.Filename, arg.Digest)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Filename,
		&i.Digest,
	)
	return i, err
}

const upsertStatement = `-- name: UpsertStatement :one
INSERT INTO statements (task_id, language, digest, content_type) VALUES ($1, $2, $3, $4)
ON CONFLICT (task_id, language) DO UPDATE SET digest = EXCLUDED.digest, content_type = EXCLUDED.content_type
RETURNING id, task_id, language, digest, content_type
`

type UpsertStatementParams struct {
	TaskID      int64  `json:"task_id"`
	Language    string `json:"language"`
	Digest      string `json:"digest"`
	ContentType string `json:"content_type"`
}

func (q *Queries) UpsertStatement(ctx context.Context, arg UpsertStatementParams) (Statement, error) {
	row := q.db.QueryRow(ctx, upsertStatement,
		arg.TaskID,
		arg.Language,
		arg.Digest,
		arg.ContentType,
	)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Language,
		&i.Digest,
		&i.ContentType,
	)
	return i, err
}
