// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: testcase_jobs.sql

package sqlc

import (
	"context"
)

const countTestcaseJobsRunning = `-- name: CountTestcaseJobsRunning :one
SELECT count(*)::bigint FROM testcase_jobs WHERE dataset_id = $1 AND state IN ('input', 'output')
`

func (q *Queries) CountTestcaseJobsRunning(ctx context.Context, datasetID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTestcaseJobsRunning, datasetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTestcaseJob = `-- name: CreateTestcaseJob :one
INSERT INTO testcase_jobs (dataset_id, codename, public, admin_id, input_digest, output, solution_id, user_test_id, state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, dataset_id, codename, public, admin_id, input_digest, output, solution_id, user_test_id, state, error, created_at
`

type CreateTestcaseJobParams struct {
	DatasetID   int64   `json:"dataset_id"`
	Codename    string  `json:"codename"`
	Public      bool    `json:"public"`
	AdminID     *int64  `json:"admin_id"`
	InputDigest *string `json:"input_digest"`
	Output      string  `json:"output"`
	SolutionID  *int64  `json:"solution_id"`
	UserTestID  *int64  `json:"user_test_id"`
	State       string  `json:"state"`
}

func (q *Queries) CreateTestcaseJob(ctx context.Context, arg CreateTestcaseJobParams) (TestcaseJob, error) {
	row := q.db.QueryRow(ctx, createTestcaseJob,
		arg.DatasetID,
		arg.Codename,
		arg.Public,
		arg.AdminID,
		arg.InputDigest,
		arg.Output,
		arg.SolutionID,
		arg.UserTestID,
		arg.State,
	)
	var i TestcaseJob
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Codename,
		&i.Public,
		&i.AdminID,
		&i.InputDigest,
		&i.Output,
		&i.SolutionID,
		&i.UserTestID,
		&i.State,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFailedTestcaseJobs = `-- name: DeleteFailedTestcaseJobs :exec
DELETE FROM testcase_jobs WHERE dataset_id = $1 AND state = 'failed'
`

func (q *Queries) DeleteFailedTestcaseJobs(ctx context.Context, datasetID int64) error {
	_, err := q.db.Exec(ctx, deleteFailedTestcaseJobs, datasetID)
	return err
}

const deleteTestcaseJob = `-- name: DeleteTestcaseJob :exec
DELETE FROM testcase_jobs WHERE id = $1
`

func (q *Queries) DeleteTestcaseJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTestcaseJob, id)
	return err
}

const listTestcaseJobs = `-- name: ListTestcaseJobs :many
SELECT id, dataset_id, codename, public, admin_id, input_digest, output, solution_id, user_test_id, state, error, created_at FROM testcase_jobs WHERE dataset_id = $1 ORDER BY id
`

// The dataset page: jobs still running or failed (testcase_jobs_dataset_idx).
func (q *Queries) ListTestcaseJobs(ctx context.Context, datasetID int64) ([]TestcaseJob, error) {
	rows, err := q.db.Query(ctx, listTestcaseJobs, datasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestcaseJob{}
	for rows.Next() {
		var i TestcaseJob
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.Codename,
			&i.Public,
			&i.AdminID,
			&i.InputDigest,
			&i.Output,
			&i.SolutionID,
			&i.UserTestID,
			&i.State,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTestcaseJobByUserTest = `-- name: LockTestcaseJobByUserTest :one
SELECT id, dataset_id, codename, public, admin_id, input_digest, output, solution_id, user_test_id, state, error, created_at FROM testcase_jobs WHERE user_test_id = $1 AND state IN ('input', 'output') FOR UPDATE
`

// The dispatcher: the job waiting for a run that ended (testcase_jobs_user_test_idx).
func (q *Queries) LockTestcaseJobByUserTest(ctx context.Context, userTestID *int64) (TestcaseJob, error) {
	row := q.db.QueryRow(ctx, lockTestcaseJobByUserTest, userTestID)
	var i TestcaseJob
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Codename,
		&i.Public,
		&i.AdminID,
		&i.InputDigest,
		&i.Output,
		&i.SolutionID,
		&i.UserTestID,
		&i.State,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const setTestcaseJobStep = `-- name: SetTestcaseJobStep :exec
UPDATE testcase_jobs SET state = $1, input_digest = $2, user_test_id = $3, error = $4
WHERE id = $5
`

type SetTestcaseJobStepParams struct {
	State       string  `json:"state"`
	InputDigest *string `json:"input_digest"`
	UserTestID  *int64  `json:"user_test_id"`
	Error       string  `json:"error"`
	ID          int64   `json:"id"`
}

func (q *Queries) SetTestcaseJobStep(ctx context.Context, arg SetTestcaseJobStepParams) error {
	_, err := q.db.Exec(ctx, setTestcaseJobStep,
		arg.State,
		arg.InputDigest,
		arg.UserTestID,
		arg.Error,
		arg.ID,
	)
	return err
}
