// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_tests.sql

package sqlc

import (
	"context"
	"time"
)

const createUserTest = `-- name: CreateUserTest :one
INSERT INTO user_tests (participation_id, task_id, submitted_at, language, input_digest)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, participation_id, task_id, submitted_at, language, input_digest
`

type CreateUserTestParams struct {
	ParticipationID int64     `json:"participation_id"`
	TaskID          int64     `json:"task_id"`
	SubmittedAt     time.Time `json:"submitted_at"`
	Language        *string   `json:"language"`
	InputDigest     string    `json:"input_digest"`
}

func (q *Queries) CreateUserTest(ctx context.Context, arg CreateUserTestParams) (UserTest, error) {
	row := q.db.QueryRow(ctx, createUserTest,
		arg.ParticipationID,
		arg.TaskID,
		arg.SubmittedAt,
		arg.Language,
		arg.InputDigest,
	)
	var i UserTest
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.SubmittedAt,
		&i.Language,
		&i.InputDigest,
	)
	return i, err
}

type CreateUserTestFilesParams struct {
	UserTestID int64  `json:"user_test_id"`
	Filename   string `json:"filename"`
	Digest     string `json:"digest"`
}

const ensureUserTestResult = `-- name: EnsureUserTestResult :exec
INSERT INTO user_test_results (user_test_id, dataset_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type EnsureUserTestResultParams struct {
	UserTestID int64 `json:"user_test_id"`
	DatasetID  int64 `json:"dataset_id"`
}

func (q *Queries) EnsureUserTestResult(ctx context.Context, arg EnsureUserTestResultParams) error {
	_, err := q.db.Exec(ctx, ensureUserTestResult, arg.UserTestID, arg.DatasetID)
	return err
}

const getUserTest = `-- name: GetUserTest :one
SELECT id, participation_id, task_id, submitted_at, language, input_digest FROM user_tests WHERE id = $1
`

func (q *Queries) GetUserTest(ctx context.Context, id int64) (UserTest, error) {
	row := q.db.QueryRow(ctx, getUserTest, id)
	var i UserTest
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.SubmittedAt,
		&i.Language,
		&i.InputDigest,
	)
	return i, err
}

const getUserTestResult = `-- name: GetUserTestResult :one
SELECT user_test_id, dataset_id, generation, compilation_outcome, compilation_text, compilation_stdout, compilation_stderr, compilation_tries, compilation_time, compilation_wall_time, compilation_memory, evaluation_outcome, evaluation_text, evaluation_tries, output_digest, execution_time, execution_wall_time, execution_memory, exit_status, system_error, completed_at, jobs_enqueued_at FROM user_test_results WHERE user_test_id = $1 AND dataset_id = $2
`

type GetUserTestResultParams struct {
	UserTestID int64 `json:"user_test_id"`
	DatasetID  int64 `json:"dataset_id"`
}

func (q *Queries) GetUserTestResult(ctx context.Context, arg GetUserTestResultParams) (UserTestResult, error) {
	row := q.db.QueryRow(ctx, getUserTestResult, arg.UserTestID, arg.DatasetID)
	var i UserTestResult
	err := row.Scan(
		&i.UserTestID,
		&i.DatasetID,
		&i.Generation,
		&i.CompilationOutcome,
		&i.CompilationText,
		&i.CompilationStdout,
		&i.CompilationStderr,
		&i.CompilationTries,
		&i.CompilationTime,
		&i.CompilationWallTime,
		&i.CompilationMemory,
		&i.EvaluationOutcome,
		&i.EvaluationText,
		&i.EvaluationTries,
		&i.OutputDigest,
		&i.ExecutionTime,
		&i.ExecutionWallTime,
		&i.ExecutionMemory,
		&i.ExitStatus,
		&i.SystemError,
		&i.CompletedAt,
		&i.JobsEnqueuedAt,
	)
	return i, err
}

const getUserTestWithResult = `-- name: GetUserTestWithResult :one
SELECT u.id, u.participation_id, u.task_id, u.submitted_at, u.language, u.input_digest,
       r.compilation_outcome, r.compilation_text, r.compilation_stdout, r.compilation_stderr,
       r.evaluation_text, r.exit_status, r.execution_time, r.execution_memory, r.output_digest,
       r.system_error, r.completed_at
FROM user_tests u
LEFT JOIN user_test_results r ON r.user_test_id = u.id AND r.dataset_id = $1::bigint
WHERE u.id = $2::bigint
`

type GetUserTestWithResultParams struct {
	DatasetID int64 `json:"dataset_id"`
	ID        int64 `json:"id"`
}

type GetUserTestWithResultRow struct {
	ID                 int64      `json:"id"`
	ParticipationID    int64      `json:"participation_id"`
	TaskID             int64      `json:"task_id"`
	SubmittedAt        time.Time  `json:"submitted_at"`
	Language           *string    `json:"language"`
	InputDigest        string     `json:"input_digest"`
	CompilationOutcome *string    `json:"compilation_outcome"`
	CompilationText    *string    `json:"compilation_text"`
	CompilationStdout  *string    `json:"compilation_stdout"`
	CompilationStderr  *string    `json:"compilation_stderr"`
	EvaluationText     *string    `json:"evaluation_text"`
	ExitStatus         *string    `json:"exit_status"`
	ExecutionTime      *float64   `json:"execution_time"`
	ExecutionMemory    *int64     `json:"execution_memory"`
	OutputDigest       *string    `json:"output_digest"`
	SystemError        *string    `json:"system_error"`
	CompletedAt        *time.Time `json:"completed_at"`
}

func (q *Queries) GetUserTestWithResult(ctx context.Context, arg GetUserTestWithResultParams) (GetUserTestWithResultRow, error) {
	row := q.db.QueryRow(ctx, getUserTestWithResult, arg.DatasetID, arg.ID)
	var i GetUserTestWithResultRow
	err := row.Scan(
		&i.ID,
		&i.ParticipationID,
		&i.TaskID,
		&i.SubmittedAt,
		&i.Language,
		&i.InputDigest,
		&i.CompilationOutcome,
		&i.CompilationText,
		&i.CompilationStdout,
		&i.CompilationStderr,
		&i.EvaluationText,
		&i.ExitStatus,
		&i.ExecutionTime,
		&i.ExecutionMemory,
		&i.OutputDigest,
		&i.SystemError,
		&i.CompletedAt,
	)
	return i, err
}

const insertUserTestExecutable = `-- name: InsertUserTestExecutable :exec
INSERT INTO user_test_executables (user_test_id, dataset_id, filename, digest) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_test_id, dataset_id, filename) DO UPDATE SET digest = EXCLUDED.digest
`

type InsertUserTestExecutableParams struct {
	UserTestID int64  `json:"user_test_id"`
	DatasetID  int64  `json:"dataset_id"`
	Filename   string `json:"filename"`
	Digest     string `json:"digest"`
}

func (q *Queries) InsertUserTestExecutable(ctx context.Context, arg InsertUserTestExecutableParams) error {
	_, err := q.db.Exec(ctx, insertUserTestExecutable,
		arg.UserTestID,
		arg.DatasetID,
		arg.Filename,
		arg.Digest,
	)
	return err
}

const listPendingUserTestResults = `-- name: ListPendingUserTestResults :many
SELECT user_test_id, dataset_id, generation, compilation_outcome, compilation_tries, evaluation_tries
FROM user_test_results WHERE completed_at IS NULL ORDER BY user_test_id LIMIT $1
`

type ListPendingUserTestResultsRow struct {
	UserTestID         int64   `json:"user_test_id"`
	DatasetID          int64   `json:"dataset_id"`
	Generation         int32   `json:"generation"`
	CompilationOutcome *string `json:"compilation_outcome"`
	CompilationTries   int32   `json:"compilation_tries"`
	EvaluationTries    int32   `json:"evaluation_tries"`
}

func (q *Queries) ListPendingUserTestResults(ctx context.Context, limit int32) ([]ListPendingUserTestResultsRow, error) {
	rows, err := q.db.Query(ctx, listPendingUserTestResults, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingUserTestResultsRow{}
	for rows.Next() {
		var i ListPendingUserTestResultsRow
		if err := rows.Scan(
			&i.UserTestID,
			&i.DatasetID,
			&i.Generation,
			&i.CompilationOutcome,
			&i.CompilationTries,
			&i.EvaluationTries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTestExecutables = `-- name: ListUserTestExecutables :many
SELECT id, user_test_id, dataset_id, filename, digest FROM user_test_executables WHERE user_test_id = $1 AND dataset_id = $2 ORDER BY filename
`

type ListUserTestExecutablesParams struct {
	UserTestID int64 `json:"user_test_id"`
	DatasetID  int64 `json:"dataset_id"`
}

func (q *Queries) ListUserTestExecutables(ctx context.Context, arg ListUserTestExecutablesParams) ([]UserTestExecutable, error) {
	rows, err := q.db.Query(ctx, listUserTestExecutables, arg.UserTestID, arg.DatasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTestExecutable{}
	for rows.Next() {
		var i UserTestExecutable
		if err := rows.Scan(
			&i.ID,
			&i.UserTestID,
			&i.DatasetID,
			&i.Filename,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTestFiles = `-- name: ListUserTestFiles :many
SELECT id, user_test_id, filename, digest FROM user_test_files WHERE user_test_id = $1 ORDER BY filename
`

func (q *Queries) ListUserTestFiles(ctx context.Context, userTestID int64) ([]UserTestFile, error) {
	rows, err := q.db.Query(ctx, listUserTestFiles, userTestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTestFile{}
	for rows.Next() {
		var i UserTestFile
		if err := rows.Scan(
			&i.ID,
			&i.UserTestID,
			&i.Filename,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTestResultsByTests = `-- name: ListUserTestResultsByTests :many
SELECT user_test_id, dataset_id, generation, compilation_outcome, compilation_text, compilation_stdout, compilation_stderr, compilation_tries, compilation_time, compilation_wall_time, compilation_memory, evaluation_outcome, evaluation_text, evaluation_tries, output_digest, execution_time, execution_wall_time, execution_memory, exit_status, system_error, completed_at, jobs_enqueued_at FROM user_test_results WHERE user_test_id = ANY($1::bigint[]) AND dataset_id = ANY($2::bigint[])
`

type ListUserTestResultsByTestsParams struct {
	Ids        []int64 `json:"ids"`
	DatasetIds []int64 `json:"dataset_ids"`
}

func (q *Queries) ListUserTestResultsByTests(ctx context.Context, arg ListUserTestResultsByTestsParams) ([]UserTestResult, error) {
	rows, err := q.db.Query(ctx, listUserTestResultsByTests, arg.Ids, arg.DatasetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTestResult{}
	for rows.Next() {
		var i UserTestResult
		if err := rows.Scan(
			&i.UserTestID,
			&i.DatasetID,
			&i.Generation,
			&i.CompilationOutcome,
			&i.CompilationText,
			&i.CompilationStdout,
			&i.CompilationStderr,
			&i.CompilationTries,
			&i.CompilationTime,
			&i.CompilationWallTime,
			&i.CompilationMemory,
			&i.EvaluationOutcome,
			&i.EvaluationText,
			&i.EvaluationTries,
			&i.OutputDigest,
			&i.ExecutionTime,
			&i.ExecutionWallTime,
			&i.ExecutionMemory,
			&i.ExitStatus,
			&i.SystemError,
			&i.CompletedAt,
			&i.JobsEnqueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTestsByParticipationTask = `-- name: ListUserTestsByParticipationTask :many
SELECT id, participation_id, task_id, submitted_at, language, input_digest FROM user_tests WHERE participation_id = $1 AND task_id = $2 ORDER BY submitted_at, id
`

type ListUserTestsByParticipationTaskParams struct {
	ParticipationID int64 `json:"participation_id"`
	TaskID          int64 `json:"task_id"`
}

func (q *Queries) ListUserTestsByParticipationTask(ctx context.Context, arg ListUserTestsByParticipationTaskParams) ([]UserTest, error) {
	rows, err := q.db.Query(ctx, listUserTestsByParticipationTask, arg.ParticipationID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTest{}
	for rows.Next() {
		var i UserTest
		if err := rows.Scan(
			&i.ID,
			&i.ParticipationID,
			&i.TaskID,
			&i.SubmittedAt,
			&i.Language,
			&i.InputDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTestsWithResults = `-- name: ListUserTestsWithResults :many
SELECT u.id, u.submitted_at, u.language,
       r.compilation_outcome, r.compilation_text, r.compilation_stdout, r.compilation_stderr,
       r.evaluation_text, r.exit_status, r.execution_time, r.execution_memory, r.output_digest,
       r.system_error, r.completed_at
FROM user_tests u
LEFT JOIN user_test_results r ON r.user_test_id = u.id AND r.dataset_id = $1::bigint
WHERE u.participation_id = $2::bigint AND u.task_id = $3::bigint
ORDER BY u.submitted_at DESC, u.id DESC
LIMIT 50
`

type ListUserTestsWithResultsParams struct {
	DatasetID       int64 `json:"dataset_id"`
	ParticipationID int64 `json:"participation_id"`
	TaskID          int64 `json:"task_id"`
}

type ListUserTestsWithResultsRow struct {
	ID                 int64      `json:"id"`
	SubmittedAt        time.Time  `json:"submitted_at"`
	Language           *string    `json:"language"`
	CompilationOutcome *string    `json:"compilation_outcome"`
	CompilationText    *string    `json:"compilation_text"`
	CompilationStdout  *string    `json:"compilation_stdout"`
	CompilationStderr  *string    `json:"compilation_stderr"`
	EvaluationText     *string    `json:"evaluation_text"`
	ExitStatus         *string    `json:"exit_status"`
	ExecutionTime      *float64   `json:"execution_time"`
	ExecutionMemory    *int64     `json:"execution_memory"`
	OutputDigest       *string    `json:"output_digest"`
	SystemError        *string    `json:"system_error"`
	CompletedAt        *time.Time `json:"completed_at"`
}

// A contestant's latest tests on a task with their result on the live
// dataset (index: user_tests_participation_task_idx + result PK).
func (q *Queries) ListUserTestsWithResults(ctx context.Context, arg ListUserTestsWithResultsParams) ([]ListUserTestsWithResultsRow, error) {
	rows, err := q.db.Query(ctx, listUserTestsWithResults, arg.DatasetID, arg.ParticipationID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTestsWithResultsRow{}
	for rows.Next() {
		var i ListUserTestsWithResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedAt,
			&i.Language,
			&i.CompilationOutcome,
			&i.CompilationText,
			&i.CompilationStdout,
			&i.CompilationStderr,
			&i.EvaluationText,
			&i.ExitStatus,
			&i.ExecutionTime,
			&i.ExecutionMemory,
			&i.OutputDigest,
			&i.SystemError,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserTestCompilation = `-- name: SetUserTestCompilation :one
UPDATE user_test_results SET
    compilation_outcome = $3, compilation_text = $4, compilation_stdout = $5, compilation_stderr = $6,
    compilation_tries = compilation_tries + 1, compilation_time = $7, compilation_wall_time = $8,
    compilation_memory = $9, completed_at = CASE WHEN $3 = 'fail' THEN now() ELSE completed_at END
WHERE user_test_id = $1 AND dataset_id = $2 AND generation = $10::integer
RETURNING user_test_id
`

type SetUserTestCompilationParams struct {
	UserTestID          int64    `json:"user_test_id"`
	DatasetID           int64    `json:"dataset_id"`
	CompilationOutcome  *string  `json:"compilation_outcome"`
	CompilationText     string   `json:"compilation_text"`
	CompilationStdout   string   `json:"compilation_stdout"`
	CompilationStderr   string   `json:"compilation_stderr"`
	CompilationTime     *float64 `json:"compilation_time"`
	CompilationWallTime *float64 `json:"compilation_wall_time"`
	CompilationMemory   *int64   `json:"compilation_memory"`
	Generation          int32    `json:"generation"`
}

func (q *Queries) SetUserTestCompilation(ctx context.Context, arg SetUserTestCompilationParams) (int64, error) {
	row := q.db.QueryRow(ctx, setUserTestCompilation,
		arg.UserTestID,
		arg.DatasetID,
		arg.CompilationOutcome,
		arg.CompilationText,
		arg.CompilationStdout,
		arg.CompilationStderr,
		arg.CompilationTime,
		arg.CompilationWallTime,
		arg.CompilationMemory,
		arg.Generation,
	)
	var user_test_id int64
	err := row.Scan(&user_test_id)
	return user_test_id, err
}

const setUserTestEvaluation = `-- name: SetUserTestEvaluation :one
UPDATE user_test_results SET
    evaluation_outcome = 'ok', evaluation_text = $3, evaluation_tries = evaluation_tries + 1,
    output_digest = $4, execution_time = $5, execution_wall_time = $6, execution_memory = $7,
    exit_status = $8, completed_at = now()
WHERE user_test_id = $1 AND dataset_id = $2 AND generation = $9::integer
RETURNING user_test_id
`

type SetUserTestEvaluationParams struct {
	UserTestID        int64    `json:"user_test_id"`
	DatasetID         int64    `json:"dataset_id"`
	EvaluationText    string   `json:"evaluation_text"`
	OutputDigest      *string  `json:"output_digest"`
	ExecutionTime     *float64 `json:"execution_time"`
	ExecutionWallTime *float64 `json:"execution_wall_time"`
	ExecutionMemory   *int64   `json:"execution_memory"`
	ExitStatus        *string  `json:"exit_status"`
	Generation        int32    `json:"generation"`
}

func (q *Queries) SetUserTestEvaluation(ctx context.Context, arg SetUserTestEvaluationParams) (int64, error) {
	row := q.db.QueryRow(ctx, setUserTestEvaluation,
		arg.UserTestID,
		arg.DatasetID,
		arg.EvaluationText,
		arg.OutputDigest,
		arg.ExecutionTime,
		arg.ExecutionWallTime,
		arg.ExecutionMemory,
		arg.ExitStatus,
		arg.Generation,
	)
	var user_test_id int64
	err := row.Scan(&user_test_id)
	return user_test_id, err
}

const setUserTestSystemError = `-- name: SetUserTestSystemError :exec
UPDATE user_test_results SET system_error = $3, completed_at = now() WHERE user_test_id = $1 AND dataset_id = $2
`

type SetUserTestSystemErrorParams struct {
	UserTestID  int64   `json:"user_test_id"`
	DatasetID   int64   `json:"dataset_id"`
	SystemError *string `json:"system_error"`
}

func (q *Queries) SetUserTestSystemError(ctx context.Context, arg SetUserTestSystemErrorParams) error {
	_, err := q.db.Exec(ctx, setUserTestSystemError, arg.UserTestID, arg.DatasetID, arg.SystemError)
	return err
}

const userTestStats = `-- name: UserTestStats :one
SELECT count(*)::bigint AS contest_count,
       (count(*) FILTER (WHERE task_id = $1::bigint))::bigint AS task_count,
       COALESCE(max(submitted_at), 'epoch')::timestamptz AS contest_last,
       COALESCE(max(submitted_at) FILTER (WHERE task_id = $1::bigint), 'epoch')::timestamptz AS task_last
FROM user_tests WHERE participation_id = $2::bigint
`

type UserTestStatsParams struct {
	TaskID          int64 `json:"task_id"`
	ParticipationID int64 `json:"participation_id"`
}

type UserTestStatsRow struct {
	ContestCount int64     `json:"contest_count"`
	TaskCount    int64     `json:"task_count"`
	ContestLast  time.Time `json:"contest_last"`
	TaskLast     time.Time `json:"task_last"`
}

func (q *Queries) UserTestStats(ctx context.Context, arg UserTestStatsParams) (UserTestStatsRow, error) {
	row := q.db.QueryRow(ctx, userTestStats, arg.TaskID, arg.ParticipationID)
	var i UserTestStatsRow
	err := row.Scan(
		&i.ContestCount,
		&i.TaskCount,
		&i.ContestLast,
		&i.TaskLast,
	)
	return i, err
}
