// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"
)

const bumpLoginNonce = `-- name: BumpLoginNonce :one
UPDATE participations SET login_nonce = login_nonce + 1 WHERE id = $1 RETURNING login_nonce
`

func (q *Queries) BumpLoginNonce(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, bumpLoginNonce, id)
	var login_nonce int64
	err := row.Scan(&login_nonce)
	return login_nonce, err
}

const createParticipation = `-- name: CreateParticipation :one
INSERT INTO participations (contest_id, user_id, team_id, password_hash, ip, delay_time_s, extra_time_s, hidden, unrestricted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, contest_id, user_id, team_id, password_hash, ip, starting_time, delay_time_s, extra_time_s, hidden, unrestricted, login_nonce
`

type CreateParticipationParams struct {
	ContestID    int64          `json:"contest_id"`
	UserID       int64          `json:"user_id"`
	TeamID       *int64         `json:"team_id"`
	PasswordHash *string        `json:"password_hash"`
	Ip           []netip.Prefix `json:"ip"`
	DelayTimeS   int64          `json:"delay_time_s"`
	ExtraTimeS   int64          `json:"extra_time_s"`
	Hidden       bool           `json:"hidden"`
	Unrestricted bool           `json:"unrestricted"`
}

func (q *Queries) CreateParticipation(ctx context.Context, arg CreateParticipationParams) (Participation, error) {
	row := q.db.QueryRow(ctx, createParticipation,
		arg.ContestID,
		arg.UserID,
		arg.TeamID,
		arg.PasswordHash,
		arg.Ip,
		arg.DelayTimeS,
		arg.ExtraTimeS,
		arg.Hidden,
		arg.Unrestricted,
	)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.TeamID,
		&i.PasswordHash,
		&i.Ip,
		&i.StartingTime,
		&i.DelayTimeS,
		&i.ExtraTimeS,
		&i.Hidden,
		&i.Unrestricted,
		&i.LoginNonce,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (code, name, flag_digest, photo_digest) VALUES ($1, $2, $3, $4) RETURNING id, code, name, flag_digest, photo_digest
`

type CreateTeamParams struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	FlagDigest  *string `json:"flag_digest"`
	PhotoDigest *string `json:"photo_digest"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Code,
		arg.Name,
		arg.FlagDigest,
		arg.PhotoDigest,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.FlagDigest,
		&i.PhotoDigest,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, first_name, last_name, email, password_hash, timezone, preferred_languages)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, first_name, last_name, email, password_hash, timezone, preferred_languages, created_at
`

type CreateUserParams struct {
	Username           string   `json:"username"`
	FirstName          string   `json:"first_name"`
	LastName           string   `json:"last_name"`
	Email              string   `json:"email"`
	PasswordHash       string   `json:"password_hash"`
	Timezone           *string  `json:"timezone"`
	PreferredLanguages []string `json:"preferred_languages"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Timezone,
		arg.PreferredLanguages,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.PreferredLanguages,
		&i.CreatedAt,
	)
	return i, err
}

const deleteParticipation = `-- name: DeleteParticipation :exec
DELETE FROM participations WHERE id = $1
`

func (q *Queries) DeleteParticipation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteParticipation, id)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getLoginCandidate = `-- name: GetLoginCandidate :one
SELECT p.id AS participation_id, p.password_hash AS participation_password_hash, p.ip, p.hidden,
       p.login_nonce, u.id AS user_id, u.username, u.password_hash AS user_password_hash
FROM participations p JOIN users u ON u.id = p.user_id
WHERE p.contest_id = $1 AND u.username = $2
`

type GetLoginCandidateParams struct {
	ContestID int64  `json:"contest_id"`
	Username  string `json:"username"`
}

type GetLoginCandidateRow struct {
	ParticipationID           int64          `json:"participation_id"`
	ParticipationPasswordHash *string        `json:"participation_password_hash"`
	Ip                        []netip.Prefix `json:"ip"`
	Hidden                    bool           `json:"hidden"`
	LoginNonce                int64          `json:"login_nonce"`
	UserID                    int64          `json:"user_id"`
	Username                  string         `json:"username"`
	UserPasswordHash          string         `json:"user_password_hash"`
}

// Everything CWS needs to authenticate a contestant, in one round trip.
func (q *Queries) GetLoginCandidate(ctx context.Context, arg GetLoginCandidateParams) (GetLoginCandidateRow, error) {
	row := q.db.QueryRow(ctx, getLoginCandidate, arg.ContestID, arg.Username)
	var i GetLoginCandidateRow
	err := row.Scan(
		&i.ParticipationID,
		&i.ParticipationPasswordHash,
		&i.Ip,
		&i.Hidden,
		&i.LoginNonce,
		&i.UserID,
		&i.Username,
		&i.UserPasswordHash,
	)
	return i, err
}

const getParticipation = `-- name: GetParticipation :one
SELECT id, contest_id, user_id, team_id, password_hash, ip, starting_time, delay_time_s, extra_time_s, hidden, unrestricted, login_nonce FROM participations WHERE id = $1
`

func (q *Queries) GetParticipation(ctx context.Context, id int64) (Participation, error) {
	row := q.db.QueryRow(ctx, getParticipation, id)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.TeamID,
		&i.PasswordHash,
		&i.Ip,
		&i.StartingTime,
		&i.DelayTimeS,
		&i.ExtraTimeS,
		&i.Hidden,
		&i.Unrestricted,
		&i.LoginNonce,
	)
	return i, err
}

const getParticipationByContestUser = `-- name: GetParticipationByContestUser :one
SELECT id, contest_id, user_id, team_id, password_hash, ip, starting_time, delay_time_s, extra_time_s, hidden, unrestricted, login_nonce FROM participations WHERE contest_id = $1 AND user_id = $2
`

type GetParticipationByContestUserParams struct {
	ContestID int64 `json:"contest_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetParticipationByContestUser(ctx context.Context, arg GetParticipationByContestUserParams) (Participation, error) {
	row := q.db.QueryRow(ctx, getParticipationByContestUser, arg.ContestID, arg.UserID)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.TeamID,
		&i.PasswordHash,
		&i.Ip,
		&i.StartingTime,
		&i.DelayTimeS,
		&i.ExtraTimeS,
		&i.Hidden,
		&i.Unrestricted,
		&i.LoginNonce,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, code, name, flag_digest, photo_digest FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.FlagDigest,
		&i.PhotoDigest,
	)
	return i, err
}

const getTeamByCode = `-- name: GetTeamByCode :one
SELECT id, code, name, flag_digest, photo_digest FROM teams WHERE code = $1
`

func (q *Queries) GetTeamByCode(ctx context.Context, code string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByCode, code)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.FlagDigest,
		&i.PhotoDigest,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, first_name, last_name, email, password_hash, timezone, preferred_languages, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.PreferredLanguages,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, first_name, last_name, email, password_hash, timezone, preferred_languages, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.PreferredLanguages,
		&i.CreatedAt,
	)
	return i, err
}

const listParticipationsByContest = `-- name: ListParticipationsByContest :many
SELECT p.id, p.contest_id, p.user_id, p.team_id, p.password_hash, p.ip, p.starting_time, p.delay_time_s, p.extra_time_s, p.hidden, p.unrestricted, p.login_nonce, u.username, u.first_name, u.last_name, u.timezone AS user_timezone,
       t.code AS team_code, t.name AS team_name
FROM participations p
JOIN users u ON u.id = p.user_id
LEFT JOIN teams t ON t.id = p.team_id
WHERE p.contest_id = $1
ORDER BY u.username
`

type ListParticipationsByContestRow struct {
	Participation Participation `json:"participation"`
	Username      string        `json:"username"`
	FirstName     string        `json:"first_name"`
	LastName      string        `json:"last_name"`
	UserTimezone  *string       `json:"user_timezone"`
	TeamCode      *string       `json:"team_code"`
	TeamName      *string       `json:"team_name"`
}

func (q *Queries) ListParticipationsByContest(ctx context.Context, contestID int64) ([]ListParticipationsByContestRow, error) {
	rows, err := q.db.Query(ctx, listParticipationsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipationsByContestRow{}
	for rows.Next() {
		var i ListParticipationsByContestRow
		if err := rows.Scan(
			&i.Participation.ID,
			&i.Participation.ContestID,
			&i.Participation.UserID,
			&i.Participation.TeamID,
			&i.Participation.PasswordHash,
			&i.Participation.Ip,
			&i.Participation.StartingTime,
			&i.Participation.DelayTimeS,
			&i.Participation.ExtraTimeS,
			&i.Participation.Hidden,
			&i.Participation.Unrestricted,
			&i.Participation.LoginNonce,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.UserTimezone,
			&i.TeamCode,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipationsByUser = `-- name: ListParticipationsByUser :many
SELECT id, contest_id, user_id, team_id, password_hash, ip, starting_time, delay_time_s, extra_time_s, hidden, unrestricted, login_nonce FROM participations WHERE user_id = $1 ORDER BY contest_id
`

func (q *Queries) ListParticipationsByUser(ctx context.Context, userID int64) ([]Participation, error) {
	rows, err := q.db.Query(ctx, listParticipationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participation{}
	for rows.Next() {
		var i Participation
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.TeamID,
			&i.PasswordHash,
			&i.Ip,
			&i.StartingTime,
			&i.DelayTimeS,
			&i.ExtraTimeS,
			&i.Hidden,
			&i.Unrestricted,
			&i.LoginNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipationsWithIP = `-- name: ListParticipationsWithIP :many
SELECT p.id, p.ip, p.login_nonce FROM participations p WHERE p.contest_id = $1 AND cardinality(p.ip) > 0
`

type ListParticipationsWithIPRow struct {
	ID         int64          `json:"id"`
	Ip         []netip.Prefix `json:"ip"`
	LoginNonce int64          `json:"login_nonce"`
}

// Candidates for IP autologin.
func (q *Queries) ListParticipationsWithIP(ctx context.Context, contestID int64) ([]ListParticipationsWithIPRow, error) {
	rows, err := q.db.Query(ctx, listParticipationsWithIP, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipationsWithIPRow{}
	for rows.Next() {
		var i ListParticipationsWithIPRow
		if err := rows.Scan(&i.ID, &i.Ip, &i.LoginNonce); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, code, name, flag_digest, photo_digest FROM teams ORDER BY code
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.FlagDigest,
			&i.PhotoDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, first_name, last_name, email, password_hash, timezone, preferred_languages, created_at FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.Timezone,
			&i.PreferredLanguages,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setParticipationPassword = `-- name: SetParticipationPassword :exec
UPDATE participations SET password_hash = $2 WHERE id = $1
`

type SetParticipationPasswordParams struct {
	ID           int64   `json:"id"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) SetParticipationPassword(ctx context.Context, arg SetParticipationPasswordParams) error {
	_, err := q.db.Exec(ctx, setParticipationPassword, arg.ID, arg.PasswordHash)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const startParticipation = `-- name: StartParticipation :one
UPDATE participations SET starting_time = COALESCE(starting_time, $2) WHERE id = $1 RETURNING id, contest_id, user_id, team_id, password_hash, ip, starting_time, delay_time_s, extra_time_s, hidden, unrestricted, login_nonce
`

type StartParticipationParams struct {
	ID           int64      `json:"id"`
	StartingTime *time.Time `json:"starting_time"`
}

// Sets the per-user start time once (idempotent).
func (q *Queries) StartParticipation(ctx context.Context, arg StartParticipationParams) (Participation, error) {
	row := q.db.QueryRow(ctx, startParticipation, arg.ID, arg.StartingTime)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.TeamID,
		&i.PasswordHash,
		&i.Ip,
		&i.StartingTime,
		&i.DelayTimeS,
		&i.ExtraTimeS,
		&i.Hidden,
		&i.Unrestricted,
		&i.LoginNonce,
	)
	return i, err
}

const updateParticipation = `-- name: UpdateParticipation :one
UPDATE participations SET team_id = $2, ip = $3, delay_time_s = $4, extra_time_s = $5, hidden = $6, unrestricted = $7, starting_time = $8
WHERE id = $1
RETURNING id, contest_id, user_id, team_id, password_hash, ip, starting_time, delay_time_s, extra_time_s, hidden, unrestricted, login_nonce
`

type UpdateParticipationParams struct {
	ID           int64          `json:"id"`
	TeamID       *int64         `json:"team_id"`
	Ip           []netip.Prefix `json:"ip"`
	DelayTimeS   int64          `json:"delay_time_s"`
	ExtraTimeS   int64          `json:"extra_time_s"`
	Hidden       bool           `json:"hidden"`
	Unrestricted bool           `json:"unrestricted"`
	StartingTime *time.Time     `json:"starting_time"`
}

func (q *Queries) UpdateParticipation(ctx context.Context, arg UpdateParticipationParams) (Participation, error) {
	row := q.db.QueryRow(ctx, updateParticipation,
		arg.ID,
		arg.TeamID,
		arg.Ip,
		arg.DelayTimeS,
		arg.ExtraTimeS,
		arg.Hidden,
		arg.Unrestricted,
		arg.StartingTime,
	)
	var i Participation
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.TeamID,
		&i.PasswordHash,
		&i.Ip,
		&i.StartingTime,
		&i.DelayTimeS,
		&i.ExtraTimeS,
		&i.Hidden,
		&i.Unrestricted,
		&i.LoginNonce,
	)
	return i, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET code = $2, name = $3, flag_digest = $4, photo_digest = $5 WHERE id = $1 RETURNING id, code, name, flag_digest, photo_digest
`

type UpdateTeamParams struct {
	ID          int64   `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	FlagDigest  *string `json:"flag_digest"`
	PhotoDigest *string `json:"photo_digest"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.FlagDigest,
		arg.PhotoDigest,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.FlagDigest,
		&i.PhotoDigest,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET username = $2, first_name = $3, last_name = $4, email = $5, timezone = $6, preferred_languages = $7
WHERE id = $1
RETURNING id, username, first_name, last_name, email, password_hash, timezone, preferred_languages, created_at
`

type UpdateUserParams struct {
	ID                 int64    `json:"id"`
	Username           string   `json:"username"`
	FirstName          string   `json:"first_name"`
	LastName           string   `json:"last_name"`
	Email              string   `json:"email"`
	Timezone           *string  `json:"timezone"`
	PreferredLanguages []string `json:"preferred_languages"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Timezone,
		arg.PreferredLanguages,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.PreferredLanguages,
		&i.CreatedAt,
	)
	return i, err
}
