id: cpp17
name: "C++17 / g++"
version_command: ["g++", "--version"]
source_extensions: [".cpp", ".cc", ".cxx", ".c++"]
header_extensions: [".h", ".hpp"]
compile:
  - ["/usr/bin/g++", "-DEVAL", "-std=gnu++17", "-O2", "-pipe", "-static", "-s", "-o", "{executable}", "{sources}"]
executable: "{main}"
run: ["./{executable}"]
