// Package extract lists the messages of the contestant and ranking sites
// (what a new interface language translates): the texts their templates
// translate, and the catalog keys that appear as string literals in the
// Go packages whose messages reach contestants.
package extract

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/D4ND3R/Contest-Management-System/internal/i18n"
)

// Templates of the two public sites.
var templateDirs = []string{"web/templates/cws", "web/templates/rws"}

// Go packages whose messages reach contestants: the two sites and what
// produces evaluation messages, statuses and medals. Only literals that
// are catalog keys count (the Spanish catalog covers every shown string).
var goDirs = []string{"internal/contestweb", "internal/rankingweb", "internal/ranking", "internal/tasktypes",
	"internal/checkers", "internal/worker", "internal/sandbox", "internal/scoring", "internal/statement", "internal/printing",
	"internal/webkit"}

var tmplRe = regexp.MustCompile(`\.T "((?:[^"\\]|\\.)*)"`)

// Collect lists the contestant-facing messages under root (the module
// directory), sorted.
func Collect(root string) ([]string, error) {
	set := map[string]bool{}
	for _, dir := range templateDirs {
		files, _ := filepath.Glob(filepath.Join(root, dir, "*.html"))
		for _, f := range files {
			b, err := os.ReadFile(f)
			if err != nil {
				return nil, err
			}
			for _, m := range tmplRe.FindAllStringSubmatch(string(b), -1) {
				s, err := strconv.Unquote(`"` + m[1] + `"`)
				if err != nil {
					return nil, fmt.Errorf("%s: %w", f, err)
				}
				set[s] = true
			}
		}
	}
	fset := token.NewFileSet()
	for _, dir := range goDirs {
		files, _ := filepath.Glob(filepath.Join(root, dir, "*.go"))
		for _, f := range files {
			if strings.HasSuffix(f, "_test.go") || strings.HasSuffix(f, "icons.go") { // icon names are not text
				continue
			}
			file, err := parser.ParseFile(fset, f, nil, 0)
			if err != nil {
				return nil, err
			}
			ast.Inspect(file, func(n ast.Node) bool {
				lit, ok := n.(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					return true
				}
				s, err := strconv.Unquote(lit.Value)
				if err != nil || strings.TrimSpace(s) == "" {
					return true
				}
				for _, k := range []string{s, strings.TrimSuffix(s, " ")} {
					if i18n.Has("es", k) && k != "" {
						set[k] = true
					}
				}
				return true
			})
		}
	}
	keys := make([]string, 0, len(set))
	for k := range set {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys, nil
}

// File is the content of contestant.txt for keys.
func File(keys []string) []byte {
	var b strings.Builder
	b.WriteString("# Generated by internal/i18n/gen (make generate): the messages of the contestant and\n")
	b.WriteString("# ranking sites, which a new UI language translates. Do not edit.\n")
	for _, k := range keys {
		b.WriteString(strconv.Quote(k) + "\n")
	}
	return []byte(b.String())
}
