-- Testcases made in the admin (SPEC_MIN §13, §14): typed one by one, or
-- generated by a program and answered by a reference solution. Both run
-- as user tests owned by an administrator instead of a participation.

-- An administrator's run has no participation; it may target a dataset
-- other than the live one, and a "plain" run (a generator) ignores the
-- task type: standard input in, standard output out, no managers.
ALTER TABLE user_tests ALTER COLUMN participation_id DROP NOT NULL,
    ADD COLUMN admin_id bigint REFERENCES admins(id) ON DELETE SET NULL,
    ADD COLUMN dataset_id bigint REFERENCES datasets(id) ON DELETE CASCADE,
    ADD COLUMN plain boolean NOT NULL DEFAULT false;

-- A testcase on its way: the input is typed or comes from a generator
-- run, the output from a reference solution run (or it is empty). The
-- dispatcher moves a job forward when its run ends and stores the
-- testcase at the end.
CREATE TABLE testcase_jobs (
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dataset_id   bigint NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    codename     text NOT NULL,
    public       boolean NOT NULL DEFAULT false,
    admin_id     bigint REFERENCES admins(id) ON DELETE SET NULL,
    input_digest sha256_digest,
    -- Where the output comes from: a reference solution (a task tester
    -- run, solution_id) or nothing (interactive tasks, checkers that only
    -- read the input).
    output       text NOT NULL CHECK (output IN ('solution', 'empty')),
    solution_id  bigint REFERENCES submissions(id) ON DELETE SET NULL,
    user_test_id bigint REFERENCES user_tests(id) ON DELETE SET NULL,
    state        text NOT NULL CHECK (state IN ('input', 'output', 'done', 'failed')),
    error        text NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now()
);
-- The dataset page lists the dataset's jobs, newest first.
CREATE INDEX testcase_jobs_dataset_idx ON testcase_jobs (dataset_id, id);
-- The dispatcher finds the job of a run that ended.
CREATE INDEX testcase_jobs_user_test_idx ON testcase_jobs (user_test_id) WHERE user_test_id IS NOT NULL;
