#!/usr/bin/env bash
# cms-host-tuning: settings that make running times stable on a judging
# machine (SPEC_IOI §2.2). Installed as /usr/local/sbin/cms-host-tuning.
#
#   cms-host-tuning status    show the current state
#   cms-host-tuning apply     apply the settings now (until the next boot)
#   cms-host-tuning enable    apply them now and at every boot (systemd unit)
#   cms-host-tuning disable   stop applying them at boot (a reboot restores
#                             the kernel defaults)
#
# What is changed is read from /etc/cms/host-tuning.conf (created with the
# defaults below on first use):
#
#   GOVERNOR=performance   CPU frequency governor ("" = leave it)
#   TURBO=off              turbo boost / CPU boost (off | leave)
#   THP=never              transparent huge pages (never | leave)
#   ASLR=leave             address space layout randomization (off | leave):
#                          off gives slightly more reproducible times but
#                          weakens every program on the machine; only on a
#                          dedicated judging machine
#   SMT=leave              hyperthreading (off | leave): the installer already
#                          leaves the siblings of judging CPUs idle
#
# On a machine shared with other services, these settings affect them too
# (more power, less turbo): prefer them on dedicated judging machines.
set -euo pipefail

CONF=${CMS_TUNING_CONF:-/etc/cms/host-tuning.conf}
SYS=${CMS_TUNING_SYSFS:-/sys}
PROC=${CMS_TUNING_PROC:-/proc}
UNIT=/etc/systemd/system/cms-host-tuning.service

GOVERNOR=performance TURBO=off THP=never ASLR=leave SMT=leave

say() { printf '%s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

load() {
  if [ ! -f "$CONF" ]; then
    [ -w "$(dirname "$CONF")" ] || return 0
    cat > "$CONF" <<EOF
# cms-host-tuning settings (see cms-host-tuning --help).
GOVERNOR=performance
TURBO=off
THP=never
ASLR=leave
SMT=leave
EOF
  fi
  # shellcheck disable=SC1090
  . "$CONF"
}

# put writes a value into a kernel file when it exists and differs.
put() {
  local f=$1 v=$2
  [ -w "$f" ] || return 0
  # Selection files read "always madvise [never]".
  case " $(cat "$f" 2>/dev/null) " in *" $v "*|*"[$v]"*) return 0 ;; esac
  if echo "$v" > "$f" 2>/dev/null; then say "  $f = $v"; else say "  could not set $f"; fi
}

apply() {
  local f
  [ "$(id -u)" = 0 ] || [ -n "${CMS_TUNING_SYSFS:-}" ] || die "run as root"
  say "applying $CONF"
  if [ -n "$GOVERNOR" ]; then
    for f in "$SYS"/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor; do
      [ -e "$f" ] && put "$f" "$GOVERNOR"
    done
  fi
  if [ "$TURBO" = off ]; then
    put "$SYS/devices/system/cpu/intel_pstate/no_turbo" 1
    put "$SYS/devices/system/cpu/cpufreq/boost" 0
  fi
  if [ "$THP" = never ]; then
    put "$SYS/kernel/mm/transparent_hugepage/enabled" never
    put "$SYS/kernel/mm/transparent_hugepage/defrag" never
    put "$SYS/kernel/mm/transparent_hugepage/khugepaged/defrag" 0
  fi
  [ "$ASLR" = off ] && put "$PROC/sys/kernel/randomize_va_space" 0
  [ "$SMT" = off ] && put "$SYS/devices/system/cpu/smt/control" off
  return 0
}

status() {
  local g
  g=$(cat "$SYS"/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor 2>/dev/null | sort -u | tr '\n' ' ')
  say "governor:            ${g:-not exposed}"
  if [ -f "$SYS/devices/system/cpu/intel_pstate/no_turbo" ]; then
    say "turbo:               $([ "$(cat "$SYS/devices/system/cpu/intel_pstate/no_turbo")" = 1 ] && echo off || echo on)"
  elif [ -f "$SYS/devices/system/cpu/cpufreq/boost" ]; then
    say "boost:               $([ "$(cat "$SYS/devices/system/cpu/cpufreq/boost")" = 0 ] && echo off || echo on)"
  else
    say "turbo:               not exposed"
  fi
  say "transparent hugepages: $(cat "$SYS/kernel/mm/transparent_hugepage/enabled" 2>/dev/null || echo 'not exposed')"
  say "ASLR:                $(cat "$PROC/sys/kernel/randomize_va_space" 2>/dev/null || echo '?') (0 = off)"
  say "SMT:                 $(cat "$SYS/devices/system/cpu/smt/control" 2>/dev/null || echo 'not exposed')"
  if [ -f "$UNIT" ]; then say "at boot:             $(systemctl is-enabled cms-host-tuning 2>/dev/null || echo unknown)"
  else say "at boot:             not enabled (cms-host-tuning enable)"; fi
}

enable() {
  [ "$(id -u)" = 0 ] || die "run as root"
  cat > "$UNIT" <<EOF
# Generated by cms-host-tuning: stable running times for judging.
[Unit]
Description=CMS judging host tuning (governor, turbo, huge pages)
After=sysinit.target
Before=cms-worker.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/cms-host-tuning apply
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable cms-host-tuning >/dev/null 2>&1
  apply
  say "enabled at boot (cms-host-tuning.service)"
}

disable() {
  [ "$(id -u)" = 0 ] || die "run as root"
  if [ -f "$UNIT" ]; then
    systemctl disable cms-host-tuning >/dev/null 2>&1 || true
    rm -f "$UNIT"
    systemctl daemon-reload
  fi
  say "no longer applied at boot; reboot to restore the kernel defaults"
}

case "${1:-status}" in
  status) load; status ;;
  apply) load; apply ;;
  enable) load; enable ;;
  disable) disable ;;
  -h|--help|help) awk 'NR > 1 { if (/^#/) print; else exit }' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//' ;;
  *) die "usage: cms-host-tuning status|apply|enable|disable" ;;
esac
